Repository boltdesignsystem/bolt, pull requests merged in 2018-11, with the labels that each got.

#919 Support row_gutter in IE
  apps/pattern-lab/src/_patterns/02-components/grid/10-grid-row-gutter-variations.twig
  apps/pattern-lab/src/_patterns/02-components/grid/20-grid-vinset-variations.twig
  packages/components/bolt-grid/src/grid.scss
Labels: bug

#943 WIP: Add example of navbar without links (BDS-748)
  apps/pattern-lab/src/_patterns/02-components/navbar/40-navbar--no-links.twig
Labels: WIP

#966 Fix: Temporarily Disable “Pretty” HTML in Pattern Lab Code Viewer
  apps/pattern-lab/composer.patches.json
Labels: maintenance
