Repository boltdesignsystem/bolt, pull requests merged in 2019-11, with the labels that each got.

#1516 Bolt Action | FE | Refactor Bolt Action components
  packages/api/__snapshots__/index.test.js.snap
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/src/_button-settings-and-tools.scss
  packages/components/bolt-button/src/button.js
  packages/components/bolt-button/src/button.scss
  packages/components/bolt-button/src/button.twig
  packages/components/bolt-card/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-chip/src/chip.js
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/src/link.js
  packages/components/bolt-link/src/link.scss
  packages/components/bolt-trigger/src/trigger.js
  packages/components/bolt-trigger/src/trigger.scss
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
  packages/core/elements/bolt-action/index.js
  packages/core/styles/02-tools/tools-button-reset/_tools-button-reset.scss
  packages/core/styles/index.scss
Labels: enhancement

#1524 Accordion | Dev | Add custom accordion spacing option
  docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/45-accordion-trigger-and-content-spacing-variations.twig
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-accordion/accordion.schema.yml
  packages/components/bolt-accordion/src/AccordionItem/AccordionItemContent.js
  packages/components/bolt-accordion/src/AccordionItem/AccordionItemTrigger.js
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig
  packages/components/bolt-accordion/src/AccordionItem/index.js
Labels: improvement

#1513 Accordion | JS | Fix nested accordion bug
  docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-accordion/src/AccordionItem/index.js
  packages/components/bolt-accordion/src/accordion.js
Labels: bug

#1510 BDS-1761 inline form demos
  docs-site/src/pages/pattern-lab/_patterns/02-components/form/65-form-inline-inputs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/form/_form-full-inline.twig
Labels: improvement

#1152 Blockquote | Docs | Add Jest tests and documentation
  packages/components/bolt-blockquote/TESTING.md
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-renders-to-light-dom-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-renders-to-shadow-dom-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-renders-when-inside-a-form-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-with-no-quotes-renders-1-snap.png
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-blockquote/__tests__/blockquote.js
  packages/components/bolt-blockquote/__tests__/fixtures/author.jpg
  packages/components/bolt-blockquote/__tests__/fixtures/paypal.svg
  packages/components/bolt-blockquote/blockquote.schema.yml
Labels: Code Update Needed, improvement

#1534 Chore: Update Release Script / CLI Args Used When Auto Publishing
  .autorc
  auto-release.js
Labels: internal

#1532 Hotfix: Address Lazysizes Issue With Dynamically Injected, LazyLoaded Images
  docs-site/src/pages/pattern-lab/_patterns/02-components/card/__tests__/_personalized-card-example-data.js
  docs-site/src/pages/pattern-lab/_patterns/02-components/card/__tests__/_personalized-card-example.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/card/__tests__/personalized-card--client-rendered/personalized-card-example--client-rendered-tests.twig
  packages/components/bolt-image/__tests__/bolt-image.e2e.js
  packages/components/bolt-image/src/image.js
Labels: hotfix

#1533 Fix: Update Nightwatch Config for Local Testing
  packages/testing/testing-nightwatch/nightwatch.local.js
  packages/testing/testing-nightwatch/package.json
  yarn.lock
Labels: hotfix

#1530 feat(micro-journeys): prevent body content render on inactive steps and prevent inactive pathway render
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/_shadow-dom-demo.twig
  packages/components/bolt-animate/utils.js
  packages/micro-journeys/src/interactive-pathway.js
  packages/micro-journeys/src/interactive-step.js
Labels: Ready For Review

#1525 feat: update schema table layout to fit more onscreen
  docs-site/src/components/pattern-lab-hacks/pattern-lab-hacks.scss
  docs-site/src/components/pattern-lab-utils/docs.twig
  docs-site/src/components/pattern-lab-utils/schema-docs.twig
Labels: docs, improvement

#1529 Maintenance: Remove Site-Specific W/WO UI
  .boltrc.js
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/index.js
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/svg-animations/10-self-drawing-circle.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/00-with-without.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/01-with-without--no-shadow-dom.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/05-with-without-intersection-test.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/06-with-without-overlay-animation-test.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/overlay-demo.js
  packages/with-without/CHANGELOG.md
  packages/with-without/images-optimized/wwo-with-desktop.jpg
  packages/with-without/images-optimized/wwo-with-mobile.jpg
  packages/with-without/images-optimized/wwo-with-tablet.jpg
  packages/with-without/images-optimized/wwo-without-desktop.jpg
  packages/with-without/images-optimized/wwo-without-mobile.jpg
  packages/with-without/images-optimized/wwo-without-tablet.jpg
  packages/with-without/images-unoptimized/wwo-with-desktop.jpg
  packages/with-without/images-unoptimized/wwo-with-mobile.jpg
  packages/with-without/images-unoptimized/wwo-with-tablet.jpg
  packages/with-without/images-unoptimized/wwo-without-desktop.jpg
  packages/with-without/images-unoptimized/wwo-without-mobile.jpg
  packages/with-without/images-unoptimized/wwo-without-tablet.jpg
  packages/with-without/index.js
  packages/with-without/js/accordion.js
  packages/with-without/js/blurEdgeFocus.js
  packages/with-without/js/handleActiveRegionChange.js
  packages/with-without/js/handleResize.js
  packages/with-without/js/shadowDomPiercingHacks.js
  packages/with-without/js/with-without.js
  packages/with-without/package.json
  packages/with-without/svg/book.svg
  packages/with-without/svg/book.twig
  packages/with-without/svg/eye-contrast.svg
  packages/with-without/svg/eye-contrast.twig
  packages/with-without/svg/eye.svg
  packages/with-without/swiper.scss
  packages/with-without/with-without.scss
  packages/with-without/with-without.twig
  packages/with-without/wwo-self-drawing-circle/__demos__/self-drawing-circle.demo.twig
  packages/with-without/wwo-self-drawing-circle/self-drawing-circle.js
  packages/with-without/wwo-self-drawing-circle/self-drawing-circle.schema.yml
  packages/with-without/wwo-self-drawing-circle/self-drawing-circle.scss
  packages/with-without/wwo-self-drawing-circle/self-drawing-circle.twig
  packages/with-without/wwo-toggle/wwo-toggle.scss
  packages/with-without/wwo-toggle/wwo-toggle.twig
Labels: improvement

#1535 Bugfix/bds 1879 pass renderable content as list items
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/__tests__/-list-with-object-in-item.twig
  packages/components/bolt-list/__tests__/bolt-list.e2e.js
  packages/components/bolt-list/list.schema.yml
  packages/components/bolt-list/src/_list-item.twig
  packages/components/bolt-table/src/table.twig
  packages/components/bolt-table/table.schema.yml
Labels: improvement

#1528 feat(micro-journeys): refactor character, dialog, and 2-char layout t…
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/15-character-kitchen-sink.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/95-micro-journeys-intersection-observer.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/97-micro-journeys-single-step-with-two-character-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/_shadow-dom-demo.twig
  packages/components/bolt-animate/src/animate.js
  packages/components/bolt-animate/utils.js
  packages/micro-journeys/src/bolt-svg-animations/svg-animations.js
  packages/micro-journeys/src/bolt-svg-animations/svg-animations.scss
  packages/micro-journeys/src/character.js
  packages/micro-journeys/src/character.scss
  packages/micro-journeys/src/connection.js
  packages/micro-journeys/src/connection.scss
  packages/micro-journeys/src/interactive-pathway.js
  packages/micro-journeys/src/interactive-step.js
  packages/micro-journeys/src/one-character-layout.scss
  packages/micro-journeys/src/status-dialogue-bar.js
  packages/micro-journeys/src/status-dialogue-bar.scss
  packages/micro-journeys/src/two-character-layout.js
  packages/micro-journeys/src/two-character-layout.scss
  packages/micro-journeys/src/utils/equalize-relative-heights.js
  packages/micro-journeys/starters/step-two-character-lorem.html
  packages/micro-journeys/starters/two-characters-1.html
  packages/micro-journeys/starters/two-characters-2.html
  packages/micro-journeys/starters/two-characters-3.html
  packages/micro-journeys/starters/two-characters-4.html
  packages/micro-journeys/starters/two-characters-lorem.html
Labels: bug, improvement

#1526 BoltElement base class, Slotify, Polyfill Loader updates
  docs-site/src/components/bolt-select/package.json
  packages/analytics/autolink/__tests__/autolink.test.js
  packages/analytics/autotrack/index.js
  packages/analytics/autotrack/package.json
  packages/base-element/index.js
  packages/base-element/package.json
  packages/base-element/src/BoltActionElement.js
  packages/base-element/src/BoltElement.js
  packages/base-element/src/Slotify.js
  packages/base-element/src/lib/decorators.js
  packages/base-element/src/lib/style-injector.js
  packages/base-element/src/lib/utils.js
  packages/base-polyfills/index.js
  packages/base-polyfills/package.json
  packages/base-polyfills/platform/baseuri.js
  packages/base-polyfills/platform/custom-event.js
  packages/base-polyfills/platform/es6-misc.js
  packages/base-polyfills/platform/flag-parser.js
  packages/base-polyfills/platform/get-own-property-symbols.max.js
  packages/base-polyfills/platform/promise.js
  packages/base-polyfills/platform/remove-polyfill.js
  packages/base-polyfills/platform/symbol.js
  packages/base-polyfills/platform/unresolved.js
  packages/build-tools/create-webpack-config.js
  packages/build-tools/get-babel-config.js
  packages/build-tools/package.json
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-band/__tests__/band.js
  packages/components/bolt-band/index.js
  packages/components/bolt-band/package.json
  packages/components/bolt-band/src/band.js
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-button/package.json
  packages/components/bolt-button/src/button.js
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-7-snap.png
  packages/components/bolt-critical-css-vars/index.js
  packages/components/bolt-typeahead/typeahead.js
  packages/configs/babel-preset-bolt/index.js
  packages/core/decorators/convert-initial-tags.js
  packages/core/package.json
  packages/core/polyfills/custom-event-polyfill.js
  packages/core/polyfills/index.js
  packages/core/renderers/bolt-base.js
  packages/core/renderers/renderer-lit-html.js
  packages/core/utils/declarative-click-handler.js
  packages/core/utils/environment.js
  packages/core/utils/find-parent-tag.js
  packages/testing/testing-utils/__tests__/test-utils.test.js
  yarn.lock
Labels: improvement

#1531 Core | JS | Move 'optimizedResize' into Core
  packages/components/bolt-carousel/src/carousel.js
  packages/components/bolt-image/src/image.js
  packages/components/bolt-nav-indicator/nav-indicator.js
  packages/components/bolt-nav-priority/nav-priority.js
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-5-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-6-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-7-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-8-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-9-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-links-3-snap.png
  packages/components/bolt-navbar/__tests__/navbar.js
  packages/components/bolt-tabs/src/tabs-dropdown.scss
  packages/components/bolt-tabs/src/tabs.js
  packages/core/utils/debounce.js
  packages/core/utils/index.js
  packages/core/utils/optimized-resize.js
Labels: improvement

#1541 fix(micro-journeys): move link component to use slot-after for icon
  packages/micro-journeys/starters/cta-text-1.html
  packages/micro-journeys/starters/cta-text-2.html
  packages/micro-journeys/starters/cta-text-3.html
  packages/micro-journeys/starters/cta-text-4.html
  packages/micro-journeys/starters/cta-text-5.html
  packages/micro-journeys/starters/cta-text-lorem.html
  packages/micro-journeys/starters/one-character-1.html
  packages/micro-journeys/starters/one-character-lorem.html
  packages/micro-journeys/starters/step-one-character-lorem.html
  packages/micro-journeys/starters/step-one-character-starter.html
  packages/micro-journeys/starters/step-two-character-lorem.html
  packages/micro-journeys/starters/step-two-character-starter.html
  packages/micro-journeys/starters/two-characters-3.html
Labels: improvement

#1546 Fix/bolt character ie 11
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/15-character-kitchen-sink.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/_shadow-dom-demo.twig
  packages/micro-journeys/index.scss
  packages/micro-journeys/src/character.js
  packages/micro-journeys/src/character.scss
  packages/micro-journeys/src/connection.scss
  packages/micro-journeys/src/interactive-step.scss
  packages/micro-journeys/src/status-dialogue-bar.js
  packages/micro-journeys/src/status-dialogue-bar.scss
  packages/micro-journeys/src/two-character-layout.js
  packages/micro-journeys/src/two-character-layout.scss
Labels: enhancement

#1537 fix: Remove redundant button tag logic and dependency on deprecated schema
  docs-site/src/pages/pattern-lab/_patterns/02-components/button/45-button-type-variations.twig
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-button/src/button.twig
Labels: improvement

#1552 Feature/editor save events
  docs-site/.incache
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/editor/00-editor-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/editor/misc/-05-drupal-integration.twig
  packages/editor/src/index.js
  packages/editor/types/grapesjs/index.d.ts
Labels: enhancement

#1547 BDS 1909 JS schema parent child example
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-accordion/accordion-item.schema.js
  packages/components/bolt-accordion/accordion.schema.js
  packages/components/bolt-accordion/accordion.schema.yml
  packages/components/bolt-accordion/package.json
  packages/components/bolt-accordion/src/accordion.js
Labels: enhancement

#1543 Pattern Lab UI Fixes + Polish
  docs-site/config/config.yml
  packages/uikit-workshop/.nvmrc
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/html/index.html
  packages/uikit-workshop/src/sass/scss/01-abstracts/_mixins.scss
  packages/uikit-workshop/src/sass/scss/02-base/_body.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.js
  packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.scss
  packages/uikit-workshop/src/scripts/components/pl-search/pl-search.scss
  packages/uikit-workshop/src/scripts/lit-components/pl-header/pl-header.js
  packages/uikit-workshop/src/scripts/lit-components/pl-icon/pl-icon.scss
  packages/uikit-workshop/src/scripts/lit-components/pl-layout/pl-layout.js
  packages/uikit-workshop/src/scripts/lit-components/pl-layout/pl-layout.scss
  packages/uikit-workshop/src/scripts/lit-components/pl-tools-menu/pl-tools-menu.js
  packages/uikit-workshop/src/scripts/lit-components/pl-viewport-size/pl-viewport-size.js
  packages/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.js
  packages/uikit-workshop/src/scripts/localstorage.js
  packages/uikit-workshop/views-twig/partials/patternSection.twig
  packages/uikit-workshop/views/partials/patternSection.mustache
  yarn.lock
Labels: enhancement

#1512 Documentation for testing standards
  docs-site/src/pages/docs/45-development/70-testing-standards/00-index.md
  docs-site/src/pages/docs/45-development/70-testing-standards/10-js-testing-standards.md
  docs-site/src/pages/docs/45-development/70-testing-standards/20-manual-testing-standards.md
Labels: enhancement

#1555 Hotfix: Pattern Lab CSS Fix for IE 11
  packages/uikit-workshop/src/sass/scss/02-base/_body.scss
Labels: patch

#1558 Hotfix: define handleEditorSave at runtime
  packages/editor/src/index.js
Labels: bug

#1559 Bolt v2.11.3 Release
  packages/editor/src/index.js
  packages/testing/testing-utils/__tests__/test-utils.test.js
  packages/uikit-workshop/src/sass/scss/02-base/_body.scss
Labels: patch

#1540 Convert Image and Ratio to @bolt/element (LitElement)
  docs-site/src/pages/pattern-lab/_patterns/02-components/card/__tests__/_personalized-card-example-data.js
  packages/base-element/index.js
  packages/components/bolt-button/src/button.js
  packages/components/bolt-image/__tests__/bolt-image.e2e.js
  packages/components/bolt-image/package.json
  packages/components/bolt-image/src/_image-lazy-sizes.js
  packages/components/bolt-image/src/image.js
  packages/components/bolt-ratio/__tests__/ratio.js
  packages/components/bolt-ratio/package.json
  packages/components/bolt-ratio/src/ratio.js
  packages/core/package.json
Labels: improvement

#1560 Bugfix/editor component save regressions
  packages/editor/src/index.js
Labels: hotfix

#1561 hotfix: patch lit-element's constructable stylesheet rendering behavior
  packages/base-element/src/BoltElement.js
Labels: hotfix

#1557 Cleaning testing docs
  docs-site/src/pages/docs/45-development/10-bolt-testing-101.md
  docs-site/src/pages/docs/45-development/70-testing-standards/10-js-testing-standards.md
Labels: minor

#1553 Accordion | Test | Use Jest page selector instead of evaluate
  packages/components/bolt-accordion/__tests__/accordion.js
Labels: improvement

#1562 Tabs | SCSS | Fix resize bug in IE11
  packages/components/bolt-tabs/src/tabs-dropdown.scss
Labels: bug

#1563 New Theme Switcher Demo Component
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/components/theme-switcher/index.js
  docs-site/src/components/theme-switcher/package.json
  docs-site/src/components/theme-switcher/theme-switcher.js
  docs-site/src/components/theme-switcher/theme-switcher.scss
  package.json
Labels: enhancement

#1571 Typeahead: Accessibility Enhancements
  packages/components/bolt-typeahead/typeahead.autosuggest.js
  packages/components/bolt-typeahead/typeahead.status.js
Labels: enhancement

#1570 Core: Add Sassy List to @bolt/core
  packages/core/package.json
  packages/core/styles/index.scss
Labels: enhancement, quick-review

#1569 Core: Add New Text on Background/Secondary Background Options to Theme Options
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/build-tools/package.json
  packages/core/styles/01-settings/settings-themes/index.scss
Labels: enhancement, quick-review

#1568 Editor component bugfixes
  packages/editor/src/setup-bolt.js
Labels: bug

#1548 Figure | Twig | Add media content prop
  docs-site/src/pages/pattern-lab/_patterns/02-components/carousel/00-carousel-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/carousel/25-carousel-basic-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/figure/00-figure-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/figure/05-figure.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/figure/10-figure-media-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/40-modal-usage-image-and-caption.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/_product-t3-extra-videos.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/_product-t3.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t2.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t4.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/combos/-95-in-page-example.twig
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-figure/__tests__/figure.js
  packages/components/bolt-figure/figure.schema.yml
  packages/components/bolt-figure/src/figure.twig
  packages/global/styles/05-objects/objects-flag/src/flag.twig
Labels: deprecation, improvement

#1554 Modal | FE | Add auto-close demo
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/35-modal-usage-javascript.twig
Labels: enhancement

#1536 Blockquote | FE | Add language-specific quotation marks
  docs-site/src/pages/pattern-lab/_patterns/02-components/blockquote/35-blockquote-language-specific-quotation-marks.twig
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-with-lang-specific-quotes-de-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-with-lang-specific-quotes-en-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-with-lang-specific-quotes-fr-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-with-lang-specific-quotes-ja-1-snap.png
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-blockquote/__tests__/blockquote.js
  packages/components/bolt-blockquote/blockquote.schema.yml
  packages/components/bolt-blockquote/src/blockquote.js
  packages/components/bolt-blockquote/src/blockquote.scss
  packages/core/styles/01-settings/settings-quotes/_settings-quotes.scss
  packages/core/styles/index.scss
Labels: enhancement

#1572 Hotfix/vertical align bottom does not work with grid
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/global/styles/05-objects/objects-grid/_objects-grid.scss
Labels: bug

#1567 Upgrade Bolt from Preact v8.x to Preact v10
  packages/build-tools/create-webpack-config.js
  packages/components/bolt-block-list/__tests__/__snapshots__/block-list.js.snap
  packages/components/bolt-block-list/src/block-list.standalone.js
  packages/components/bolt-block-list/src/block-list.twig
  packages/components/bolt-code-snippet/package.json
  packages/components/bolt-code-snippet/src/code-snippet.standalone.js
  packages/components/bolt-typeahead/typeahead.autosuggest.js
  packages/configs/babel-preset-bolt/index.js
  packages/configs/eslint-config/ideal.js
  packages/core/package.json
  packages/core/renderers/preact-markup.js
  packages/core/renderers/renderer-preact.js
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/scripts/components/base-skate-preact-element.js
  packages/uikit-workshop/webpack.config.js
  yarn.lock
Labels: enhancement
