Repository boltdesignsystem/bolt, pull requests merged in 2019-12, with the labels that each got.

#1574 Update Eslint / Sass / Stylelint Dependencies
  packages/build-tools/create-webpack-config.js
  packages/build-tools/package.json
  packages/components/bolt-modal/focus-trap/focusable.js
  packages/configs/browserslist-config/package.json
  packages/configs/eslint-config/package.json
  packages/configs/stylelint-config/package.json
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: improvement, quick-review

#1580 Feat: update Twig Renderer to use Twig's new filter, map, and reduce functions
  docs-site/composer.lock
  package.json
  packages/core-php/composer.lock
  packages/drupal-twig-extensions/composer.lock
  packages/twig-renderer/composer.json
  packages/twig-renderer/composer.lock
  packages/twig-renderer/package.json
  yarn.lock
Labels: enhancement

#1556 Feature/bds 1911 icon cleanup
  packages/build-tools/tasks/icon-tasks.js
  packages/build-tools/utils/icon-generator.js
  packages/components/bolt-icon/registry.js
  packages/components/bolt-icon/src/icon.standalone.js
Labels: improvement

#1590 Pattern Lab UIKit Cross Browser Fixes
  packages/uikit-polyfills/index.js
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/scripts/components/modal-styleguide.js
  packages/uikit-workshop/src/scripts/patternlab-pattern.js
  packages/uikit-workshop/src/scripts/patternlab-viewer.modern.js
Labels: bug, improvement, quick-review

#1589 Add Lighthouse CI Performance Monitoring / Github Integration
  .travis.yml
  lighthouserc.json
Labels: enhancement, quick-review

#1593 feat: convert Trigger schema to JS
  packages/components/bolt-trigger/__tests__/trigger.js
  packages/components/bolt-trigger/package.json
  packages/components/bolt-trigger/src/trigger.js
  packages/components/bolt-trigger/trigger.schema.js
  packages/components/bolt-trigger/trigger.schema.yml
Labels: improvement

#1594 test: Replace unnecessary e2e test with Jest test for renderable items
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/__tests__/-list-with-object-in-item.twig
  packages/components/bolt-list/__tests__/bolt-list.e2e.js
  packages/components/bolt-list/__tests__/list.js
Labels: improvement

#1598 fix(editor): restore pathways editable traits; fix opacity: 0
  packages/editor/src/setup-bolt.js
  packages/micro-journeys/index.scss
  packages/micro-journeys/src/interactive-pathways.js
Labels: bug

#1596 feat(editor): add ability to remove icon from status-dialogue-bar
  packages/micro-journeys/src/status-dialogue-bar.js
  packages/micro-journeys/src/status-dialogue-bar.schema.js
Labels: new feature

#1604 Fix: unordered list's inconsistent stack spacing
  packages/components/bolt-ul/src/ul.scss
Labels: bug

#1583 Fix: Device Viewer CSS Fix
  packages/components/bolt-device-viewer/src/device-viewer.scss
Labels: patch

#1573 Bolt band in modal fix
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-bolt-modal-rendered-by-twig-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-bolt-modal-rendered-by-twig-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-bolt-modal-slots-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-bolt-modal-slots-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-default-bolt-modal-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-default-bolt-modal-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-band-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-band-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-w-o-shadow-dom-renders-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-with-band-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-with-band-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-with-shadow-dom-renders-2-snap.png
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-modal/__tests__/fixtures/1200x2500.jpg
  packages/components/bolt-modal/__tests__/modal.js
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-align-start-3-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-web-component-usage-shadow-dom-2-snap.png
Labels: bug

#1597 fix(editor): remove false error on editor navigation away from saved …
  packages/editor/src/editor.js
  packages/editor/src/index.js
Labels: bug

#1605 Hotfix/editor remove valign option from bolt link
  packages/editor/src/setup-bolt.js
Labels: bug

#1607 Fix Navbar Vertical Alignment + Add Java / SQL Support to Code Snippets
  packages/components/bolt-code-snippet/src/code-snippet.standalone.js
  packages/components/bolt-navbar/src/navbar.scss
Labels: minor, quick-review

#1608 Icon Refactor: SVG Updates
  packages/components/bolt-icons/src/svgs/product/industry/life-sciences.svg
  packages/components/bolt-icons/src/svgs/product/product/crm/customer-decision-hub.svg
  packages/components/bolt-icons/src/svgs/product/product/crm/customer-service.svg
  packages/components/bolt-icons/src/svgs/product/product/crm/field-service-gray.svg
  packages/components/bolt-icons/src/svgs/product/product/crm/field-service.svg
  packages/components/bolt-icons/src/svgs/product/product/crm/sales-automation.svg
  packages/components/bolt-icons/src/svgs/utility/add-solid.svg
  packages/components/bolt-icons/src/svgs/utility/bolt-logo-colored.svg
  packages/components/bolt-icons/src/svgs/utility/check-solid.svg
  packages/components/bolt-icons/src/svgs/utility/close-solid.svg
  packages/components/bolt-icons/src/svgs/utility/exit-full-screen.svg
  packages/components/bolt-icons/src/svgs/utility/external-link.svg
  packages/components/bolt-icons/src/svgs/utility/full-screen.svg
  packages/components/bolt-icons/src/svgs/utility/info-solid.svg
  packages/components/bolt-icons/src/svgs/utility/map-pin-solid.svg
  packages/components/bolt-icons/src/svgs/utility/minus-solid.svg
  packages/components/bolt-icons/src/svgs/utility/star-solid.svg
Labels: Ready For Review, improvement, quick-review

#1618 Add Optional Chaining Support to Babel
  packages/configs/babel-preset-bolt/index.js
  packages/configs/babel-preset-bolt/package.json
Labels: minor, quick-review

#1619 Add Collaboration Center-related SVG Icons
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/icons/collaboration.js
  packages/components/bolt-icons/src/icons/discussions.js
  packages/components/bolt-icons/src/icons/file-small.js
  packages/components/bolt-icons/src/icons/heart.js
  packages/components/bolt-icons/src/icons/ideas.js
  packages/components/bolt-icons/src/icons/questions.js
  packages/components/bolt-icons/src/icons/reply.js
  packages/components/bolt-icons/src/index.js
  packages/components/bolt-icons/src/svgs/brand/collaboration.svg
  packages/components/bolt-icons/src/svgs/brand/discussions.svg
  packages/components/bolt-icons/src/svgs/brand/ideas.svg
  packages/components/bolt-icons/src/svgs/brand/questions.svg
  packages/components/bolt-icons/src/svgs/utility/file-small.svg
  packages/components/bolt-icons/src/svgs/utility/heart.svg
  packages/components/bolt-icons/src/svgs/utility/reply.svg
Labels: patch

#1599 Fix/wwwd 4357 pathway ready event only when ready
  jest.config.js
  packages/micro-journeys/__tests__/microjourneys.js
  packages/micro-journeys/src/interactive-pathway.js
Labels: bug

#1581 Remove slot-based CSS selector so status bar color works in IE
  packages/micro-journeys/src/status-dialogue-bar.scss
Labels: bug

#1346 Keep Drupal Lab Dependencies in Sync + Deploy As Static Site
  .travis.yml
  example-integrations/drupal-lab/composer.json
  example-integrations/drupal-lab/composer.lock
  example-integrations/drupal-lab/config/sync/block.block.bartik_admin.yml
  example-integrations/drupal-lab/config/sync/block.block.bartik_tools.yml
  example-integrations/drupal-lab/config/sync/block.block.bolt_starter_admin.yml
  example-integrations/drupal-lab/config/sync/block.block.bolt_starter_tools.yml
  example-integrations/drupal-lab/config/sync/block.block.stark_admin.yml
  example-integrations/drupal-lab/config/sync/block.block.stark_tools.yml
  example-integrations/drupal-lab/config/sync/core.extension.yml
  example-integrations/drupal-lab/package.json
  example-integrations/drupal-lab/web/sites/default/settings.local.php
  example-integrations/drupal-lab/web/themes/bolt-starter/yarn.lock
  jest.config.js
  now.json
  packages/build-tools/tasks/task-collections.js
  packages/build-tools/tasks/webpack-tasks.js
  packages/generators/yeoman-create-component/generators/component/__tests__/component-generator.js
  packages/generators/yeoman-create-component/generators/component/add-bolt-package.js
  packages/generators/yeoman-create-component/generators/component/index.js
  packages/generators/yeoman-create-component/generators/component/templates/component.scss
  packages/generators/yeoman-create-component/generators/component/update-boltrc.js
  packages/generators/yeoman-create-component/package.json
  packages/servers/default-server/index.js
  packages/testing/testing-jest/jest-global-teardown.js
  yarn.lock
Labels: enhancement

#1253 Form | Docs | Testing and Documentation for form component
  packages/components/bolt-form/TESTING.md
  packages/components/bolt-form/__tests__/__snapshots__/form.js.snap
  packages/components/bolt-form/__tests__/form.js
Labels: improvement

#1585 ES Modules: Internal Component Updates
  docs-site/src/components/schema-form/schema-form.js
  packages/base-element/src/BoltActionElement.js
  packages/components/bolt-blockquote/src/blockquote.js
  packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
  packages/components/bolt-device-viewer/src/device-viewer.standalone.js
  packages/components/bolt-dropdown/dropdown.js
  packages/components/bolt-figure/src/figure.js
  packages/components/bolt-icon/src/icon.standalone.js
  packages/components/bolt-image/src/image.js
  packages/components/bolt-modal/src/modal.js
  packages/components/bolt-nav-priority/nav-priority.js
  packages/components/bolt-navlink/navlink.js
  packages/components/bolt-placeholder/placeholder.standalone.js
  packages/components/bolt-ratio/src/ratio.js
  packages/components/bolt-stack/src/stack.js
  packages/components/bolt-text/src/text.js
  packages/components/bolt-video/src/video.standalone.js
  packages/micro-journeys/src/interactive-pathway.js
  packages/micro-journeys/src/interactive-pathways.js
  packages/micro-journeys/src/two-character-layout.js
Labels: enhancement, quick-review

#1621 Speed Up Monorepo Git Commit Hooks By ~90s
  package.json
  yarn.lock
Labels: improvement

#1577 Fix Micro Journey-related Issues with the Two-Character Layout
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/editor/25-editor-with-two-character-layout.twig
  packages/micro-journeys/src/character.scss
  packages/micro-journeys/src/connection.js
  packages/micro-journeys/src/connection.scss
  packages/micro-journeys/src/interactive-step.js
  packages/micro-journeys/src/interactive-step.scss
  packages/micro-journeys/src/two-character-layout.js
  packages/micro-journeys/src/utils/equalize-relative-heights.js
  packages/micro-journeys/starters/step-two-character-starter.html
Labels: hotfix

#1623 Add New Academy-related Icons
  .gitignore
  packages/build-tools/utils/icon-generator.js
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/icons/collaboration.js
  packages/components/bolt-icons/src/icons/discussions.js
  packages/components/bolt-icons/src/icons/file-small.js
  packages/components/bolt-icons/src/icons/heart.js
  packages/components/bolt-icons/src/icons/ideas.js
  packages/components/bolt-icons/src/icons/questions.js
  packages/components/bolt-icons/src/icons/reply.js
  packages/components/bolt-icons/src/index.js
  packages/components/bolt-icons/src/svgs/brand/brand-atom.svg
  packages/components/bolt-icons/src/svgs/brand/brand-meteor.svg
  packages/components/bolt-icons/src/svgs/brand/brand-molecule.svg
  packages/components/bolt-icons/src/svgs/brand/brand-orbit.svg
  packages/components/bolt-icons/src/svgs/brand/brand-rocket.svg
  packages/components/bolt-icons/src/svgs/brand/brand-satelite.svg
  packages/components/bolt-icons/src/svgs/brand/brand-triangle.svg
  packages/components/bolt-icons/src/svgs/brand/thumbs-up-outline.svg
  packages/components/bolt-icons/src/svgs/brand/time-outline.svg
  packages/components/bolt-icons/src/svgs/brand/world-outline.svg
Labels: improvement

#1622 Academy-required Updates to Core, Utility Classes, etc
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-band/src/band.twig
  packages/components/bolt-headline/headline.schema.yml
  packages/components/bolt-headline/src/_tools.headlines.scss
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-headline/src/headline.scss
  packages/components/bolt-site/site.scss
  packages/core/styles/01-settings/settings-breakpoints/_settings-breakpoints.scss
  packages/core/styles/01-settings/settings-font-weight/_settings-font-weight.scss
  packages/core/styles/01-settings/settings-spacing/_settings-spacing.scss
  packages/global/styles/03-generic/_generic-font-stacks.scss
  packages/global/styles/07-utilities/_utilities-flex.scss
  packages/global/styles/07-utilities/_utilities-position.scss
  packages/global/styles/07-utilities/_utilities-spacing.scss
  packages/global/styles/07-utilities/_utilities-widths.scss
  packages/global/styles/index.scss
Labels: enhancement, quick-review

#1441 Export font information for font loader js
  docs-site/.boltrc.js
  packages/build-tools/create-webpack-config.js
  packages/components/bolt-critical-fonts/src/critical-fonts.js
  packages/components/bolt-critical-fonts/src/font-stacks.bolt.json
Labels: enhancement

#1626 Automatically Format Package.json Files
  package.json
  yarn.lock
Labels: improvement

#1588 ES Modules: Upgrade Link to BoltElement
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-link/src/link.js
Labels: improvement

#1586 ES Modules: Bolt Core / BoltElement Updates
  packages/base-element/src/Slotify.js
  packages/base-element/src/lib/decorators.js
  packages/base-element/src/lib/utils.js
  packages/core/decorators/convert-initial-tags.js
  packages/core/package.json
  packages/core/renderers/bolt-base.js
  packages/core/renderers/renderer-lit-html.js
  packages/core/renderers/renderer-preact.js
  packages/core/renderers/wc-context.core.js
  packages/core/renderers/wc-context.js
  packages/core/renderers/with-events.js
  packages/core/utils/environment.js
  packages/core/utils/find-parent-tag.js
  packages/core/utils/index.js
Labels: enhancement

#1587 ES Modules: Simplified "Polyfill Loader"
  packages/base-polyfills/index.js
  packages/base-polyfills/modern.js
  packages/components/bolt-button/index.js
  packages/core/polyfills/index.js
Labels: enhancement

#1638 fix: eslint errors not fixable with --fix
  auto-release.js
Labels: patch

#1641 hotfix: Remove cache-loader from webpack fonts rule
  packages/build-tools/create-webpack-config.js
Labels: hotfix

#1646 Feature: Add bolt-shadow-toggle component
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/components/shadow-toggle/index.js
  docs-site/src/components/shadow-toggle/package.json
  docs-site/src/components/shadow-toggle/shadow-toggle.js
  docs-site/src/components/shadow-toggle/shadow-toggle.scss
  docs-site/src/components/shadow-toggle/shadow-toggle.twig
  docs-site/src/templates/_site-footer.twig
  package.json
  packages/base-element/index.js
  packages/base-element/src/lib/utils.js
Labels: enhancement
