Repository boltdesignsystem/bolt, pull requests merged in 2019-08, with the labels that each got.

#1282 Speed Up Jest Tests By ~70% (4 minutes faster!)
  packages/analytics/autolink/__tests__/autolink.test.js
  packages/api/index.test.js
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-band/__tests__/band.js
  packages/components/bolt-blockquote/__tests__/blockquote.js
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-carousel/__tests__/carousel.js
  packages/components/bolt-icons/__tests__/icons.js
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-logo/__tests__/logo.js
  packages/components/bolt-modal/__tests__/modal.js
  packages/components/bolt-navbar/__tests__/navbar.js
  packages/components/bolt-ratio/__tests__/ratio.js
  packages/components/bolt-text/__tests__/text.js
  packages/generators/yeoman-create-component/generators/component/templates/component.test.js
  packages/servers/testing-server/index.js
  packages/twig-renderer/twig-renderer.js
Labels: Ready For Review

#1290 Feature: Improve Navbar Spacing
  docs-site/src/components/docs-search/docs-search.scss
  docs-site/src/components/version-selector/version-selector.twig
  packages/components/bolt-navbar/src/navbar.scss
Labels: Ready To Merge

#1276 Button/Link | Bug | Double focus styles on button and link
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/src/button.scss
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/src/link.scss
Labels: Code Update Needed

#1267 docs: add quick writeup on configuring language-specific builds in Bolt
  docs-site/src/pages/docs/45-development/30-build-tools/40-internationalization.md
Labels: Ready For Review

#1328 fix: update nightwatch config to fix chrome driver issues
  packages/testing/testing-nightwatch/nightwatch.js
  packages/testing/testing-nightwatch/nightwatch.local.js
Labels: Ready To Merge, maintenance

#1327 Modal | JS | Add `toggle` method
  packages/components/bolt-modal/src/modal.js
Labels: Ready To Merge, enhancement

#1306 Fix: correct close button color in IE11
  packages/components/bolt-modal/src/modal.js
  packages/components/bolt-modal/src/modal.scss
Labels: Ready To Merge, bug

#1283 Docs | Manually Cutting a Bolt Release
  docs-site/src/assets/images/docs/release_github-token.png
  docs-site/src/assets/images/docs/release_now-token.png
  docs-site/src/pages/docs/45-workflow-and-process/20-cutting-a-release.md
Labels: Ready For Review, docs

#1322 Navlink | Bug | Prevent JS errors in Navlink When Clicking on "Non Scroll-to" Links
  packages/components/bolt-navlink/navlink.js
Labels: Ready To Merge, bug

#1321 Analytics | Bug | Fix Autotrack and Autolink JS Errors When GA Config / GA Script Missing
  packages/analytics/autolink/index.js
  packages/analytics/autotrack/index.js
Labels: Ready For Review, Ready To Merge, bug

#1329 Bugfix/wwwd 1347 duplicate id attributes
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-link/src/link.twig
Labels: Ready To Merge

#1358 Fix: update Button testing instructions to sync up with the current docs
  packages/components/bolt-button/TESTING.md
Labels: Ready To Merge

#1319 Modal | FE | Improve doc pages to explain each prop option and minor CSS fixes
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/00-modal-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/05-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/10-modal-width-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/15-modal-spacing-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/20-modal-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/25-modal-scroll-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/30-modal-trigger-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/35-modal-usage-javascript.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/40-modal-usage-image-and-caption.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/50-modal-usage-content.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/999-modal-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/custom-events/_modal-usage-custom-events.twig
  packages/components/bolt-modal/README.md
  packages/components/bolt-modal/TESTING.md
  packages/components/bolt-modal/modal.schema.yml
  packages/components/bolt-modal/package.json
  packages/components/bolt-modal/src/modal.scss
Labels: Ready To Merge
