Repository boltdesignsystem/bolt, pull requests merged in 2019-01, with the labels that each got.

#990 Set up Docker deployment and Express Server
  .dockerignore
  .travis.yml
  Dockerfile
  deploys/Dockerfile
  deploys/now.json
  docs-site/.boltrc.js
  docs-site/src/components/handle-iframe-height/index.js
  docs-site/src/components/pattern-lab-utils/docs.twig
  docs-site/src/components/schema-form/component-explorer.js
  docs-site/src/components/schema-form/component-explorer.scss
  docs-site/src/components/schema-form/grid-layout.js
  docs-site/src/components/schema-form/index.js
  docs-site/src/components/schema-form/package.json
  docs-site/src/components/schema-form/schema-form.js
  docs-site/src/components/schema-form/utils.js
  docs-site/src/index.js
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/02-components/button/-00-button-live-demo@inprogress.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/button/00-button-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/navbar/00-navbar-docs.twig
  now.json
  package.json
  packages/build-tools/api/__snapshots__/index.test.js.snap
  packages/build-tools/api/index.js
  packages/build-tools/api/index.test.js
  packages/build-tools/api/twig-renderer.js
  packages/build-tools/create-webpack-config.js
  packages/build-tools/tasks/task-collections.js
  packages/build-tools/tasks/webpack-tasks.js
  packages/build-tools/utils/config-store.js
  packages/components/bolt-button/button.schema.yml
  packages/components/bolt-navbar/navbar.schema.yml
  packages/core/actions.js
  packages/core/localstorage.js
  packages/core/package.json
  packages/core/reducers.js
  packages/core/renderers/bolt-base.js
  packages/core/store.js
  packages/twig-renderer/twig-renderer.js
  scripts/deploy.js
  scripts/docker-build.sh
  scripts/docker-run.sh
  scripts/docker.sh
  scripts/package.json
  serve.json
  server.js
  yarn.lock
Labels: enhancement, refactor

#1042 fix: partially revert recent update to Github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#1034 Speed Up Component Explorer Rendering Times
  packages/build-tools/api/index.js
  packages/twig-renderer/twig-renderer.js
Labels: review needed

#1061 Hotfix: Band / Height Issue In IE 11 & Firefox
  docs-site/src/components/site-layout/site-layout.scss
  docs-site/src/templates/_site-head.twig
  nightwatch.js
Labels: bug
