Repository boltdesignsystem/bolt, pull requests merged in 2019-02, with the labels that each got.

#1009 WIP BDS-789 card adaptor
  docs-site/src/pages/pattern-lab/_patterns/02-components/card/90-deprecated-cards.twig
  packages/components/bolt-card/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-card/__tests__/card.js
  packages/components/bolt-card/__tests__/fixtures/landscape-16x9-mountains.jpg
  packages/components/bolt-card/src/_new-card.twig
  packages/components/bolt-card/src/_old-card-adapter.twig
  packages/components/bolt-card/src/card-w-teaser-list.twig
  packages/components/bolt-card/src/card-w-teaser.twig
  packages/components/bolt-card/src/card.scss
  packages/components/bolt-card/src/card.twig
Labels: WIP, review needed

#1064 Fix: flag object's icon figure not rendering
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t2.twig
  packages/components/bolt-figure/src/figure.twig
  packages/global/styles/05-objects/objects-flag/_objects-flag.scss
  packages/global/styles/05-objects/objects-flag/src/flag.twig
Labels: review needed

#1056 Custom solution: Careers homepage background video
  docs-site/package.json
  docs-site/src/pages/pattern-lab/_patterns/04-pages/50-d8-careers/00-careers-homepage.twig
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/scripts/components/pl-layout/pl-layout.js
  yarn.lock
Labels: WIP
