Repository boltdesignsystem/bolt, pull requests merged in 2019-10, with the labels that each got.

#1287 Fix: Update Table Component's HTML Parser To Not Break When Encountering HTML Comments
  packages/components/bolt-table/__tests__/__image_snapshots__/table-js-bolt-table-component-twig-rendered-table-with-html-comments-3-snap.png
  packages/components/bolt-table/__tests__/__image_snapshots__/table-js-bolt-table-component-web-component-rendered-table-with-html-comments-2-snap.png
  packages/components/bolt-table/__tests__/__snapshots__/table.js.snap
  packages/components/bolt-table/__tests__/table.js
  packages/components/bolt-table/src/table.js
Labels: Ready To Merge, bug

#1315 Make Schema Data Displayed in Pattern Lab Dynamic(ish)
  docs-site/src/components/pattern-lab-utils/docs.twig
  packages/build-tools/tasks/pattern-lab-tasks.js
  packages/core-php/src/TwigExtensions/BoltCore.php
  packages/core-php/src/TwigFunctions.php
  packages/core-php/src/Utils.php
Labels: improvement

#1338 List | FE | Spacing consistency and code clean up
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/00-list-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/10-list-item-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/20-list-spacing-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/25-list-separator-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/30-list-inset-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/999-list-with-web-component.twig
  packages/components/bolt-list/TESTING.md
  packages/components/bolt-list/src/_list-item.scss
  packages/components/bolt-list/src/list.scss
Labels: enhancement

#1449 Accordion | Test | Add e2e accordion test for inactive prop
  docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/-45-accordion-no-shadow.twig
  packages/components/bolt-accordion/__tests__/accordion.e2e.js
Labels: enhancement

#1451 Tabs | Test | Add Jest and e2e tests
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/-40-tabs-no-shadow.twig
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-align-center-1-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-align-end-1-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-align-start-1-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-inset-auto-1-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-inset-off-1-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-inset-on-1-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-web-component-usage-light-dom-1-snap.png
  packages/components/bolt-tabs/__tests__/__image_snapshots__/tabs-js-bolt-tabs-web-component-usage-shadow-dom-1-snap.png
  packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
  packages/components/bolt-tabs/__tests__/tabs.e2e.js
  packages/components/bolt-tabs/__tests__/tabs.js
  packages/components/bolt-tabs/src/TabPanel/index.js
  packages/components/bolt-tabs/src/tabs.js
Labels: improvement

#1444 feat(core-styles): add documentation to bolt-theme
  packages/core/styles/02-tools/tools-themes/_tools.themes.scss
Labels: Ready To Merge, docs

#1461 Feat/dark theme context for svg animations
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/svg-animations/05-svg-animations.twig
  packages/micro-journeys/src/bolt-svg-animations/svg-animations.js
  packages/micro-journeys/src/bolt-svg-animations/svg-animations.schema.js
  packages/micro-journeys/src/bolt-svg-animations/svg/automation.js
  packages/micro-journeys/src/bolt-svg-animations/svg/connectionBand.js
  packages/micro-journeys/src/bolt-svg-animations/svg/orbit.js
  packages/micro-journeys/src/bolt-svg-animations/svg/radar.js
  packages/micro-journeys/src/bolt-svg-animations/svg/tripleConnectionBand.js
Labels: Ready To Merge, enhancement

#1440 Fix triple band SVG animation
  packages/micro-journeys/src/bolt-svg-animations/svg/tripleConnectionBand.js
Labels: bug

#1467 Fix/context js error on svg animations
  packages/core/utils/context/with-context.js
  packages/micro-journeys/src/bolt-svg-animations/svg-animations.schema.js
  packages/micro-journeys/src/interactive-pathways.js
Labels: bug

#1468 Self-drawing Circle and Ratio Fix + Update Dependencies
  docs-site/composer.lock
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/svg-animations/10-self-drawing-circle.twig
  packages/components/bolt-ratio/index.js
  packages/components/bolt-ratio/src/ratio.js
  packages/core/package.json
  packages/drupal-twig-extensions/composer.lock
  packages/twig-renderer/composer.lock
  packages/uikit-workshop/package.json
  packages/uikit-workshop/webpack.config.js
  packages/with-without/wwo-self-drawing-circle/__demos__/self-drawing-circle.demo.twig
  packages/with-without/wwo-self-drawing-circle/self-drawing-circle.js
  yarn.lock
Labels: bug, enhancement

#1470 feat: speed up default exit animation to create a smoother experience
  packages/components/bolt-animate/animate.schema.js
Labels: enhancement

#1464 chore(micro-journeys): remove destructured assignment to prevent trut…
  packages/micro-journeys/src/character.js
  packages/micro-journeys/src/character.schema.js
  packages/micro-journeys/src/connection.js
  packages/micro-journeys/src/interactive-pathways.js
  packages/micro-journeys/src/interactive-pathways.schema.js
  packages/micro-journeys/src/interactive-step.js
  packages/micro-journeys/src/status-dialogue-bar.js
Labels: improvement

#1408 Docs: Tips & Tricks on Building Web Components
  docs-site/src/pages/docs/50-guides/50-tips-on-building-web-components.md
Labels: docs

#1469 fix: z-index clash between dropdown menu and status bars
  packages/micro-journeys/src/interactive-pathways.scss
Labels: Ready To Merge, bug

#1412 Feature/dropdown close on select
  packages/micro-journeys/src/interactive-pathways.js
Labels: enhancement

#1429 Tabs | Docs | Tabbed Band demo
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/40-tabs-use-case-tabbed-band.twig
Labels: improvement

#1472 Upgrade withContext Solution
  packages/core/package.json
  packages/core/polyfills/index.js
  packages/core/renderers/renderer-lit-html.js
  packages/micro-journeys/package.json
  packages/micro-journeys/src/bolt-svg-animations/svg-animations.js
  packages/micro-journeys/src/connection.js
  packages/micro-journeys/src/interactive-pathway.js
  packages/micro-journeys/src/interactive-pathways.js
  packages/micro-journeys/src/interactive-step.js
  yarn.lock
Labels: hotfix, improvement

#1473 Micro Journey RWD / Layout Fixes
  packages/micro-journeys/src/interactive-step.scss
  packages/micro-journeys/src/nav-shared.scss
  packages/micro-journeys/src/one-character-layout.scss
  packages/micro-journeys/src/status-dialogue-bar.scss
  packages/micro-journeys/src/two-character-layout.scss
Labels: bug

#1471 Hotfix/with without fixes
  docs-site/src/index.js
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/00-with-without.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/01-with-without--no-shadow-dom.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/05-with-without-intersection-test.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/06-with-without-overlay-animation-test.twig
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/with-without/overlay-demo.js
  packages/components/bolt-animate/utils.js
  packages/with-without/js/accordion.js
  packages/with-without/js/blurEdgeFocus.js
  packages/with-without/js/handleActiveRegionChange.js
  packages/with-without/js/handleResize.js
  packages/with-without/js/with-without.js
  packages/with-without/with-without.scss
  packages/with-without/with-without.twig
  packages/with-without/wwo-self-drawing-circle/__demos__/self-drawing-circle.demo.twig
  packages/with-without/wwo-self-drawing-circle/self-drawing-circle.js
  packages/with-without/wwo-self-drawing-circle/self-drawing-circle.scss
  packages/with-without/wwo-toggle/wwo-toggle.scss
Labels: bug

#1482 Feat/micro journey little fixes
  packages/components/bolt-animate/animate.schema.js
  packages/editor/src/index.js
  packages/editor/src/setup-bolt.js
  packages/micro-journeys/src/interactive-pathways.js
  packages/micro-journeys/src/interactive-pathways.schema.js
Labels: bug

#1480 fix(editor): use package name for import
  packages/editor/src/setup-bolt.js
Labels: bug, enhancement

#1487 Hotfix: Tooltip Refactor + Updates
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/05-tooltip.twig
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/index.js
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-tooltip/src/tooltip.twig
Labels: bug

#1479 Component Generator | Update | Use latest component conventions
  packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js.snap
  packages/generators/yeoman-create-component/generators/component/templates/component.html.twig
  packages/generators/yeoman-create-component/generators/component/templates/component.js
Labels: enhancement

#1388 Fix: Backport Upstream Pattern Lab UIKit Bug Fixes
  docs-site/config/config.yml
  packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.js
  packages/uikit-workshop/src/scripts/components/pl-viewport/pl-viewport.js
Labels: Ready For Review, docs

#1496 Fix for Video Controls Bar Bug
  .npmrc
  docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
  package.json
  packages/components/bolt-accordion/__tests__/__image_snapshots__/accordion-js-bolt-accordion-component-default-bolt-accordion-w-o-shadow-dom-renders-3-snap.png
  packages/components/bolt-accordion/__tests__/__image_snapshots__/accordion-js-bolt-accordion-component-default-bolt-accordion-with-shadow-dom-renders-3-snap.png
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig
  packages/components/bolt-accordion/src/AccordionItem/index.js
  packages/components/bolt-accordion/src/accordion.js
  packages/components/bolt-carousel/src/_carousel.pagination.scss
  packages/components/bolt-tabs/src/tabs.js
  packages/components/bolt-video/src/video.standalone.js
Labels: bug

#1497 Feature/tabs adaptive menu
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/-40-tabs-no-shadow.twig
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-tabs/__tests__/tabs.e2e.js
  packages/components/bolt-tabs/src/tabs-dropdown.scss
  packages/components/bolt-tabs/src/tabs.js
  packages/components/bolt-tabs/src/tabs.scss
  packages/core/styles/01-settings/settings-themes/index.scss
Labels: bug

#1393 Hotfix: correct spacing for non-link navbar title
  docs-site/composer.lock
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-6-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-7-snap.png
  packages/components/bolt-navbar/__tests__/__snapshots__/navbar.js.snap
  packages/components/bolt-navbar/src/_navbar-title.twig
  packages/components/bolt-navbar/src/navbar.scss
  packages/components/bolt-sticky/__tests__/__snapshots__/sticky.js.snap
  packages/core-php/composer.lock
  packages/twig-renderer/composer.lock
Labels: bug

#1503 Fix: Update Editor Template
  packages/editor/src/editor.twig
Labels: bug

#1457 Core | JS | Fix tabs, accordion, carousel nesting bugs
  docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/-45-accordion-no-shadow.twig
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig
  packages/components/bolt-accordion/src/AccordionItem/index.js
  packages/components/bolt-accordion/src/accordion.js
  packages/components/bolt-carousel/src/carousel.js
  packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
  packages/components/bolt-tabs/src/TabPanel/tab-panel.twig
  packages/components/bolt-tabs/src/tabs-dropdown.scss
  packages/components/bolt-tabs/src/tabs.js
  packages/components/bolt-tabs/src/tabs.scss
  packages/components/bolt-tabs/src/tabs.twig
  packages/core/elements/index.js
  packages/core/elements/ssr-keep/README.md
  packages/core/elements/ssr-keep/index.js
  packages/core/renderers/bolt-base.js
Labels: bug

#1500 Video | QA | Add Brightcove player demo page
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/tests/-test-brightcove-video-player.twig
Labels: docs

#1289 Feature: Add Support for Displaying Advanced (Hidden) Schema Props
  docs-site/src/components/pattern-lab-utils/schema-docs.twig
Labels: enhancement

#1505 Fix: Update Auto-release Script
  .travis.yml
  auto-release.js
  docs-site/.incache
  package.json
Labels: skip-release

#1506 Tabs | JS | Close dropdown menu after selecting tab item
  packages/components/bolt-tabs/src/tabs.js
Labels: hotfix

#1332 Chip | FE | Refactor and add size prop
  docs-site/composer.lock
  docs-site/src/pages/pattern-lab/_patterns/02-components/chip/05-chip.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/chip/10-chip-url-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/chip/10-chip-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/chip/15-chip-size-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/chip/20-chip-icon-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/chip/999-chip-with-web-component.twig
  packages/components/bolt-chip-list/__tests__/__snapshots__/chip-list.js.snap
  packages/components/bolt-chip/README.md
  packages/components/bolt-chip/TESTING.md
  packages/components/bolt-chip/__tests__/__snapshots__/chip.js.snap
  packages/components/bolt-chip/__tests__/chip.js
  packages/components/bolt-chip/chip.schema.yml
  packages/components/bolt-chip/package.json
  packages/components/bolt-chip/src/_chip-macros.twig
  packages/components/bolt-chip/src/chip.js
  packages/components/bolt-chip/src/chip.scss
  packages/components/bolt-chip/src/chip.twig
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-5-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-6-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-5-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-5-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-6-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-5-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-8-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-9-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-a-linked-title-1-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-a-linked-title-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-a-linked-title-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-a-title-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-a-title-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-links-3-snap.png
  yarn.lock
Labels: enhancement

#1331 Chore: Refresh Video Examples Used in Pattern Lab Demos
  docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/figure/10-figure-media-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/45-modal-usage-video.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/custom-events/_modal-usage-custom-events.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/05-video.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/10-video-hide-meta-title-and-duration.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/15-video-hide-meta-title-only.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/20-video-hide-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/25-video-with-external-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/35-video-with-inline-script-and-external-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/50-video-with-email-share.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/55-video-with-custom-share-text.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/65-video-with-external-title.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/_video-with-inline-script-and-external-controls-as-background.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/plugins/default-plugins.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/plugins/disabled-plugins.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/plugins/enabled-plugins.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/plugins/external-plugins-script.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/tests/-test-brightcove-video-player.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/tests/-test-video-injection.twig
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-figure/__tests__/figure.data.js
  packages/components/bolt-video/__tests__/__snapshots__/video.js.snap
  packages/components/bolt-video/__tests__/video.js
Labels: docs

#1509 Image | JS | Fix images in tabs appearing fuzzy
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
  packages/components/bolt-image/src/image.js
Labels: hotfix

#1508 Bolt v2.9.1 Release
  .travis.yml
  auto-release.js
  docs-site/.incache
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
  package.json
  packages/components/bolt-image/src/image.js
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-tabs/src/tabs.js
Labels: internal

#1499 fix(micro-journeys): dot-and-line nav squished on mobile with overlon…
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/billing-micro-journey-fragments/_micro-journey-demo-1.twig
  packages/micro-journeys/src/nav-shared.scss
Labels: bug

#1517 fix(micro-journeys): tighten dialog icon spacing
  packages/micro-journeys/src/status-dialogue-bar.scss
Labels: bug

#1514 Fix: Image Component Re-rendering / Perf Fix
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/05-device-viewer.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/10-device-viewer-ipad-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/15-device-viewer-iphone8-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/20-device-viewer-macbook-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/15-d8-resource-details-pages/00-resource-details-page.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/45-d8-blog/00-blog-homepage.twig
  packages/components/bolt-image/src/_image-lazy-sizes.js
  packages/components/bolt-image/src/image.js
  packages/components/bolt-image/src/image.twig
Labels: bug, improvement

#1518 Fix: List component's inline@breakpoint display options not aligning correctly in Firefox
  docs-site/src/pages/pattern-lab/_patterns/02-components/list/40-list-align-variations.twig
  packages/components/bolt-list/list.schema.yml
  packages/components/bolt-list/src/list.scss
Labels: bug, docs
