Repository boltdesignsystem/bolt, pull requests merged in 2020-01, with the labels that each got.

#1635 fix(micro-journeys): broaden desktop width of status bar
  packages/micro-journeys/src/status-dialogue-bar.scss
Labels: improvement

#1632 Hotfix: Fix IE11 Typeahead bugs
  docs-site/src/pages/pattern-lab/_patterns/02-components/typeahead/_typeahead-demo.twig
  packages/components/bolt-typeahead/__demos__/dynamically-fetch-data/typeahead.dynamically-fetch-data.js
  packages/components/bolt-typeahead/__demos__/navigate-to-exact-result/typeahead.navigate-to-exact-result.js
  packages/components/bolt-typeahead/__demos__/navigate-to-search-results/typeahead.navigate-to-search-results.js
  packages/components/bolt-typeahead/typeahead.autosuggest.js
  packages/components/bolt-typeahead/typeahead.js
Labels: bug, hotfix

#1651 Improve Initial SSR Rendering (Especially in IE 11)
  docs-site/src/templates/_site-footer.twig
  docs-site/src/templates/_site-head.twig
Labels: improvement

#1639 Upgrade Pattern Lab UIKit To Latest Version
  packages/website-ui/uikit-workshop/.gitignore
  packages/website-ui/uikit-workshop/.npmrc
  packages/website-ui/uikit-workshop/.patternlabrc.example.js
  packages/website-ui/uikit-workshop/README.md
  packages/website-ui/uikit-workshop/build-tools.js
  packages/website-ui/uikit-workshop/build/webpack-dev-server-waitpage/index.js
  packages/website-ui/uikit-workshop/build/webpack-dev-server-waitpage/pl-loading.ejs
  packages/website-ui/uikit-workshop/build/webpack-server.js
  packages/website-ui/uikit-workshop/package.json
  packages/website-ui/uikit-workshop/src/html/index.html
  packages/website-ui/uikit-workshop/src/html/partials/base-template.html
  packages/website-ui/uikit-workshop/src/sass/pattern-lab.scss
  packages/website-ui/uikit-workshop/src/sass/scss/02-base/_body.scss
  packages/website-ui/uikit-workshop/src/sass/scss/04-components/_pattern-states.scss
  packages/website-ui/uikit-workshop/src/sass/scss/04-components/_tabs.scss
  packages/website-ui/uikit-workshop/src/sass/scss/05-themes/_sidebar-theme.scss
  packages/website-ui/uikit-workshop/src/scripts/components/base-skate-preact-element.js
  packages/website-ui/uikit-workshop/src/scripts/components/copy-to-clipboard.js
  packages/website-ui/uikit-workshop/src/scripts/components/modal-styleguide.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-copy-to-clipboard/pl-copy-to-clipboard.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/get-parents.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/index.scss
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-accordion.scss
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-dropdown.scss
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-link.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-link.scss
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-list.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-list.scss
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav.scss
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/pl-nav.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/pl-nav.scss
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-controls/pl-controls.scss
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-drawer/pl-drawer.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-header/pl-header.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-icon/unsafe-svg.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-layout/pl-layout.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-logo/pl-logo.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.js
  packages/website-ui/uikit-workshop/src/scripts/patternlab-components.js
  packages/website-ui/uikit-workshop/src/scripts/patternlab-viewer.modern.js
  packages/website-ui/uikit-workshop/src/scripts/reducers/app.js
  packages/website-ui/uikit-workshop/webpack.config.js
  yarn.lock
Labels: enhancement

#1633 fix(micro-journeys): black connection band in Safari
  packages/experimental/micro-journeys/src/two-character-layout.js
  packages/micro-journeys/src/utils/is-chrome.js
Labels: bug

#1667 Webpack Cache Related Updates
  packages/build-tools/create-webpack-config.js
Labels: minor

#1672 Add Overflow Hidden to "Site" Content Container
  packages/components/bolt-site/site.scss
Labels: minor

#1660 Academy-related Band Updates
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-band/band.schema.yml
  packages/components/bolt-band/src/band.twig
Labels: minor, quick-review

#1655 Refactor Image Task in Build Tools
  packages/build-tools/package.json
  packages/build-tools/tasks/image-tasks.js
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-card-deprecated/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-device-viewer/__tests__/__snapshots__/device-viewer.js.snap
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-image/__tests__/__snapshots__/image.js.snap
  packages/components/bolt-image/__tests__/bolt-image.e2e.js
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-band-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-band-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-2-snap.png
  yarn.lock
Labels: minor

#1657 Minor Bolt Core Style Updates
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/core-v3.x/styles/01-settings/00-settings-lang/_settings.lang-ja.scss
  packages/core-v3.x/styles/01-settings/settings-breakpoints/_settings-breakpoints.scss
  packages/core-v3.x/styles/01-settings/settings-font-size/_settings-font-size.scss
  packages/core-v3.x/styles/01-settings/settings-font-weight/_settings-font-weight.scss
  packages/core-v3.x/styles/01-settings/settings-spacing/_settings-spacing.scss
Labels: enhancement

#1659 Headline Component Updates
  packages/components/bolt-headline/headline.schema.yml
  packages/components/bolt-headline/src/_tools.headlines.scss
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-headline/src/headline.scss
Labels: enhancement

#1669 Chip Updates for Academy
  packages/components/bolt-chip/src/chip.scss
Labels: minor, quick-review

#1671 Academy-related List Component CSS Update
  packages/components/bolt-list/src/_list-item.scss
Labels: minor, quick-review

#1661 Academy-related Background Updates
  packages/components/bolt-background/background.schema.yml
  packages/components/bolt-background/src/background.scss
  packages/components/bolt-background/src/background.twig
Labels: minor, quick-review

#1662 Minor Dynamic Import Cleanup
  packages/components/bolt-nav-indicator/index.js
  packages/components/bolt-nav-priority/index.js
  packages/components/bolt-navlink/index.js
Labels: minor, quick-review

#1663 Update Slotify Internal `templateMap` API
  packages/base-element/src/Slotify.js
  packages/components/bolt-button/src/button.js
  packages/components/bolt-link/src/link.js
Labels: minor

#1673 Code Snippet Wrapping / Scrolling Updates
  packages/components/bolt-code-snippet/src/_code-snippet-base.scss
Labels: enhancement

#1676 Hotfix/remove empty mj slots rebased
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/15-character-kitchen-sink.twig
  packages/experimental/editor/src/editor.js
  packages/experimental/editor/src/index.js
Labels: hotfix

#1677 Hotfix/improve two char layout while editing
  packages/experimental/editor/src/editor.js
  packages/experimental/micro-journeys/src/two-character-layout.js
Labels: hotfix

#1654 Academy-related SVG Updates
  .gitignore
  packages/build-tools/utils/icon-generator.js
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/index.js
  packages/components/bolt-icons/src/svgs/brand/brand-atom.svg
  packages/components/bolt-icons/src/svgs/brand/brand-meteor.svg
  packages/components/bolt-icons/src/svgs/brand/brand-molecule.svg
  packages/components/bolt-icons/src/svgs/brand/brand-orbit.svg
  packages/components/bolt-icons/src/svgs/brand/brand-rocket.svg
  packages/components/bolt-icons/src/svgs/brand/brand-satelite.svg
  packages/components/bolt-icons/src/svgs/brand/brand-triangle.svg
  packages/components/bolt-icons/src/svgs/brand/thumbs-up-open.svg
  packages/components/bolt-icons/src/svgs/brand/time-open.svg
  packages/components/bolt-icons/src/svgs/brand/world-open.svg
Labels: enhancement, quick-review

#1666 Misc Monorepo Updates
  .travis.yml
  docs-site/src/templates/_site-head.twig
  packages/build-tools/__tests__/multi-lang/.boltrc.multi-lang.js
  packages/testing/testing-jest/package.json
  patches/jest-image-snapshot+2.11.1.patch
  tsconfig.json
Labels: minor

#1664 Flag / Link / Image-related Academy Updates
  docs-site/src/pages/pattern-lab/_patterns/02-components/link/10-link-display-variations.twig
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-image/src/image.js
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/link.schema.yml
  packages/components/bolt-link/src/link.scss
  packages/global/styles/05-objects/objects-flag/src/flag.twig
Labels: enhancement

#1668 Restore Missing Yeoman Generator Jest Test
  packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js
Labels: minor

#1647 Component Explorer | DEV | Update name spacing
  jest.config.js
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js.snap
  packages/generators/yeoman-create-component/generators/component/__tests__/component-generator.js
  packages/generators/yeoman-create-component/generators/component/add-bolt-package.js
  packages/generators/yeoman-create-component/generators/component/index.js
  packages/generators/yeoman-create-component/generators/component/templates/component.js
  packages/generators/yeoman-create-component/generators/component/templates/index.component.js
  packages/generators/yeoman-create-component/generators/component/update-boltrc.js
  packages/generators/yeoman-create-component/package.json
  packages/testing/testing-jest/jest-global-teardown.js
  yarn.lock
Labels: improvement

#1658 Global Style Updates
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/core-v3.x/styles/01-settings/00-settings-lang/_settings.lang-ja.scss
  packages/core-v3.x/styles/01-settings/settings-spacing/_settings-spacing.scss
  packages/global/styles/03-generic/_generic-font-stacks.scss
  packages/global/styles/05-objects/objects-flag/_objects-flag.scss
  packages/global/styles/05-objects/objects-grid/_objects-grid.scss
  packages/global/styles/06-themes/_themes.all.scss
  packages/global/styles/07-utilities/_utilities-flex.scss
  packages/global/styles/07-utilities/_utilities-float.scss
  packages/global/styles/07-utilities/_utilities-line-length.scss
  packages/global/styles/07-utilities/_utilities-position.scss
  packages/global/styles/07-utilities/_utilities-spacing.scss
  packages/global/styles/07-utilities/_utilities-widths.scss
  packages/global/styles/index.scss
Labels: minor, quick-review

#1684 Webpack DLL / Polyfill Workaround
  packages/base-element/index.js
  packages/base-element/package.json
Labels: hotfix

#1636 fix(micro-journeys): ie11 shorten connection length in two-character-…
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/15-character-kitchen-sink.twig
  packages/experimental/micro-journeys/src/character.js
  packages/experimental/micro-journeys/src/character.scss
  packages/experimental/micro-journeys/src/two-character-layout.scss
Labels: enhancement

#1686 Academy-related Background Updates (Support Layers, New Fill Colors, etc)
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/03-organisms/heros/_hero--hp-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/04-templates/_landing-page-template.twig
  packages/components/bolt-background/background.schema.yml
  packages/components/bolt-background/src/background-item.twig
  packages/components/bolt-background/src/background-overlay.twig
  packages/components/bolt-background/src/background-shapes-wrapper.twig
  packages/components/bolt-background/src/background.scss
  packages/components/bolt-background/src/background.twig
Labels: quick-review

#1690 fix: address HTML rendering / escaping issue w/ Card Replacement Body in Drupal
  packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
Labels: hotfix

#1691 feat(editor): add prop schema descriptions underneath traits
  packages/experimental/editor/src/editor.js
  packages/experimental/editor/src/utils.js
Labels: enhancement

#1687 Tooltip | FE | Refactor and redesign
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/00-tooltip-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/05-tooltip.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/10-tooltip-direction-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/10-tooltip-placement-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/15-tooltip-nowrap-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/15-tooltip-use-case-button-and-link.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/20-tooltip-spacing-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/20-tooltip-use-case-icon.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/25-tooltip-trigger-type-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/30-tooltip-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/999-tooltip-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/_poc-tooltip.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/35-d8-events/00-event-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/35-d8-events/05-event-detail.twig
  packages/components/bolt-link/link.schema.js
  packages/components/bolt-tooltip/README.md
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/__tests__/tooltip.js
  packages/components/bolt-tooltip/package.json
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-tooltip/src/tooltip.twig
  packages/components/bolt-tooltip/tooltip.schema.js
  packages/components/bolt-tooltip/tooltip.schema.yml
  packages/core-v3.x/utils/index.js
  packages/core-v3.x/utils/is-focusable.js
  yarn.lock
Labels: enhancement

#1696 Feature/dashboard updates
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/01-atoms/toolbar-buttons/_remove.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/01-atoms/toolbar-buttons/_share.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/01-atoms/toolbar-buttons/_toolbar-button.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/02-molecules/cards/_vertical-card.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/02-molecules/user-actions/_toolbar-actions.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/03-organisms/collections/dashboard/_dashboard-band--in-progress.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/03-organisms/collections/dashboard/_dashboard-band.twig
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action-item.twig
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-actions.twig
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
  packages/components/bolt-tooltip/src/tooltip.js
  yarn.lock
Labels: enhancement

#1698 Ship new Banner component originally slated for v2.15.0
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/pages/pattern-lab/_patterns/02-components/banner/00-banner-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/banner/05-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/banner/10-banner-status-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/banner/15-banner-align-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/banner/20-banner-use-case-status-report.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/banner/999-banner-with-web-component.twig
  packages/components/bolt-banner/README.md
  packages/components/bolt-banner/__tests__/__snapshots__/banner.js.snap
  packages/components/bolt-banner/__tests__/banner.js
  packages/components/bolt-banner/banner.schema.js
  packages/components/bolt-banner/index.js
  packages/components/bolt-banner/index.scss
  packages/components/bolt-banner/package.json
  packages/components/bolt-banner/src/banner.js
  packages/components/bolt-banner/src/banner.scss
  packages/components/bolt-banner/src/banner.twig
Labels: patch

#1703 Fix: corrects the stacking order in vertical card media
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/cards/_vertical-card.twig
Labels: patch

#1682 Fix/spacing adjustments and misc
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/15-character-kitchen-sink.twig
  packages/experimental/editor/src/components.js
  packages/experimental/editor/src/editor.js
  packages/experimental/editor/src/setup-bolt.js
  packages/experimental/micro-journeys/src/bolt-svg-animations/svg-animations.js
  packages/experimental/micro-journeys/src/bolt-svg-animations/svg/connectionBand.js
  packages/experimental/micro-journeys/src/bolt-svg-animations/svg/tripleConnectionBand.js
  packages/experimental/micro-journeys/src/character.js
  packages/experimental/micro-journeys/src/character.schema.js
  packages/experimental/micro-journeys/src/character.scss
  packages/experimental/micro-journeys/src/interactive-pathway.scss
  packages/experimental/micro-journeys/src/interactive-step.scss
  packages/experimental/micro-journeys/src/one-character-layout.scss
  packages/experimental/micro-journeys/src/status-dialogue-bar.js
  packages/experimental/micro-journeys/src/status-dialogue-bar.schema.js
  packages/experimental/micro-journeys/src/status-dialogue-bar.scss
  packages/experimental/micro-journeys/src/two-character-layout.js
  packages/experimental/micro-journeys/src/two-character-layout.scss
  packages/experimental/micro-journeys/src/utils/equalize-relative-heights.js
  packages/experimental/micro-journeys/starters/step-one-character-starter.html
  packages/experimental/micro-journeys/starters/step-two-character-starter.html
  packages/experimental/micro-journeys/starters/two-characters-2.html
  scripts/release/update-php-package-versions.js
Labels: improvement

#1615 Icon Refactor: Switch To SVG Sprite Loader + SVGO Loader
  example-integrations/angular/package.json
  example-integrations/drupal-lab/package.json
  packages/build-tools/package.json
  packages/build-tools/plugins/file-passthrough-loader/package.json
  packages/components/bolt-menu/package.json
  packages/components/bolt-page-footer/package.json
  packages/components/bolt-toolbar/package.json
  packages/website-ui/uikit-prerender-spa-plugin/package.json
  packages/website-ui/uikit-prerenderer/package.json
Labels: minor

#1678 Chore/schema cleanup
  packages/components/bolt-logo/logo.schema.yml
  packages/components/bolt-pagination/pagination.schema.yml
  packages/components/bolt-share/share.schema.yml
  packages/components/bolt-tabs/tabs.schema.yml
Labels: minor

#1648 Feat/bds 1937 add compatibility mode
  .boltrc.js
  docs-site/package.json
  package.json
  packages/build-tools/cli.js
  packages/build-tools/create-webpack-config.js
  packages/build-tools/utils/config-store.js
  packages/build-tools/utils/config.schema.yml
Labels: improvement

#1685 feat(editor): remove click handlers on element select; add function d…
  docs-site/src/pages/pattern-lab/_patterns/06-experiments/editor/20-editor-modal.twig
  packages/experimental/editor/src/editor.js
Labels: enhancement

#1710 chore(editor): remove console log
  packages/experimental/editor/src/editor.js
Labels: minor

#1700 Popover | FE | Fast-follows to clean up and document
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/00-popover-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/05-popover.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/10-popover-placement-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/15-popover-spacing-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/20-popover-use-case-menu.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/999-popover-with-web-component.twig
  packages/components/bolt-popover/README.md
  packages/components/bolt-popover/__tests__/__snapshots__/popover.js.snap
  packages/components/bolt-popover/__tests__/popover.js
  packages/components/bolt-popover/package.json
  packages/components/bolt-popover/popover.schema.js
  packages/components/bolt-popover/popover.schema.yml
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-popover/src/popover.twig
  packages/components/bolt-tooltip/package.json
  yarn.lock
Labels: enhancement

#1705 Fix Tooltip + Popover Placement
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/10-tooltip-placement-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_toolbar-button.twig
  packages/components/bolt-popover/popover.schema.js
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-popover/src/popover.twig
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.twig
  packages/components/bolt-tooltip/tooltip.schema.js
Labels: improvement

#1675 Table of content | Academy | New component to navigate within an article
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc/00-toc-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc/05-toc.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc/10-toc-item-active-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc/15-toc-header-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc/20-toc-use-case-sticky.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc/999-toc-with-web-component.twig
  packages/components/bolt-toc/README.md
  packages/components/bolt-toc/__tests__/__snapshots__/toc.js.snap
  packages/components/bolt-toc/__tests__/toc.js
  packages/components/bolt-toc/index.js
  packages/components/bolt-toc/index.scss
  packages/components/bolt-toc/package.json
  packages/components/bolt-toc/src/_toc-item.js
  packages/components/bolt-toc/src/_toc-item.scss
  packages/components/bolt-toc/src/_toc-item.twig
  packages/components/bolt-toc/src/toc.js
  packages/components/bolt-toc/src/toc.scss
  packages/components/bolt-toc/src/toc.twig
  packages/components/bolt-toc/toc.schema.js
Labels: enhancement

#1713 Twig rendering fixes for Toolbar + Icon; fix for docs site visual regression w/ CSS vars fallback
  docs-site/src/templates/_site-head.twig
  packages/components/bolt-icon/src/icon.twig
  packages/components/bolt-toolbar/toolbar.twig
Labels: bug, quick-review

#1715 Restore -none- option for icons in dialog bar
  packages/experimental/micro-journeys/src/status-dialogue-bar.schema.js
Labels: hotfix

#1714 Hotfix/wwwd 4533 web component icon background match twig
  packages/components/bolt-icon/src/icon.standalone.js
Labels: hotfix

#1717 Fix Step removal event not firing due to removal of Animate parent
  packages/experimental/editor/src/editor.js
Labels: hotfix

#1712 TOC | JS | Add smooth scroll and scroll-spy behavior
  packages/components/bolt-toc/__tests__/__snapshots__/toc.js.snap
  packages/components/bolt-toc/package.json
  packages/components/bolt-toc/src/_toc-item.js
  packages/components/bolt-toc/src/toc.js
  packages/components/bolt-toc/src/toc.twig
  packages/components/bolt-toc/src/waypoint/computeOffsetPixels.js
  packages/components/bolt-toc/src/waypoint/getBounds.js
  packages/components/bolt-toc/src/waypoint/getCurrentPosition.js
  packages/components/bolt-toc/src/waypoint/index.js
  packages/components/bolt-toc/src/waypoint/parseOffsetAsPercentage.js
  packages/components/bolt-toc/src/waypoint/parseOffsetAsPixels.js
Labels: enhancement

#1681 feat: Add suggested bolt.rc file for external builds
  __tests__/monorepo-basics.test.js
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/pages/docs/50-guides/15-building-a-new-component.md
  packages/base-starter-kit/.boltrc.demo.js
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/.gitignore
  packages/base-starter-kit/demo.html
  packages/base-starter-kit/package.json
  packages/generators/yeoman-create-component/generators/component/update-boltrc.js
  packages/generators/yeoman-create-component/package.json
  packages/testing/testing-utils/__tests__/test-utils.test.js
  yarn.lock
Labels: enhancement

#1719 Fix: add missing role attributes to menu component
  packages/components/bolt-menu/__tests__/__snapshots__/menu.js.snap
  packages/components/bolt-menu/src/_menu-item.js
  packages/components/bolt-menu/src/_menu-item.twig
  packages/components/bolt-menu/src/menu.js
  packages/components/bolt-menu/src/menu.twig
Labels: improvement

#1707 Carousel Pre-Rendering Fixes + Cleanup
  .stylelintrc
  docs-site/src/pages/pattern-lab/_patterns/02-components/carousel/15-carousel-slides-per-view-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/cards/_vertical-card.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band.twig
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-7-snap.png
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-carousel/carousel.schema.yml
  packages/components/bolt-carousel/index.scss
  packages/components/bolt-carousel/package.json
  packages/components/bolt-carousel/src/_carousel-settings-and-tools.scss
  packages/components/bolt-carousel/src/_carousel-slide.scss
  packages/components/bolt-carousel/src/_carousel-slide.slides-per-view-auto.scss
  packages/components/bolt-carousel/src/_carousel-slide.slides-per-view-fixed.scss
  packages/components/bolt-carousel/src/_carousel-slide.slides-per-view.scss
  packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
  packages/components/bolt-carousel/src/_carousel.scss
  packages/components/bolt-carousel/src/carousel.js
  packages/components/bolt-icon/src/icon.standalone.js
  yarn.lock
Labels: improvement

#1720 Fix/link whitespace
  packages/components/bolt-link/__tests__/__image_snapshots__/link-js-link-default-bolt-link-with-shadow-dom-renders-with-no-extra-whitespace-1-snap.png
  packages/components/bolt-link/__tests__/__image_snapshots__/link-js-link-default-bolt-link-with-shadow-dom-renders-with-no-extra-whitespace-2-snap.png
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-link/src/link.js
Labels: bug

#1722 feat: add "My Missions" and "Add Mission" templates
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-missions/dashboard--my-missions.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-missions/dashboard--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard/dashboard-add-mission.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard/dashboard~add-mission.json
Labels: enhancement
