Repository boltdesignsystem/bolt, pull requests merged in 2020-06, with the labels that each got.

#1882 Allow autoplay video for iPhone/iPad when controls disabled
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/autoplay/-autoplay-and-loop-hide-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/autoplay/-autoplay-and-loop.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/autoplay/-autoplay.twig
  packages/components/bolt-video/src/video.standalone.js
Labels: bug

#1883 BDS-2118: Investigate options for Brightcove error styling/UX
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/70-video-with-default-error-message.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/71-video-with-custom-error-message.twig
  packages/components/bolt-video/src/_video-tag.twig
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/components/bolt-video/src/video.standalone.js
  packages/components/bolt-video/video.schema.yml
Labels: enhancement

#1879 Move layout change event to be dispatched after bolt-interactive-path…
  packages/experimental/micro-journeys/src/interactive-pathway.js
  packages/experimental/micro-journeys/src/interactive-pathways.js
Labels: bug

#1885 Fix tooltip flicker
  packages/components/bolt-tooltip/src/tooltip.js
Labels: bug

#1890 BDS-2118: added the error code back into the error message
  docs-site/.incache
  packages/components/bolt-icons/package.json
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/generators/yeoman-create-component/package.json
Labels: improvement

#1892 WWWD-4862/BDS-2157/BDS-37 broken watch icon
  packages/components/bolt-icons/src/svgs/utility/watch.svg
Labels: hotfix

#1878 Feature/device viewer enable video embed
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/00-device-viewer-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/05-device-viewer.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/10-device-viewer-ipad-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/15-device-viewer-iphone8-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/20-device-viewer-macbook-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/25-device-viewer-video.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/30-device-viewer-content-magnifier-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/image/30-image-zoom-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/_product-t3-extra-videos.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/_product-t3.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t2.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t4.twig
  packages/components/bolt-device-viewer/device-viewer.schema.yml
  packages/components/bolt-device-viewer/src/device-viewer.twig
  packages/components/bolt-image/__tests__/bolt-image.e2e.js
  packages/components/bolt-image/image.schema.yml
  packages/components/bolt-image/src/image.twig
Labels: minor

#1897 DS-104 code snippet web component default props and text wrapping
  docs-site/src/pages/pattern-lab/_patterns/02-components/code-snippet/999-code-snippet-web-component.twig
  packages/components/bolt-code-snippet/src/_code-snippet-base.scss
  packages/components/bolt-code-snippet/src/code-snippet.standalone.js
Labels: bug

#1895 Feature/ds 96
  docs-site/src/pages/docs/45-development/01-local-dev-environment-setup.md
Labels: docs
