Repository boltdesignsystem/bolt, pull requests merged in 2020-05, with the labels that each got.

#1863 IE11 deprecation: Remove deprecated packages
  docs-site/.boltrc.js
  example-integrations/angular/.bolt/.boltrc.js
  example-integrations/angular/.bolt/package.json
  example-integrations/static-html/.bolt/.boltrc.js
  example-integrations/static-html/.bolt/package.json
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-critical-css-vars/CHANGELOG.md
  packages/components/bolt-critical-css-vars/package.json
  packages/components/bolt-critical-path-polyfills/CHANGELOG.md
  packages/components/bolt-critical-path-polyfills/README.md
  packages/components/bolt-critical-path-polyfills/package.json
  packages/components/bolt-critical-path-polyfills/rollup.config.js
  packages/components/bolt-critical-path-polyfills/src/index.js
  yarn.lock
Labels: breaking change

#1859 Migrate "Add Classes to Slotted Children" functionality to BoltElement
  packages/base-element/index.js
  packages/base-element/src/BoltElement.js
  packages/base-element/src/lib/decorators.js
  packages/base-element/src/lib/decorators/add-classes-to-slotted-children.js
  packages/base-element/src/lib/decorators/conditional-shadow-dom.js
  packages/base-element/src/lib/decorators/convert-initial-tags.js
  packages/base-element/src/lib/decorators/index.js
  packages/base-element/src/lib/decorators/json-schema-props.js
  packages/base-element/src/lib/decorators/lazy-styles.js
  packages/base-element/src/lib/decorators/render-and-rendered-events.js
Labels: improvement, quick-review, web performance

#1862 Add deprecation notices and migration docs
  docs-site/src/pages/docs/50-guides/60-migrating-to-3.x.md
  packages/build-tools/plugins/postcss-themify/README.md
  packages/components/bolt-critical-css-vars/README.md
  packages/components/bolt-critical-css/README.md
  packages/components/bolt-critical-fonts/README.md
  packages/components/bolt-critical-path-polyfills/README.md
Labels: deprecation, minor

#1867 Micro Journey intersection observer-related fix to prevent "restarts" when scrolling away
  packages/experimental/micro-journeys/src/interactive-pathways.js
Labels: bug

#1865 Fix: body text color
  docs-site/src/pages/pattern-lab/_patterns/02-components/headline/05-headline.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/headline/10-headline-tag-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/headline/15-headline-align-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/headline/20-headline-style-and-weight-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/headline/25-headline-icon-variations.twig
  packages/components/bolt-headline/src/_tools.headlines.scss
  packages/components/bolt-headline/src/headline.scss
Labels: bug, minor

#1852 Card | Docs | Add demo of controlling horizontal card image size
  docs-site/src/assets/images/placeholders/thumb-square-abstract.jpg
  docs-site/src/pages/pattern-lab/_patterns/02-components/card-replacement/06-card-horizontal.twig
Labels: docs

#1861 Migrate Icon component over to LitElement; reduce overall SVG file size by 2.5x
  packages/build-tools/create-webpack-config.js
  packages/build-tools/svgo-plugins.js
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
  packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-card-deprecated/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-chip-list/__tests__/__snapshots__/chip-list.js.snap
  packages/components/bolt-chip/__tests__/__snapshots__/chip.js.snap
  packages/components/bolt-copy-to-clipboard/__tests__/__snapshots__/copy-to-clipboard.js.snap
  packages/components/bolt-device-viewer/__tests__/__snapshots__/device-viewer.js.snap
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/components/bolt-icon/package.json
  packages/components/bolt-icon/registry.js
  packages/components/bolt-icon/src/icon.js
  packages/components/bolt-icon/src/icon.json
  packages/components/bolt-icon/src/icon.jsx
  packages/components/bolt-icon/src/icon.standalone.js
  packages/components/bolt-icons/__tests__/__snapshots__/icons.js.snap
  packages/components/bolt-icons/__tests__/icons.js
  packages/components/bolt-icons/package.json
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-band-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-at-various-viewport-sizes-4-snap.png
  packages/components/bolt-navbar/__tests__/__snapshots__/navbar.js.snap
  packages/components/bolt-share/__tests__/__snapshots__/share.js.snap
  packages/components/bolt-sticky/__tests__/__snapshots__/sticky.js.snap
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
  yarn.lock
Labels: improvement, web performance

#1858 Migrate Accordion web component to now render using LitElement
  packages/components/bolt-accordion/__tests__/__image_snapshots__/accordion-js-bolt-accordion-component-default-bolt-accordion-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-accordion/__tests__/__image_snapshots__/accordion-js-bolt-accordion-component-default-bolt-accordion-w-o-shadow-dom-renders-3-snap.png
  packages/components/bolt-accordion/__tests__/__image_snapshots__/accordion-js-bolt-accordion-component-default-bolt-accordion-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-accordion/__tests__/__image_snapshots__/accordion-js-bolt-accordion-component-default-bolt-accordion-with-shadow-dom-renders-4-snap.png
  packages/components/bolt-accordion/__tests__/__image_snapshots__/accordion-js-bolt-accordion-component-default-bolt-accordion-with-shadow-dom-renders-5-snap.png
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-accordion/index.js
  packages/components/bolt-accordion/main.js
  packages/components/bolt-accordion/src/AccordionItem/AccordionItemContent.js
  packages/components/bolt-accordion/src/AccordionItem/AccordionItemTrigger.js
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig
  packages/components/bolt-accordion/src/AccordionItem/index.js
  packages/components/bolt-accordion/src/accordion.js
  packages/components/bolt-icon/package.json
Labels: enhancement, web performance

#1868 Link as popover trigger
  docs-site/src/pages/pattern-lab/_patterns/02-components/link/28-link-with-button-element.twig
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-link/src/link.js
  packages/components/bolt-link/src/link.scss
  packages/components/bolt-link/src/link.twig
Labels: enhancement, minor

#1864 Update build tools to no longer "magically" pull in related pkg dependencies (if no issues are found)
  __tests__/monorepo-basics.test.js
  packages/base-starter-kit/package.json
  packages/build-tools/utils/manifest.deprecated.js
  packages/build-tools/utils/manifest.get-pkg-info.js
  packages/build-tools/utils/manifest.js
Labels: improvement, minor, web performance

#1870 Rate This Mission Blueprint Layout Fix for Safari / Firefox
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/index.scss
Labels: bug, minor, quick-review
