Repository boltdesignsystem/bolt, pull requests merged in 2020-02, with the labels that each got.

#1727 `@bolt/element` conditional Shadow DOM fix; add `css` export
  packages/base-element/index.js
  packages/base-element/src/lib/decorators.js
  packages/base-element/src/lib/utils.js
  packages/components/bolt-button/src/button.js
Labels: minor

#1709 Breadcrumb | Docs | Demo popover inside a breadcrumb
  docs-site/src/pages/pattern-lab/_patterns/02-components/breadcrumb/00-breadcrumb-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/breadcrumb/05-breadcrumb.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/breadcrumb/10-breadcrumb-current-page-aria-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/breadcrumb/10-breadcrumb-use-case-popover.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/breadcrumb/15-breadcrumb-use-case-band.twig
  packages/components/bolt-breadcrumb/README.md
  packages/components/bolt-breadcrumb/package.json
Labels: enhancement

#1723 Icon | Docs | Add web component documentation
  docs-site/src/pages/pattern-lab/_patterns/02-components/icon/999-icon-with-web-component.twig
Labels: enhancement

#1728 fix: remove padding on last list item
  packages/components/bolt-list/src/_list-item.scss
Labels: bug, quick-review

#1725 Monorepo and dependency-related maintenance
  .npmrc
  docs-site/composer.lock
  docs-site/package.json
  package.json
  packages/build-tools/package.json
  packages/build-tools/plugins/file-passthrough-loader/package.json
  packages/build-tools/plugins/postcss-themify/package.json
  packages/build-tools/plugins/postcss-themify/src/index.js
  packages/build-tools/plugins/sassdoc-webpack-plugin/package.json
  packages/build-tools/plugins/sassdoc-webpack-plugin/sassdoc-webpack-plugin.js
  packages/build-tools/svg-to-icon-component-runtime-generator.js
  packages/build-tools/utils/package.json
  packages/components/bolt-critical-css-vars/package.json
  packages/components/bolt-critical-path-polyfills/package.json
  packages/components/bolt-critical-path-polyfills/rollup.config.js
  packages/components/bolt-popover/package.json
  packages/components/bolt-typeahead/package.json
  packages/configs/eslint-config/package.json
  packages/experimental/micro-journeys/package.json
  packages/testing/testing-jest/jest-global-setup.js
  packages/testing/testing-jest/package.json
  packages/twig-integration/twig-renderer-endpoint/index.js
  packages/twig-integration/twig-renderer-endpoint/package.json
  packages/twig-integration/twig-renderer/package.json
  packages/website-ui/uikit-prerenderer/index.js
  packages/website-ui/uikit-prerenderer/package.json
  packages/website-ui/uikit-prerenderer/renderer.mjs
  packages/website-ui/uikit-workshop/package.json
  packages/website-ui/uikit-workshop/webpack.config.js
  patches/jest-image-snapshot+2.12.0.patch
  scripts/package.json
  yarn.lock
Labels: minor

#1726 Build tools & yeoman component generator maintenance & stability updates
  packages/build-tools/package.json
  packages/build-tools/tasks/api-tasks/bolt-versions.js
  packages/build-tools/tasks/webpack-dev-server-waitpage/bolt.ejs
  packages/build-tools/tasks/webpack-dev-server-waitpage/index.js
  packages/build-tools/utils/timer.js
  packages/generators/yeoman-create-component/generators/component/index.js
  packages/generators/yeoman-create-component/generators/component/templates/package.tpl.json
Labels: minor

#1729 Fix block() and include() autoescaping
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/_checkbox.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/_custom-select.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/_select.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_share.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/macros.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/h5p-embed/h5p-embed.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/search-and-filtereing/_chips--search-filter.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/search-and-filtereing/_hide-show-completed.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/user-actions/_toolbar-actions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--in-progress.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--new-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--recommended.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/_hero-partials/_hero-primary-content.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/_hero-partials/_hero-secondary-content.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/dashboard-page-hero/dashboard-page-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/homepage-heros/_hero--hp-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/landing-page-hero/landing-page-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/wip-heros/_hero--request-feedback.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/search/_search-bar.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/toolbar/_toolbar.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_landing-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/certification-exam/certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/_mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/challenge-details/t2-challenge-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/wip-pages/mission-exercise/_t2-mission-exercise-detail-page.twig
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
  packages/components/bolt-toolbar/toolbar.twig
Labels: bug

#1724 Build Topic Details Page Blueprint + Supporting Updates
  __tests__/monorepo-deps.test.js
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/00-assets/images/placeholders/1920x1200.jpg
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/00-assets/images/placeholders/1920x1440.jpg
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/00-assets/images/placeholders/1920x960.jpg
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/user-actions/_toolbar-actions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/_hero-partials/_hero-primary-content.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/details-page-hero/details-page-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/toolbar/_toolbar.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/topic-details/t2-topic-detail-page.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/topic-details/t2-topic-detail-page.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/topic-details/t2-topic-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/package.json
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.scss
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-popover/src/popover.twig
  packages/components/bolt-site/site.scss
  packages/components/bolt-toc/src/_toc-item.scss
  packages/components/bolt-toc/src/toc.scss
  packages/components/bolt-toolbar/toolbar.scss
  packages/components/bolt-toolbar/toolbar.twig
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/core-v3.x/styles/01-settings/settings-font-weight/_settings-font-weight.scss
  packages/global/styles/03-generic/_generic-font-stacks.scss
  packages/global/styles/04-elements/_elements-page.scss
  packages/global/styles/07-utilities/_utilities-float.scss
Labels: minor, quick-review

#1734 Remove CSS workarounds for micro journeys in dark theme
  packages/experimental/micro-journeys/src/interactive-pathway.scss
  packages/experimental/micro-journeys/src/interactive-step.scss
  packages/experimental/micro-journeys/src/nav-shared.scss
Labels: improvement

#1736 Theming | Docs | Add theme colors demo page
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/00-color-palette/04-theming.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/00-color-palette/_color-swatch.scss
Labels: docs

#1731 Feature/training page
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/_select.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/training/_completed-training-item.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/completed-training/completed-training.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/completed-training/completed-training.twig
  packages/components/bolt-pagination/src/pagination.scss
Labels: minor

#1733 Fix popover double-focus
  packages/components/bolt-popover/src/popover.js
Labels: bug, minor, quick-review

#1742 Fix micro journey up and down buttons
  packages/experimental/editor/src/editor.js
  packages/experimental/micro-journeys/src/interactive-pathway.js
  packages/experimental/micro-journeys/src/interactive-step.js
Labels: hotfix

#1744 Fix: negative margin mixin and maps
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/core-v3.x/styles/01-settings/00-settings-lang/_settings.lang-ja.scss
  packages/core-v3.x/styles/01-settings/settings-spacing/_settings-spacing.scss
  packages/global/styles/07-utilities/_utilities-spacing.scss
Labels: bug

#1743 Fix broken PL pages
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-default-page-template.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-default-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-landing-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/completed-training/completed-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-missions/dashboard--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard/dashboard.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/homepage/00-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/search/search-results--archived/search-results-page--archived.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/search/search-results--filtered/search-results-page--filtered.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/search/search-results/search-results-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/certification-exam/certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test/t1-mission-landing--test.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/_mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/challenge-details/t2-challenge-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/topic-details/t2-topic-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/wip-pages/mission-exercise/_t2-mission-exercise-detail-page.twig
Labels: bug

#1732 Popover | FE | NoJS fallback styles
  packages/components/bolt-popover/__tests__/__snapshots__/popover.js.snap
  packages/components/bolt-popover/popover.schema.js
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-popover/src/popover.twig
Labels: enhancement

#1737 Fix Button `disabled` prop
  packages/base-element/src/BoltActionElement.js
  packages/components/bolt-button/__tests__/__image_snapshots__/button-js-button-button-with-disabled-adds-attr-to-a-3-snap.png
  packages/components/bolt-button/__tests__/__image_snapshots__/button-js-button-button-with-disabled-adds-attr-to-button-3-snap.png
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-button/src/button.js
Labels: bug, minor

#1747 SVG Icon Theming / Coloring Fix
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/build-tools/plugins/svg-transform-loader/index.js
  packages/build-tools/svgo-plugins.js
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-card-deprecated/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-chip/__tests__/__snapshots__/chip.js.snap
  packages/components/bolt-copy-to-clipboard/__tests__/__snapshots__/copy-to-clipboard.js.snap
  packages/components/bolt-device-viewer/__tests__/__snapshots__/device-viewer.js.snap
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/components/bolt-icon/src/icon.scss
  packages/components/bolt-icons/__tests__/__snapshots__/icons.js.snap
  packages/components/bolt-icons/src/svgs/utility/file-small.svg
  packages/components/bolt-navbar/__tests__/__snapshots__/navbar.js.snap
  packages/components/bolt-share/__tests__/__snapshots__/share.js.snap
  packages/components/bolt-sticky/__tests__/__snapshots__/sticky.js.snap
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
Labels: bug

#1748 Fix wrapping links in Safari
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band.twig
Labels: bug

#1750 Updating Modal snapshots
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-bolt-modal-slots-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-band-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-band-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-w-o-shadow-dom-renders-1-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-with-band-at-various-viewport-sizes-2-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-with-band-at-various-viewport-sizes-3-snap.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/modal-js-bolt-modal-component-simple-usage-bolt-modal-with-shadow-dom-renders-1-snap.png
Labels: hotfix, minor

#1749 Build Tools | Update SVGO to force merging SVG paths; remove mask in `asset-text` icon
  packages/build-tools/svgo-plugins.js
  packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
  packages/components/bolt-copy-to-clipboard/__tests__/__snapshots__/copy-to-clipboard.js.snap
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/components/bolt-icons/__tests__/__snapshots__/icons.js.snap
  packages/components/bolt-icons/src/svgs/utility/asset-text.svg
Labels: enhancement

#1752 fix: Correct icon color rules
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-icon/src/icon.scss
Labels: hotfix

#1754 Bolt List | Custom separator color
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/training/_training-meta-items.twig
  packages/components/bolt-list/__tests__/__image_snapshots__/list-js-bolt-list-component-list-custom-separator-color-2-snap.png
  packages/components/bolt-list/__tests__/__snapshots__/list.js.snap
  packages/components/bolt-list/__tests__/list.js
  packages/components/bolt-list/src/_list-item.scss
Labels: enhancement

#1753 BDS | Docs | Typography and spacing
  docs-site/src/assets/images/placeholders/oliver-silouette.png
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/05-spacing/00-spacing-overview.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/05-spacing/_spacing.scss
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/05-spacing/spacing.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/10-typography/-blockquotes.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/10-typography/-headings.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/10-typography/-lists.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/10-typography/00-text.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/10-typography/00-typography-overview.twig
Labels: docs, enhancement

#1762 Fix failing Lighthouse job
  lighthouserc.json
Labels: bug

#1761 Fix Pattern Lab Viewport Resizer Calculation
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-viewport-size/pl-viewport-size.js
Labels: patch

#1760 Fix OL number bugs in Firefox
  packages/components/bolt-li/src/li.scss
  packages/components/bolt-ol/src/ol.scss
Labels: bug

#1757 Fix the Blockquote web component to support the existing `size` prop
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-blockquote/src/blockquote.js
Labels: patch
