Repository boltdesignsystem/bolt, pull requests merged in 2020-09, with the labels that each got.

#1955 DS-193: fix list wrapping bug in safari
  packages/components/bolt-list/src/list.scss
Labels: type: bugfix

#1968 DS-177: update academy color and gradient usage with new brand colors
  docs-site/.incache
  docs-site/src/components/release-banner/release-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/05-color-tokens.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/_color-swatch.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/05-spacing/10-spacing-utilities.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/00-information-density-system.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/icon/10-icon-theme-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/icon/15-icon-color-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/progress-bar/30-progress-bar-in-toolbar.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/display/_icon-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--new-training.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--recommended.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/search/_search-results--results-list.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/modals/_test-completed-modal--return-to-mission.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/completed-training/acd-completed-training.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/homepage/_00-acd-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/certification-exam/acd-certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/mission-landing/acd-mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-background/background.schema.js
  packages/components/bolt-background/src/background.scss
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icon/src/icon.scss
  packages/components/bolt-icon/src/icon.twig
  packages/components/bolt-toolbar/toolbar.scss
  packages/core-v3.x/styles/01-settings/settings-colors/_settings-colors.scss
Labels: type: feature

#1973 DS-208: remove "full" prop from bolt-banner
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/00-assets/images/pega-community.svg
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/04-templates/_academy-detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
  packages/components/bolt-banner/__tests__/__snapshots__/banner.js.snap
  packages/components/bolt-banner/banner.schema.js
  packages/components/bolt-banner/src/banner.js
  packages/components/bolt-banner/src/banner.scss
  packages/components/bolt-banner/src/banner.twig
Labels: type: feature

#1969 WWW-209: make animation wait till JS is loaded
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-calculator.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-results.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/calculator.scss
Labels: type: bugfix

#1971 DS-197: Update Stack to the latest renderer.
  packages/components/bolt-stack/src/stack.js
Labels: type: feature

#1965 Convert Bolt-List to Latest Renderer
  packages/components/bolt-list/src/_list-item.js
  packages/components/bolt-list/src/list.js
Labels: type: feature

#1976 DS-45: Add missing 'wc-context' dependencies
  packages/components/bolt-accordion/package.json
  packages/components/bolt-card-replacement/package.json
  packages/components/bolt-list/package.json
Labels: type: feature

#1977 2.28.0 Release
  docs-site/.incache
  docs-site/src/components/release-banner/release-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/05-color-tokens.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/_color-swatch.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/05-spacing/10-spacing-utilities.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/00-information-density-system.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/icon/10-icon-theme-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/icon/15-icon-color-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/progress-bar/30-progress-bar-in-toolbar.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-calculator.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-results.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/calculator.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/00-assets/images/pega-community.svg
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/display/_icon-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--new-training.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--recommended.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/search/_search-results--results-list.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/modals/_test-completed-modal--return-to-mission.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/04-templates/_academy-detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/completed-training/acd-completed-training.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/homepage/_00-acd-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/certification-exam/acd-certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/mission-landing/acd-mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-accordion/package.json
  packages/components/bolt-background/background.schema.js
  packages/components/bolt-background/src/background.scss
  packages/components/bolt-banner/__tests__/__snapshots__/banner.js.snap
  packages/components/bolt-banner/banner.schema.js
  packages/components/bolt-banner/src/banner.js
  packages/components/bolt-banner/src/banner.scss
  packages/components/bolt-banner/src/banner.twig
  packages/components/bolt-card-replacement/package.json
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icon/src/icon.scss
  packages/components/bolt-icon/src/icon.twig
  packages/components/bolt-list/package.json
  packages/components/bolt-list/src/_list-item.js
  packages/components/bolt-list/src/list.js
  packages/components/bolt-list/src/list.scss
  packages/components/bolt-stack/src/stack.js
  packages/components/bolt-toolbar/toolbar.scss
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/core-v3.x/styles/01-settings/settings-colors/_settings-colors.scss
  packages/experimental/editor/src/editor.js
  packages/experimental/editor/src/main.js
Labels: version: minor

#1975 DS-198: Rename `update` to `updateLayout`
  packages/components/bolt-accordion/src/accordion.js
  packages/components/bolt-carousel/src/carousel.js
  packages/components/bolt-tabs/src/tabs.js
Labels: type: feature

#1981 WWW-269: fix calculator background overflow
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-calculator.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/calculator.scss
Labels: type: bugfix

#1980 DS-200: Convert UL, OL, LI to BoltElement renderer
  packages/components/bolt-li/src/li.js
  packages/components/bolt-ol/src/ol.js
  packages/components/bolt-ul/src/ul.js
  packages/components/bolt-ul/ul.schema.js
  packages/core-v2.x/utils/index.js
  packages/core-v2.x/utils/map-with-depth.js
  packages/core-v3.x/utils/index.js
  packages/core-v3.x/utils/map-with-depth.js
Labels: type: feature

#1979 DS-213 Modal Conversion
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-modal/focus-trap/focus-trap.js
  packages/components/bolt-modal/modal.schema.js
  packages/components/bolt-modal/src/modal.js
Labels: type: feature

#1982 DS-222: Convert Table to latest renderer
  packages/components/bolt-table/__tests__/__snapshots__/table.js.snap
  packages/components/bolt-table/src/table.js
Labels: type: feature

#1983 DS-149 Fix Modal focus
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/52-modal-usage-persistent.twig
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-modal/src/modal.js
Labels: type: bugfix

#1987 DS-184: Video error message styling doesn't always work
  packages/components/bolt-video/src/_videojs-enhancements.scss
Labels: type: feature
