Repository boltdesignsystem/bolt, pull requests merged in 2020-10, with the labels that each got.

#1990 Update Chromedriver
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#1988 Bolt version generator
  docs-site/.incache
  packages/build-tools/tasks/api-tasks/bolt-versions.js
Labels: type: bugfix

#1985 DS-198 Tabs renderer conversion
  packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
  packages/components/bolt-tabs/__tests__/tabs.js
  packages/components/bolt-tabs/src/TabPanel/index.js
  packages/components/bolt-tabs/src/tabs.js
Labels: type: feature

#1989 DS-231 Update Menu 'core' dependency, JS conventions
  packages/components/bolt-menu/package.json
  packages/components/bolt-menu/src/_menu-item.js
  packages/components/bolt-menu/src/_menu-item.scss
  packages/components/bolt-menu/src/menu.js
  packages/components/bolt-menu/src/menu.scss
Labels: type: feature

#1801 Feature/ie11 deprecation
  .boltrc.js
  docs-site/.boltrc.js
  docs-site/__tests__/pattern-lab.e2e.js
  docs-site/package.json
  docs-site/src/templates/_site-head.twig
  example-integrations/angular/.bolt/.boltrc.js
  example-integrations/angular/.bolt/package.json
  example-integrations/static-html/.bolt/.boltrc.js
  example-integrations/static-html/.bolt/package.json
  packages/base-starter-kit/.boltrc.demo.js
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/demo.html
  packages/base-starter-kit/package.json
  packages/build-tools/__tests__/multi-lang/.boltrc.multi-lang.js
  packages/build-tools/cli.js
  packages/build-tools/create-webpack-config.js
  packages/build-tools/package.json
  packages/build-tools/plugins/postcss-themify/CHANGELOG.md
  packages/build-tools/plugins/postcss-themify/README.md
  packages/build-tools/plugins/postcss-themify/package.json
  packages/build-tools/plugins/postcss-themify/src/helpers/css.util.js
  packages/build-tools/plugins/postcss-themify/src/index.js
  packages/build-tools/utils/config-store.js
  packages/build-tools/utils/config.schema.yml
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
  packages/components/bolt-critical-css-vars/CHANGELOG.md
  packages/components/bolt-critical-css-vars/README.md
  packages/components/bolt-critical-css-vars/index.js
  packages/components/bolt-critical-css-vars/package.json
  packages/components/bolt-critical-path-polyfills/CHANGELOG.md
  packages/components/bolt-critical-path-polyfills/README.md
  packages/components/bolt-critical-path-polyfills/package.json
  packages/components/bolt-critical-path-polyfills/rollup.config.js
  packages/components/bolt-critical-path-polyfills/src/index.js
  packages/components/bolt-nav-priority/nav-priority.scss
  packages/components/bolt-typeahead/__tests__/typeahead.e2e.js
  packages/components/bolt-typeahead/typeahead.scoped.scss
  packages/configs/babel-preset-bolt/index.js
  packages/configs/babel-preset-bolt/package.json
  packages/configs/browserslist-config/.browserlistrc
  packages/configs/browserslist-config/all.js
  packages/configs/browserslist-config/index.js
  packages/configs/browserslist-config/legacy.js
  packages/configs/browserslist-config/package.json
  packages/configs/browserslist-config/test.js
  packages/core-v3.x/styles/01-settings/settings-themes/index.scss
  packages/core-v3.x/styles/02-tools/tools-themes/_tools.themes.scss
  packages/servers/testing-server/index.js
  yarn.lock
Labels: type: feature, version: major

#1997 DS-225: Placeholder Renderer Conversion
  packages/components/bolt-placeholder/placeholder.standalone.js
  packages/components/bolt-placeholder/placeholder.twig
Labels: type: feature

#1998 DS-190 Fix tooltip placement bug
  packages/components/bolt-tooltip/src/tooltip.js
Labels: type: feature

#1996 ACD-286 Academy popover overflow bug
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/cards/_horizontal-card.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/search/_search-results--results-list.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
Labels: type: feature

#2003 DS-178 Fix Blockquote quotes in Safari
  packages/components/bolt-blockquote/src/blockquote.js
  packages/components/bolt-blockquote/src/blockquote.scss
  packages/components/bolt-blockquote/src/blockquote.twig
Labels: type: bugfix

#1984 DS-224: Convert Text to latest renderer
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-carousel/__tests__/carousel.js
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-modal/__tests__/modal.js
  packages/components/bolt-text/__tests__/__snapshots__/text.js.snap
  packages/components/bolt-text/__tests__/text.js
  packages/components/bolt-text/src/text.js
  packages/components/bolt-text/text.schema.js
Labels: type: feature

#2006 Fix composer version conflict on Travis
  docs-site/composer.json
  docs-site/composer.lock
Labels: type: bugfix

#2004 WWW-277: Allow video captions button to show
  packages/components/bolt-video/src/_videojs-enhancements.scss
Labels: type: feature

#2007 Fix failing autolink test
  packages/analytics/autolink/__tests__/autolink.test.js
  packages/analytics/autolink/__tests__/fixtures/test-analytics-config.data.js
Labels: type: bugfix

#2001 DS-128: Tooltip | a11y | Enable ESC key to close and style no-js version
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-tooltip/src/tooltip.twig
Labels: type: feature

#2000 Feature/ds 237 move no shadow demos
  .travis.yml
  docs-site/src/animate-demos.js
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/animate/00-animate-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/animate/05-animate.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/animate/10-animate-build-stages.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/animate/animate-demo-helpers.js
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/00-editor-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/10-editor-simple.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/15-editor-blockquote.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/25-editor-with-two-character-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/misc/-05-drupal-integration.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/00-micro-journey-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/10-character-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/10-character.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/15-character-kitchen-sink.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/20-connection-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/20-connection.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/30-status-dialogue-bar-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/30-status-dialogue-bar.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/35-status-dialogue-bar-kitchen-sink.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/40-icon-group-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/40-icon-group.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/80-micro-journeys-solo.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/90-micro-journeys.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/95-micro-journeys-intersection-observer.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/97-micro-journeys-single-step-with-two-character-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/_editor-wrapper.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/_shadow-dom-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/_micro-journey-demo-1.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/_step-five.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/_step-four.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/_step-one.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/_step-six.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/_step-three.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/_step-two.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/step-1-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/step-2-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/step-3-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/step-4-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/billing-micro-journey-fragments/step-5-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/combos/-92-micro-journey-in-themes.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/combos/-95-in-page-example.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/combos/-99-demo-links.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/svg-animations/00-svg-animations-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/svg-animations/05-svg-animations.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/accordion/00-accordion-no-shadow.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/image/00-image-no-shadow.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/tabs/00-tabs-no-shadow.twig
  packages/components/bolt-accordion/__tests__/accordion.e2e.js
  packages/components/bolt-image/__tests__/bolt-image.e2e.js
  packages/components/bolt-tabs/__tests__/tabs.e2e.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-list.scss
Labels: type: feature

#1986 DS-189 Table Caption
  docs-site/src/pages/pattern-lab/_patterns/40-components/table/35-table-item-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/table/40-table-caption.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/table/999-table-with-web-component.twig
  packages/components/bolt-table/__tests__/__snapshots__/table.js.snap
  packages/components/bolt-table/__tests__/table.js
  packages/components/bolt-table/src/table.js
  packages/components/bolt-table/src/table.scss
  packages/components/bolt-table/src/table.twig
  packages/components/bolt-table/table.schema.js
Labels: type: feature

#1995 DS-236: Add support for images in action blocks (and other cleanup)
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/_info-density.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/00-action-blocks-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/05-action-blocks.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/10-action-blocks-valign-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/15-action-blocks-borderless-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/20-action-blocks-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/25-action-blocks-max-items-per-row.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/30-action-blocks-spacing-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/35-action-blocks-freeform-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/_wip-modal-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/00-d8-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/05-d8-homepage-japanese.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/_event-sponsors-with-action-block.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/_event-sponsors-with-action-block.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/-wip-global-search-mega-nav.twig
  packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
  packages/components/bolt-action-blocks/__tests__/action-blocks.js
  packages/components/bolt-action-blocks/action-blocks.schema.js
  packages/components/bolt-action-blocks/index.scss
  packages/components/bolt-action-blocks/src/_action-blocks-item.twig
  packages/components/bolt-action-blocks/src/action-block.scss
  packages/components/bolt-action-blocks/src/action-block.twig
  packages/components/bolt-action-blocks/src/action-blocks.scss
  packages/components/bolt-action-blocks/src/action-blocks.twig
Labels: type: feature
