Repository boltdesignsystem/bolt, pull requests merged in 2020-07, with the labels that each got.

#1893 Fix: font family for regular table
  packages/components/bolt-table/src/table.scss
Labels: bug

#1899 DS-102: Expand new-component docs
  docs-site/src/pages/docs/50-guides/15-building-a-new-component.md
Labels: docs

#1877 DS-23 | Convert typography and spacing scss vars to CSS custom props
  docs-site/src/pages/pattern-lab/_patterns/02-components/grid/10-grid-start-and-span.twig
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-grid/src/grid.scss
  packages/components/bolt-grid/src/grid.twig
  packages/components/bolt-headline/src/_headline.numbered.scss
  packages/components/bolt-text/src/text.scss
  packages/components/bolt-video/src/video.standalone.js
  packages/core-v3.x/styles/01-settings/settings-spacing/_settings-spacing.scss
  packages/core-v3.x/styles/01-settings/settings-typography/_settings-typography.scss
  packages/core-v3.x/styles/01-settings/settings-z-index/_settings-z-index.scss
  packages/core-v3.x/styles/02-tools/tools-font-family/_tools-font-family.scss
  packages/core-v3.x/styles/02-tools/tools-font-size/_tools-font-size.scss
  packages/core-v3.x/styles/02-tools/tools-font-weight/_tools-font-weight.scss
  packages/core-v3.x/styles/02-tools/tools-shadow/_tools-shadow.scss
  packages/core-v3.x/styles/02-tools/tools-spacing/_tools-spacing.scss
  packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-margin.scss
  packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-padding.scss
  packages/core-v3.x/styles/main.scss
  packages/experimental/micro-journeys/src/interactive-pathways.js
  packages/global/styles/03-generic/_generic-vars-spacing.scss
  packages/global/styles/03-generic/_generic-vars-typography.scss
  packages/global/styles/index.scss
  packages/testing/testing-jest/jest-reporter-vrt.js
Labels: minor

#1906 Fix: text-contrast min ratio and icon background border
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-icon/src/icon.scss
  packages/core-v3.x/styles/01-settings/settings-themes/_helpers.scss
Labels: bug

#1900 BDS-1663: button CSS cleanup
  docs-site/src/pages/pattern-lab/_patterns/02-components/button/15-button-style-variations.twig
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-button/src/_button-settings-and-tools.scss
  packages/components/bolt-button/src/button.scss
Labels: enhancement

#1913 Hotfix: sass warnings drupal build issues
  auto-release.js
  packages/core-v3.x/styles/02-tools/tools-font-family/_tools-font-family.scss
  packages/core-v3.x/styles/02-tools/tools-font-size/_tools-font-size.scss
  packages/core-v3.x/styles/02-tools/tools-font-weight/_tools-font-weight.scss
  packages/core-v3.x/styles/02-tools/tools-spacing/_tools-spacing.scss
  packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-margin.scss
  packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-padding.scss
Labels: hotfix

#1911 Fix Git hooks
  package.json
Labels: bug

#1902 Convert components to use custom props
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-actions.scss
  packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.scss
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
  packages/components/bolt-carousel/src/_carousel-settings-and-tools.scss
  packages/components/bolt-carousel/src/_carousel-slide.scss
  packages/components/bolt-carousel/src/_carousel-slide.slides-per-view.scss
  packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
  packages/components/bolt-carousel/src/_carousel.pagination.scss
  packages/components/bolt-carousel/src/_carousel.scrollbar.scss
  packages/components/bolt-carousel/src/_carousel.scss
  packages/components/bolt-carousel/src/_carousel.stacked.scss
  packages/components/bolt-code-snippet/src/_code-snippet-base.scss
  packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.scss
  packages/components/bolt-image/src/image.scss
  packages/components/bolt-menu/src/_menu-item.scss
  packages/components/bolt-menu/src/menu.scss
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-nav-priority/nav-priority.scss
  packages/components/bolt-navbar/src/navbar.scss
  packages/components/bolt-pagination/src/pagination.scss
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-progress-bar/src/progress-bar.scss
  packages/components/bolt-tabs/src/tabs.scss
  packages/components/bolt-toc/src/_toc-item.scss
  packages/components/bolt-toc/src/toc.scss
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-trigger/src/trigger.scss
  packages/components/bolt-typeahead/typeahead.scoped.scss
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/components/bolt-video/src/video-meta.scss
  packages/components/bolt-video/src/video.scss
Labels: improvement

#1912 Fix Stylelint conflict with Prettier
  packages/configs/stylelint-config/ideal.js
Labels: bug

#1908 DS-106 PR and release workflow housekeeping
  .autorc
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: docs

#1916 DS-106 simplify labels
  .autorc
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: type: feature

#1918 Recreated the vanilla build
  example-integrations/vanilla-webpack-demo/index.html
  example-integrations/vanilla-webpack-demo/index.js
  example-integrations/vanilla-webpack-demo/index.scss
  example-integrations/vanilla-webpack-demo/package.json
  example-integrations/vanilla-webpack-demo/webpack.config.js
Labels: feature

#1919 feature/DS-105: Remove unnecessary package dependency.
  package.json
  yarn.lock
Labels: type: feature

#1922 DS-142: Security Modal: "Unlocking" content with webform
  docs-site/src/pages/pattern-lab/_patterns/02-components/modal/52-modal-usage-persistent.twig
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-modal/modal.schema.js
  packages/components/bolt-modal/src/modal.js
  packages/components/bolt-modal/src/modal.scss
Labels: type: feature

#1923 DS-140: setup "elements" and "layouts" namespaces
  jest.config.js
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/elements/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/elements/bolt-link/__tests__/link.js
  packages/elements/bolt-link/index.js
  packages/elements/bolt-link/index.scss
  packages/elements/bolt-link/link.schema.js
  packages/elements/bolt-link/package.json
  packages/elements/bolt-link/src/_link-macros.twig
  packages/elements/bolt-link/src/link.js
  packages/elements/bolt-link/src/link.scss
  packages/elements/bolt-link/src/link.twig
  packages/layouts/bolt-list/__tests__/__snapshots__/list.js.snap
  packages/layouts/bolt-list/__tests__/list.js
  packages/layouts/bolt-list/index.js
  packages/layouts/bolt-list/index.scss
  packages/layouts/bolt-list/list.schema.js
  packages/layouts/bolt-list/main.js
  packages/layouts/bolt-list/package.json
  packages/layouts/bolt-list/src/_list-item.js
  packages/layouts/bolt-list/src/_list-item.scss
  packages/layouts/bolt-list/src/_list-item.twig
  packages/layouts/bolt-list/src/list.js
  packages/layouts/bolt-list/src/list.scss
  packages/layouts/bolt-list/src/list.twig
Labels: type: feature

#1921 Add "modules" to Bolt Core
  packages/core-v3.x/index.js
  packages/core-v3.x/modules/index.js
  packages/core-v3.x/modules/modules.js
  packages/core-v3.x/modules/src/click-handler.js
Labels: type: feature

#1925 DS-118: remove unused height utils and fix docs
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/20-utility-classes/visually-hidden.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/code-snippet/999-code-snippet-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/-30-dropdown-sticky.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/00-dropdown-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/05-dropdown.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/10-dropdown-center.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/15-dropdown-collapse.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/16-dropdown-collapse-center.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/20-dropdown-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/25-dropdown-long-header.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/30-dropdown-custom-element-demo-collection.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/dropdown/999-dropdown-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/10-tooltip-placement-variations.twig
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/global/styles/07-utilities/_utilities-height.scss
Labels: type: feature

#1927 DS-170: spacing hotfix for Japanese
  packages/base-element/src/lib/decorators/json-schema-props.js
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/global/styles/03-generic/_generic-vars-japanese.scss
  packages/global/styles/index.scss
Labels: version: patch

#1928 DS-169: Fix broken icons in Micro Journeys
  packages/base-element/src/lib/decorators/json-schema-props.js
Labels: type: bugfix

#1929 DS-171 Remove redundant and incorrect schema validation for headline
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-headline/src/_typography.twig
Labels: version: patch
