Repository boltdesignsystem/bolt, pull requests merged in 2020-12, with the labels that each got.

#2027 DS-268: Update copy-to-clipboard WC to latest renderer
  packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
Labels: type: feature

#2032 DS-42 restore schema validation twig dump
  docs-site/.patches/faster-compile-times--add-twig-cache-support--file-system-loader.patch
  docs-site/.patches/faster-compile-times--add-twig-cache-support--pattern-loader.patch
  docs-site/.patches/faster-compile-times--add-twig-cache-support--string-loader.patch
  docs-site/config/config.yml
  docs-site/src/pages/pattern-lab/_patterns/40-components/headline/25-headline-icon-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/icon/10-icon-size-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/05-event-detail.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/10-event-form-example.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/cards/_vertical-card.twig
  packages/components/bolt-background/background.schema.js
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
  packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
  packages/components/bolt-chip-list/__tests__/__snapshots__/chip-list.js.snap
  packages/components/bolt-chip-list/src/_chip-list-macros.twig
  packages/components/bolt-chip-list/src/chip-list.twig
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-share/src/share.twig
  packages/elements/bolt-button/button.schema.js
  packages/elements/bolt-text-link/text-link.schema.js
Labels: type: feature

#2031 DS-243: Remove URL attribute on bolt-text
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/_text-link.twig
  packages/components/bolt-text/src/text.js
  packages/components/bolt-text/src/text.twig
  packages/components/bolt-text/text.schema.js
Labels: type: feature

#2028 DS-248 Update TOC with latest conventions, refactor Waypoint
  packages/components/bolt-toc/src/_toc-item.js
  packages/components/bolt-toc/src/toc.js
  packages/components/bolt-toc/src/waypoint/index.js
  packages/core-v3.x/utils/waypoint/computeOffsetPixels.js
  packages/core-v3.x/utils/waypoint/getBounds.js
  packages/core-v3.x/utils/waypoint/getCurrentPosition.js
  packages/core-v3.x/utils/waypoint/index.js
  packages/core-v3.x/utils/waypoint/parseOffsetAsPercentage.js
  packages/core-v3.x/utils/waypoint/parseOffsetAsPixels.js
Labels: type: feature

#2029 WWW-421: Do not show remaining video time in accordion or tabs
  packages/components/bolt-video/src/video.scss
Labels: type: bugfix

#2039 DS-277 Replace divs with spans in tooltip
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/src/tooltip.twig
Labels: type: bugfix

#2038 Docs: fix element docs typos
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/20-button-with-icon.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/20-text-link-with-icon.twig
Labels: type: docs

#2036 DS-275 Make the background component absolute positioned
  packages/components/bolt-background/src/background.scss
Labels: type: bugfix

#2037 DS-276 Remove -0.5px top/bottom margins from full bleed mixin
  packages/core-v3.x/styles/02-tools/tools-full-bleed/_tools-full-bleed.scss
Labels: type: bugfix

#2035 DS-273 Remove 100% height from icon component
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-icon/src/icon.scss
Labels: type: bugfix

#2040 Docs/lost schema updates
  docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/40-tabs-use-case-tabbed-band.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/combos/-95-in-page-example.twig
  packages/analytics/autolink/__tests__/autolink.test.js
  packages/analytics/autolink/__tests__/fixtures/test-analytics.drupal-config.data.js
  packages/components/bolt-device-viewer/device-viewer.schema.js
  packages/components/bolt-image/image.schema.js
Labels: type: docs

#2042 Hotfix/2.29.3
  packages/analytics/autolink/__tests__/autolink.test.js
  packages/analytics/autolink/__tests__/fixtures/test-analytics.drupal-config.data.js
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-icon/src/icon.scss
Labels: version: patch

#2043 Unable to tap/select first step in microjourneys experiences on mobile
  packages/experimental/micro-journeys/src/interactive-pathway.js
Labels: type: bugfix

#2045 [Docs] add elements to nav and add logic to doc template
  docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
  docs-site/src/templates/_page-header.twig
  docs-site/src/templates/base-template.twig
  docs-site/src/templates/default-redesign.twig
  docs-site/src/templates/default.twig
  docs-site/src/templates/homepage.twig
  docs-site/src/templates/sassdoc.twig
Labels: type: docs

#2033 DS-267: Update card-replacement WC to latest renderer
  packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
  packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-actions.js
  packages/components/bolt-card-replacement/src/card-replacement-body/card-replacement-body.js
  packages/components/bolt-card-replacement/src/card-replacement-link/_card-replacement-link.scss
  packages/components/bolt-card-replacement/src/card-replacement-link/card-replacement-link.js
  packages/components/bolt-card-replacement/src/card-replacement-media/card-replacement-media.js
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.js
Labels: type: feature

#2044 DS-278 add page padding css vars
  packages/global/styles/00-vars/_vars-page-width-and-spacing.scss
  packages/global/styles/index.scss
Labels: type: feature
