Repository boltdesignsystem/bolt, pull requests merged in 2020-08, with the labels that each got.

#1931 DS-41: Make Accordion transparent by default
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
  packages/components/bolt-accordion/src/accordion.scss
Labels: type: feature

#1930 ds 161 calculator pattern pages
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/02-components/form/26-form-element-auto-format.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/00-d8-calculator.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/00-d8-results.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/calculator.scss
  packages/components/bolt-form/src/form.js
  packages/components/bolt-form/src/form.scss
Labels: type: feature

#1933 DS-129: make any component props use --c-bolt instead of --bolt
  packages/components/bolt-carousel/src/_carousel-slide.scss
  packages/components/bolt-carousel/src/_carousel-slide.slides-per-view.scss
  packages/components/bolt-carousel/src/_carousel.scss
  packages/components/bolt-dropdown/dropdown.scss
  packages/components/bolt-nav-indicator/nav-indicator.scss
Labels: type: feature

#1937 COM-93 Fix hero center alignment
  packages/components/bolt-hero/hero.twig
Labels: type: bugfix

#1936 DS-139: fix spacing utils
  packages/core-v3.x/styles/02-tools/tools-spacing/_tools-spacing.scss
  packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-margin.scss
  packages/global/styles/05-objects/objects-grid/_objects-grid.scss
  packages/global/styles/07-utilities/_utilities-spacing.scss
Labels: type: bugfix

#1939 DS-160: calculator quick follows
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/00-d8-calculator.twig
Labels: type: bugfix

#1941 DS-180: fix font styles on button link
  packages/components/bolt-link/src/link.scss
Labels: type: bugfix

#1940 DS-179: update input focus styles to display well in dark themes
  packages/components/bolt-form/src/form.scss
Labels: type: feature

#1935 Feature/ds 134 navbar title
  docs-site/src/pages/pattern-lab/_patterns/02-components/navbar/05-navbar-hide-title.twig
  packages/components/bolt-nav-priority/nav-priority.js
  packages/components/bolt-nav-priority/nav-priority.scss
  packages/components/bolt-navbar/navbar.schema.js
  packages/components/bolt-navbar/src/_navbar-title.twig
  packages/components/bolt-navbar/src/navbar.scss
  packages/components/bolt-navlink/navlink.scss
Labels: type: feature

#1943 DS-160: Calculator JS (v2)
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/00-d8-calculator.twig
  packages/components/bolt-form/src/form.js
  packages/components/bolt-form/src/form.scss
Labels: type: feature

#1942 DS-139: revert spacing functions back to scss
  packages/core-v3.x/styles/02-tools/tools-spacing/_tools-spacing.scss
Labels: type: bugfix

#1945 DS-160: fix reduced motion logic on animation
  docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/calculator.scss
Labels: type: bugfix

#1914 DS-93: convert to use typography css vars (Part 1)
  docs-site/src/components/schema-form/component-explorer.scss
  docs-site/src/components/schema-table/schema-table.scss
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/10-typography/00-typography-overview.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/form/00-form-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/video/65-video-with-external-title.twig
  docs-site/src/templates/_site-head.twig
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
  packages/components/bolt-band/__tests__/__image_snapshots__/band-js-bolt-band-component-full-bleed-usage-1-snap.png
  packages/components/bolt-blockquote/src/blockquote.scss
  packages/components/bolt-button/__tests__/__image_snapshots__/button-js-button-default-bolt-button-with-shadow-dom-renders-1-snap.png
  packages/components/bolt-button/src/_button-settings-and-tools.scss
  packages/components/bolt-button/src/button.scss
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-code-snippet/src/_code-snippet-base.scss
  packages/components/bolt-code-snippet/src/_code-snippet-syntax.scss
  packages/components/bolt-form/src/form.scss
  packages/components/bolt-headline/src/_headline.numbered.scss
  packages/components/bolt-headline/src/_tools.headlines.scss
  packages/components/bolt-headline/src/headline.scss
  packages/components/bolt-li/src/li.scss
  packages/components/bolt-menu/src/_menu-item.scss
  packages/components/bolt-menu/src/menu.scss
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-nav-priority/nav-priority.scss
  packages/components/bolt-navbar/src/navbar.scss
  packages/components/bolt-pagination/src/pagination.scss
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-progress-bar/__tests__/__image_snapshots__/progress-bar-js-progress-bar-component-renders-with-shadow-dom-3-snap.png
  packages/components/bolt-progress-bar/__tests__/__image_snapshots__/progress-bar-js-progress-bar-component-renders-without-shadow-dom-2-snap.png
  packages/components/bolt-progress-bar/src/progress-bar.scss
  packages/components/bolt-tabs/src/tabs.scss
  packages/components/bolt-toc/src/_toc-item.scss
  packages/components/bolt-toc/src/toc.scss
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-trigger/src/trigger.scss
  packages/components/bolt-typeahead/typeahead.scoped.scss
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/components/bolt-video/src/video-meta.scss
  packages/core-v3.x/styles/01-settings/settings-typography/_settings-typography.scss
  packages/core-v3.x/styles/02-tools/tools-font-family/_tools-font-family.scss
  packages/core-v3.x/styles/02-tools/tools-font-size/_tools-font-size.scss
  packages/core-v3.x/styles/02-tools/tools-font-weight/_tools-font-weight.scss
  packages/experimental/micro-journeys/src/status-dialogue-bar.scss
  packages/global/styles/03-generic/_generic-font-stacks.scss
  packages/global/styles/03-generic/_generic-vars-typography.scss
  packages/global/styles/04-elements/_elements-page.scss
Labels: type: feature

#1946 DS-187: Calculator Design Updates
  docs-site/src/assets/images/backgrounds/calculator-landing-shapes-transparent.png
  docs-site/src/assets/images/backgrounds/calculator-landing-shapes.jpg
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/26-form-element-auto-format.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-calculator.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-results.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/calculator.scss
  packages/components/bolt-form/src/form.js
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/svgs/utility/dollar-open.svg
Labels: type: feature

#1953 DS-191: Fix invalid version error
  packages/build-tools/tasks/api-tasks/bolt-versions.js
Labels: type: bugfix

#1956 DS-194: Fix Navbar Jest tests
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-centered-with-4-short-links-6-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-variable-width-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-5-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-4-short-links-6-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-3-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-4-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-5-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-6-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-7-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-8-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-6-lengthy-links-9-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-a-linked-title-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-a-title-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-links-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-without-links-3-snap.png
  packages/components/bolt-navbar/src/navbar.scss
Labels: type: bugfix

#1960 Updated the Chromedriver version to the supported number
  packages/testing/testing-nightwatch/nightwatch.js
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#1957 DS-195: Page Level Information Density Feature
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/00-information-density-system.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/05-comfortable-density.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/10-regular-density.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/15-compact-density.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/_info-density.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/clearfix.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/displays.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/flex.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/height.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/opacity.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/shadow.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/text-align.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/text-decoration.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/visually-hidden.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/z-index.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/_default-page-template.twig
  docs-site/src/templates/base-template.twig
  docs-site/src/templates/homepage.twig
  packages/global/styles/00-vars/_vars-info-density.scss
  packages/global/styles/00-vars/_vars-japanese.scss
  packages/global/styles/00-vars/_vars-spacing.scss
  packages/global/styles/00-vars/_vars-typography.scss
  packages/global/styles/index.scss
  yarn.lock
Labels: type: feature

#1954 DS-182: Convert Blockquote to latest renderer
  docs-site/src/pages/pattern-lab/_patterns/40-components/blockquote/25-blockquote-full-bleed-variation.twig
  packages/base-element/src/Slotify.js
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-blockquote/__tests__/blockquote.js
  packages/components/bolt-blockquote/src/Author/AuthorImage.js
  packages/components/bolt-blockquote/src/Author/AuthorName.js
  packages/components/bolt-blockquote/src/Author/AuthorTitle.js
  packages/components/bolt-blockquote/src/Author/index.js
  packages/components/bolt-blockquote/src/_blockquote-author.js
  packages/components/bolt-blockquote/src/blockquote.js
  packages/components/bolt-blockquote/src/blockquote.scss
  packages/components/bolt-blockquote/src/blockquote.twig
Labels: type: feature

#1962 DS-183: Remove vrt-urls test from Post-deploy step
  .travis.yml
Labels: type: feature

#1961 DS-177: add new brand colors
  docs-site/src/components/component-status/component-status.scss
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/00-color-system.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/05-color-tokens.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/10-theming-system.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/15-text-color-utilities.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/_color-swatch.scss
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/_color-swatch.twig
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/core-v3.x/styles/01-settings/settings-colors/_settings-colors.scss
  packages/global/styles/00-vars/_vars-color.scss
  packages/global/styles/index.scss
Labels: type: feature

#1679 chore(micro-journeys): add schema for one and two character layouts
  packages/experimental/micro-journeys/src/one-character-layout.schema.js
  packages/experimental/micro-journeys/src/two-character-layout.schema.js
Labels: type: docs

#1959 DS-196: Fix Priority Nav bug in Safari
  packages/components/bolt-nav-priority/nav-priority.js
Labels: type: bugfix

#1966 WWW-171 Add workaround for tabs bug in older Edge
  packages/components/bolt-tabs/src/tabs.scss
Labels: type: bugfix

#1967 Debug/release 2.27.0
  auto-release.js
Labels: version: minor
