Repository boltdesignsystem/bolt, pull requests merged in 2020-03, with the labels that each got.

#1755 Fix Animated Gif Support in Bolt
  packages/build-tools/package.json
  packages/build-tools/tasks/image-tasks.js
  packages/components/bolt-image/src/image.twig
  yarn.lock
Labels: enhancement, patch

#1765 Fix / update Popover to better support color theming
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/25-popover-theme-variations.twig
  packages/components/bolt-popover/__tests__/__snapshots__/popover.js.snap
  packages/components/bolt-popover/__tests__/popover.js
  packages/components/bolt-popover/popover.schema.js
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-popover/src/popover.twig
Labels: patch

#1766 Remove 'brand-' prefix from icon in _icon-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/display/_icon-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--in-progress.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--new-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--recommended.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/search/_search-results--results-list.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
Labels: patch

#1763 Feature/tabs deep linking
  docs-site/src/components/pattern-lab-hacks/pattern-lab-hacks.scss
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/45-tabs-deep-linking.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/50-tabs-deep-linking-with-scroll-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t4.twig
  packages/components/bolt-page-header/src/page-header.scss
  packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
  packages/components/bolt-tabs/package.json
  packages/components/bolt-tabs/src/TabPanel/index.js
  packages/components/bolt-tabs/src/TabPanel/tab-panel.twig
  packages/components/bolt-tabs/src/tabs.js
  packages/components/bolt-tabs/tabs.schema.yml
Labels: enhancement

#1764 Add new tertiary variant to the Button component
  packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
  packages/components/bolt-button/button.schema.js
  packages/components/bolt-button/src/_button-settings-and-tools.scss
  packages/components/bolt-button/src/button.scss
  packages/global/styles/06-themes/_themes.all.scss
Labels: enhancement

#1759 Refactor bullet styles, decrease UL spacing
  packages/components/bolt-li/src/li.scss
Labels: enhancement

#1758 Add new "Hero" component; includes variations of image alignment & art direction
  docs-site/src/assets/images/heros/hero-background--indigo.jpg
  docs-site/src/assets/images/heros/hero-background--orange.jpg
  docs-site/src/assets/images/heros/hero-background--teal.jpg
  docs-site/src/assets/images/heros/hero-background--yellow.svg
  docs-site/src/assets/images/heros/hero-foreground--indigo.png
  docs-site/src/assets/images/heros/hero-foreground--orange--animated-gif.gif
  docs-site/src/assets/images/heros/hero-foreground--orange--logo.svg
  docs-site/src/assets/images/heros/hero-foreground--teal.png
  docs-site/src/assets/images/heros/hero-foreground--yellow.png
  docs-site/src/assets/images/heros/responsive-web-design.svg
  docs-site/src/components/pattern-lab-utils/schema-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/00-hero-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/10-hero.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/10-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/20-hero--reverse-order.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/20-hero--reverse-order.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/25-hero--reverse-order--no-image.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/25-hero--reverse-order--no-image.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/30-hero--image-min-width.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/30-hero--image-min-width.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/40-hero--image-align-right.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/40-hero--image-align-right.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/50-hero--image-valign-top.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/50-hero--image-valign-top.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/55-hero--image-valign-bottom.md
  docs-site/src/pages/pattern-lab/_patterns/02-components/hero/55-hero--image-valign-bottom.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-hero/README.md
  packages/components/bolt-hero/hero.schema.js
  packages/components/bolt-hero/hero.twig
  packages/components/bolt-hero/package.json
  packages/core-v3.x/macros.twig
  packages/testing/testing-utils/__tests__/test-utils.test.js
Labels: enhancement

#1756 Allow Blockquote font weight to be customized
  docs-site/src/pages/pattern-lab/_patterns/02-components/blockquote/40-blockquote-weight-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/blockquote/45-blockquote-size-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/blockquote/50-blockquote-web-component.twig
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-blockquote/blockquote.schema.yml
  packages/components/bolt-blockquote/src/blockquote.js
  packages/components/bolt-blockquote/src/blockquote.twig
Labels: enhancement

#1780 Fix/stack component shadow root
  packages/components/bolt-stack/__tests__/__snapshots__/stack.js.snap
  packages/components/bolt-stack/src/stack.js
  packages/components/bolt-stack/src/stack.twig
Labels: minor

#1776 Fix the Doc Site's broken off-canvas nav panel
  docs-site/__tests__/docs-site-nav.e2e.js
  docs-site/src/components/hamburger-button/hamburger-button.twig
  docs-site/src/templates/default.twig
Labels: patch

#1784 Internally upgrade Figure to address slot rendering issues + reduce complexity
  packages/components/bolt-figure/__tests__/__image_snapshots__/figure-js-figure-a-figures-without-any-default-slotted-content-wont-render-a-figcaption-1-snap.png
  packages/components/bolt-figure/__tests__/__image_snapshots__/figure-js-figure-figures-renders-slotted-default-and-media-content-1-snap.png
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-figure/__tests__/figure.js
  packages/components/bolt-figure/package.json
  packages/components/bolt-figure/src/figure.js
Labels: minor

#1778 Fix: update xxsmall font-size to follow conventions
  packages/core-v3.x/styles/01-settings/settings-font-size/_settings-font-size.scss
Labels: enhancement

#1787 Update Headline to support displaying bulleted (numbered) text
  docs-site/src/pages/pattern-lab/_patterns/02-components/headline/40-headline-numbered.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/challenge-details/t2-challenge-detail-page.twig
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-card-deprecated/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-figure/__tests__/__image_snapshots__/figure-js-figure-a-figures-without-any-default-slotted-content-wont-render-a-figcaption-1-snap.png
  packages/components/bolt-figure/__tests__/__image_snapshots__/figure-js-figure-figures-renders-slotted-default-and-media-content-1-snap.png
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-headline/headline.schema.yml
  packages/components/bolt-headline/src/_headline.numbered.scss
  packages/components/bolt-headline/src/_tools.headlines.scss
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-headline/src/headline.scss
  packages/components/bolt-headline/src/scss/_components.eyebrow.scss
  packages/components/bolt-headline/src/scss/_components.headline.scss
  packages/components/bolt-headline/src/scss/_components.subheadline.scss
  packages/components/bolt-sticky/__tests__/__snapshots__/sticky.js.snap
  packages/core-v3.x/styles/02-tools/tools-font-size/_tools-font-size.scss
  packages/core-v3.x/styles/02-tools/tools-font-weight/_tools-font-weight.scss
Labels: patch

#1781 Add new offset-related props to the TOC component
  docs-site/src/pages/pattern-lab/_patterns/02-components/toc/30-toc-use-case-sticky-and-scroll-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-default-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/topic-details/t2-topic-detail-page.twig
  packages/components/bolt-page-header/src/page-header.scss
  packages/components/bolt-page-header/src/page-header.twig
  packages/components/bolt-toc/package.json
  packages/components/bolt-toc/src/_toc-item.js
  packages/components/bolt-toc/src/toc.js
  packages/components/bolt-toc/src/toc.scss
  packages/components/bolt-toc/toc.schema.js
Labels: enhancement

#1782 Update Popover to mirror it's internal state with the original no-JS / SSR state
  docs-site/src/pages/pattern-lab/_patterns/02-components/popover/25-popover-theme-variations.twig
  package.json
  packages/components/bolt-popover/__tests__/popover.e2e.js
  packages/components/bolt-popover/src/popover.js
  packages/testing/testing-nightwatch/nightwatch.js
Labels: Ready To Merge, enhancement

#1768 Update 5 of Bolt's SVG icon assets to have a more consistent stroke weights
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--new-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--recommended.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/search/_search-results--results-list.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/completed-training/completed-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/svgs/brand/brand-atom.svg
  packages/components/bolt-icons/src/svgs/brand/brand-meteor.svg
  packages/components/bolt-icons/src/svgs/brand/brand-molecule.svg
  packages/components/bolt-icons/src/svgs/brand/brand-orbit.svg
  packages/components/bolt-icons/src/svgs/brand/brand-rocket.svg
  packages/components/bolt-icons/src/svgs/brand/brand-satelite.svg
  packages/components/bolt-icons/src/svgs/brand/brand-triangle.svg
  packages/components/bolt-icons/src/svgs/product/services/launchpad.svg
Labels: enhancement

#1783 feat: replace `xxsmall` with `xsmall` in Blueprints
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/training/_completed-training-item.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/certification-exam/certification-exam-page.twig
Labels: improvement, quick-review

#1793 Hotfix: Fix for Composer Install Issues on Travis
  .travis.yml
  docs-site/composer.json
  docs-site/composer.lock
  packages/twig-integration/twig-extensions-compat/composer.json
  packages/twig-integration/twig-extensions-compat/composer.lock
  packages/twig-integration/twig-extensions-shared/composer.lock
  packages/twig-integration/twig-renderer/composer.json
  packages/twig-integration/twig-renderer/composer.lock
Labels: hotfix

#1794 Hotfix: Headline / Blockquote Text Alignment Regression Fix
  .travis.yml
  docs-site/src/pages/pattern-lab/_patterns/02-components/headline/25-headline-icon-variations.twig
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-align-variations-center-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-align-variations-center-2-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-align-variations-left-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-align-variations-left-2-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-align-variations-right-1-snap.png
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-align-variations-right-2-snap.png
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-blockquote/__tests__/blockquote.js
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-card-deprecated/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-headline/src/_tools.headlines.scss
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-modal/__tests__/__image_snapshots__/__diff_output__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-w-o-shadow-dom-renders-1-diff.png
  packages/components/bolt-modal/__tests__/__image_snapshots__/__diff_output__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-1-diff.png
  packages/components/bolt-sticky/__tests__/__snapshots__/sticky.js.snap
Labels: hotfix

#1798 Feature/academy blueprint updates
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/display/_icon-banner.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/module-list/_module-quiz-item.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/module-list/_module-topic-item.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/search/_search-results--results-list.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.twig
Labels: minor, quick-review

#1799 fix: Rework logic for grid ordering in hero component
  packages/components/bolt-hero/hero.twig
Labels: patch

#1789 BDS-1573 action element schema
  docs-site/src/pages/pattern-lab/_patterns/04-pages/00-full-page-theming/_full-page-theming.twig
  packages/base-element/element.schemas.js
  packages/base-element/package.json
  packages/base-element/src/BoltActionElement.schema.js
  packages/components/bolt-button/button.schema.js
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-link/link.schema.js
  packages/components/bolt-link/link.schema.yml
  packages/components/bolt-link/package.json
  packages/components/bolt-link/src/link.js
  packages/experimental/editor/src/setup-bolt.js
Labels: enhancement

#1803 Fix/toc scroll position fixes
  packages/components/bolt-toc/src/_toc-item.js
  packages/components/bolt-toc/src/toc.js
Labels: hotfix

#1802 Speed up Pattern Lab compile times by 3x; speed up Travis
  docs-site/.patches/faster-compile-times--add-twig-cache-support--file-system-loader.patch
  docs-site/.patches/faster-compile-times--add-twig-cache-support--pattern-loader.patch
  docs-site/.patches/faster-compile-times--add-twig-cache-support--string-loader.patch
  docs-site/.patches/faster-compile-times--docs--composer.json.patch
  docs-site/.patches/faster-compile-times--docs--documentation-rule.patch
  docs-site/.patches/faster-compile-times--docs--documentation.patch
  docs-site/.patches/faster-compile-times--ignore-more-files.patch
  docs-site/composer.json
  docs-site/composer.lock
  docs-site/composer.patches.json
  docs-site/config/config.yml
  packages/twig-integration/twig-extensions-shared/src/TwigExtensions/Faker.php
  packages/twig-integration/twig-renderer/SetupTwigRenderer.php
  packages/twig-integration/twig-renderer/twig-renderer.js
Labels: enhancement, quick-review

#1804 Faster Nightwatch.js tests on Travis CI (~3.5 mins faster!)
  .travis.yml
  packages/servers/default-server/index.js
  packages/servers/default-server/server.js
  packages/testing/testing-nightwatch/nightwatch.local.js
Labels: enhancement, quick-review

#1785 Typography | Docs | Map typography tokens to JSON data
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/05-spacing/00-spacing-overview.twig
  docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/10-typography/00-typography-overview.twig
  packages/build-tools/create-webpack-config.js
  packages/build-tools/package.json
  packages/core-v3.x/styles/01-settings/settings-font-family/_settings-font-family.scss
  packages/core-v3.x/styles/01-settings/settings-font-size/_settings-font-size.scss
  packages/global/styles/04-elements/_elements-page.scss
  yarn.lock
Labels: docs, enhancement
