Repository boltdesignsystem/bolt, pull requests merged in 2020-04, with the labels that each got.

#1796 Add visual regression test to Blockquote to check that quote styles render correctly
  packages/components/bolt-blockquote/__tests__/__image_snapshots__/blockquote-js-bolt-blockquote-component-bolt-blockquote-initially-rendering-via-twig-display-quotes-correctly-1-snap.png
  packages/components/bolt-blockquote/__tests__/blockquote.js
Labels: Ready For Review, patch

#1808 fix: Remove join filters and related workarounds in replacement card
  packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
Labels: bug

#1815 Re-enable branch and commit-specific now.sh deploy preview URLs on Github
  .travis.yml
  scripts/get-branch-alias.js
Labels: enhancement, quick-review

#1806 Fix List wrapping bug
  packages/components/bolt-list/src/list.scss
Labels: bug

#1810 fix: Allow card url attributes to be empty
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
Labels: bug

#1813 Feat: Update Mission Modal Blueprint w/ new (WIP) Rating component
  docs-site/src/index.js
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/00-assets/images/mission-test-badge-example.svg
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/00-assets/images/orion-nebula.jpg
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal--after-submit.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal--before-submit.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal--rating.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal--return-to-mission.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/01-t1-mission-landing--test-with-modal.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/01-t1-mission-landing--test-with-modal.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/01-t1-mission-landing--test-with-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/02-t1-mission-landing--test-with-modal--after-submit.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/02-t1-mission-landing--test-with-modal--after-submit.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/02-t1-mission-landing--test-with-modal--after-submit.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/t1-mission-landing--test-with-modal.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/index.scss
  packages/components/bolt-card-replacement/src/card-replacement-background/_card-replacement-background.scss
  packages/components/bolt-toolbar/toolbar.scss
  packages/components/bolt-toolbar/toolbar.twig
Labels: enhancement

#1809 Fix: accordion open prop typo in web component demo
  docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/999-accordion-web-component.twig
Labels: docs, minor

#1820 Create a new component documentation update
  docs-site/src/pages/docs/50-guides/15-building-a-new-component.md
Labels: docs, minor

#1819 IE11 deprecation testing updates
  docs-site/__tests__/pattern-lab.e2e.js
  packages/components/bolt-typeahead/__tests__/typeahead.e2e.js
Labels: internal, minor

#1822 Consolidate + update the Travis CI commands for handling now.sh deployment URLs in the Github UI
  .travis.yml
  package.json
  yarn.lock
Labels: internal, minor

#1824 Update Github Deployment Status logic so deployment env names are tied to a specific branch
  .travis.yml
  scripts/get-git-sha.js
Labels: minor

#1807 Action Blocks | FE | Add spacing prop
  docs-site/src/pages/pattern-lab/_patterns/02-components/action-blocks/30-action-blocks-spacing-variations.twig
  packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
  packages/components/bolt-action-blocks/__tests__/action-blocks.js
  packages/components/bolt-action-blocks/action-blocks.schema.yml
  packages/components/bolt-action-blocks/src/_action-blocks-item.scss
  packages/components/bolt-action-blocks/src/action-blocks.scss
  packages/components/bolt-action-blocks/src/action-blocks.twig
Labels: new feature

#1825 hotfix: address Headline layout / alignment regression when using <span> tags
  packages/components/bolt-headline/__tests__/__image_snapshots__/headline-js-bolt-headline-component-span-based-headlines-do-not-overlap-with-neighboring-p-tags-3-snap.png
  packages/components/bolt-headline/__tests__/__image_snapshots__/headline-js-bolt-headline-component-span-based-headlines-horizontally-align-properly-3-snap.png
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-headline/__tests__/headline.js
  packages/components/bolt-headline/src/_tools.headlines.scss
Labels: hotfix

#1797 Add spread support to BoltElement + demo usage in Link and Button components
  docs-site/src/pages/pattern-lab/_patterns/02-components/link/30-link-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/link/35-link-with-web-component-html-attributes.twig
  packages/base-element/index.js
  packages/base-element/package.json
  packages/base-element/src/BoltActionElement.js
  packages/base-element/src/BoltActionElement.schema.js
  packages/base-element/src/lib/decorators.js
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-button/src/button.js
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/src/link.js
  yarn.lock
Labels: improvement

#1818 Feature/auto-prop support
  packages/base-element/package.json
  packages/base-element/src/BoltElement.js
  packages/base-element/src/lib/decorators.js
  packages/components/bolt-menu/src/menu.js
  yarn.lock
Labels: new feature

#1826 Feature/update component generator
  packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/__snapshots__/component-generator.js.snap
  packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js
  packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js.snap
  packages/generators/yeoman-create-component/generators/component/__tests__/component-generator.js
  packages/generators/yeoman-create-component/generators/component/index.js
  packages/generators/yeoman-create-component/generators/component/templates/README.md
  packages/generators/yeoman-create-component/generators/component/templates/component.html.twig
  packages/generators/yeoman-create-component/generators/component/templates/component.js
  packages/generators/yeoman-create-component/generators/component/templates/component.schema.js
  packages/generators/yeoman-create-component/generators/component/templates/component.schema.yml
  packages/generators/yeoman-create-component/generators/component/templates/component.scss
  packages/generators/yeoman-create-component/generators/component/templates/component.test.js
  packages/generators/yeoman-create-component/generators/component/templates/index.component.js
  packages/generators/yeoman-create-component/generators/component/templates/package.json
  packages/generators/yeoman-create-component/generators/component/templates/package.tpl.json
Labels: enhancement, minor

#1828 Fix: add proper attributes to bolt-ol and bolt-ul for accessibility
  packages/components/bolt-li/src/li.js
  packages/components/bolt-li/src/li.scss
  packages/components/bolt-li/src/li.twig
  packages/components/bolt-ol/__tests__/__snapshots__/ol.js.snap
  packages/components/bolt-ol/src/ol.js
  packages/components/bolt-ol/src/ol.twig
  packages/components/bolt-ul/__tests__/__snapshots__/ul.js.snap
  packages/components/bolt-ul/src/ul.js
  packages/components/bolt-ul/src/ul.twig
Labels: minor

#1849 Add "locked" Badge to Blueprints
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/_badge.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/index.scss
Labels: new feature

#1827 New Progress Bar component, supporting demos, and updated Blueprints to use the new component
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/00-progress-bar-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/05-progress-bar-basic-usage.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/10-progress-bar-value-format.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/15-progress-bar-max.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/20-progress-bar-animated.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/25-progress-bar-theming.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/30-progress-bar-in-toolbar.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/35-progress-bar-use-case-stepper.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/40-progress-bar-use-case-loading-animation.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/progress-bar/999-progress-bar-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/toolbar/_toolbar.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/01-t1-mission-landing--test-with-modal.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/02-t1-mission-landing--test-with-modal--after-submit.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test/t1-mission-landing--test.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.json
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.json
  packages/base-element/src/lib/decorators.js
  packages/base-starter-kit/.boltrc.js
  packages/components/bolt-progress-bar/README.md
  packages/components/bolt-progress-bar/__tests__/__image_snapshots__/progress-bar-js-progress-bar-component-renders-with-shadow-dom-3-snap.png
  packages/components/bolt-progress-bar/__tests__/__image_snapshots__/progress-bar-js-progress-bar-component-renders-without-shadow-dom-2-snap.png
  packages/components/bolt-progress-bar/__tests__/__snapshots__/progress-bar.js.snap
  packages/components/bolt-progress-bar/__tests__/progress-bar.js
  packages/components/bolt-progress-bar/index.js
  packages/components/bolt-progress-bar/index.scss
  packages/components/bolt-progress-bar/package.json
  packages/components/bolt-progress-bar/progress-bar.schema.js
  packages/components/bolt-progress-bar/src/progress-bar.js
  packages/components/bolt-progress-bar/src/progress-bar.scss
  packages/components/bolt-progress-bar/src/progress-bar.twig
  yarn.lock
Labels: minor, new component

#1830 Truncate Chip List
  docs-site/src/pages/pattern-lab/_patterns/02-components/chip/20-chip-icon-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/chips-list/15-chip-list-truncate.twig
  docs-site/src/pages/pattern-lab/_patterns/02-components/chips-list/20-chip-list-collapsible.twig
  packages/components/bolt-chip-list/__tests__/__snapshots__/chip-list.js.snap
  packages/components/bolt-chip-list/__tests__/chip-list.js
  packages/components/bolt-chip-list/chip-list.schema.yml
  packages/components/bolt-chip-list/index.js
  packages/components/bolt-chip-list/index.scss
  packages/components/bolt-chip-list/package.json
  packages/components/bolt-chip-list/src/_chip-list-macros.twig
  packages/components/bolt-chip-list/src/chip-list.js
  packages/components/bolt-chip-list/src/chip-list.scss
  packages/components/bolt-chip-list/src/chip-list.twig
  packages/components/bolt-chip/__tests__/__snapshots__/chip.js.snap
  packages/components/bolt-chip/__tests__/chip.js
  packages/components/bolt-chip/chip.schema.yml
  packages/components/bolt-chip/src/chip.js
  packages/components/bolt-chip/src/chip.scss
  packages/components/bolt-chip/src/chip.twig
  packages/components/bolt-list/src/_list-item.twig
Labels: minor, new feature

#1823 Fix: add only to twig includes
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/cards/_horizontal-card.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/cards/_vertical-card.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/navigation/_nav--search.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/band/_band--request-feedback.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--in-progress.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--new-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--recommended.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/heros/dashboard-page-hero/dashboard-page-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/landing-page/_landing-page-inner-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal--rating.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/search/_form--search-filter.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/search/_search-bar.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/toolbar/_toolbar.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-default-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/04-templates/_blueprints-landing-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/completed-training/completed-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-missions/dashboard--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/certification-exam/certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/01-t1-mission-landing--test-with-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing--test-with-modal/02-t1-mission-landing--test-with-modal--after-submit.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/_mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/topic-details/t2-topic-detail-page.twig
  packages/components/bolt-chip-list/package.json
Labels: hotfix

#1841 Create new Favorited Training blueprint
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_add.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_favorite.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_remove.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_share.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_toolbar-button.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/forms/toolbar-buttons/_unfavorite.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/user-actions/_toolbar-actions.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--my-favorite-training.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band.twig
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-favorite-training/dashboard--my-favorite-training.md
  docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-favorite-training/dashboard--my-favorite-training.twig
Labels: new feature

#1850 hotfix: update Chip List JavaScript to handle when the `.c-bolt-chip-list__input` element doesn't exist
  packages/components/bolt-chip-list/src/chip-list.js
  packages/components/bolt-chip-list/src/chip-list.twig
Labels: hotfix

#1845 Misc internal perf-related updates: <script> tag location + removal of unnecessary critical path CSS / JS
  .boltrc.js
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/templates/_site-footer.twig
  docs-site/src/templates/_site-head.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
Labels: minor, quick-review, web performance

#1843 feat: manually cherry pick ajv replacement updates
  packages/base-starter-kit/package.json
  packages/components/bolt-link/package.json
  packages/components/bolt-list/src/list.js
  packages/core-v3.x/package.json
  packages/core-v3.x/renderers/bolt-base.js
  yarn.lock
Labels: minor, web performance

#1844 Migrate Carousel to render using LitElement (BoltElement)
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-5-snap.png
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-carousel/index.scss
  packages/components/bolt-carousel/src/carousel.js
Labels: minor, quick-review, web performance

#1842 Add `<ssr-keep>` + better hydration support to `@bolt/element`
  packages/analytics/autolink/__tests__/autolink.test.js
  packages/base-element/src/BoltElement.js
  packages/components/bolt-band/__tests__/band.js
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-nav-controls-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-outer-nav-controls-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-3-slide-bolt-carousel-renders-w-variable-auto-slide-per-view-7-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-2-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-3-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-4-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-5-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-6-snap.png
  packages/components/bolt-carousel/__tests__/__image_snapshots__/carousel-js-carousel-basic-7-slide-bolt-carousel-renders-7-snap.png
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-carousel/__tests__/carousel.js
  packages/components/bolt-modal/__tests__/__image_snapshots__/__diff_output__/modal-js-bolt-modal-component-long-content-usage-bolt-modal-with-shadow-dom-renders-1-diff.png
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-modal/__tests__/modal.js
  packages/components/bolt-ratio/__tests__/ratio.js
  packages/testing/testing-helpers/index.js
  packages/testing/testing-helpers/package.json
  yarn.lock
Labels: minor, quick-review, web performance

#1821 Add new Lazy Queue package to allow components to defer loading
  packages/base-lazy-queue/idle-queue.mjs
  packages/base-lazy-queue/index.mjs
  packages/base-lazy-queue/lazy-definition-observer.mjs
  packages/base-lazy-queue/package.json
  packages/components/bolt-chip/index.js
  packages/components/bolt-chip/package.json
  packages/components/bolt-video/index.js
  packages/components/bolt-video/package.json
  yarn.lock
Labels: minor, web performance
