Repository boltdesignsystem/bolt, pull requests merged in 2020-11, with the labels that each got.

#1999 DS-156 add text link element and doc page template
  docs-site/src/components/pattern-lab-utils/docs.twig
  docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
  docs-site/src/components/pattern-lab-utils/schema-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/.gitkeep
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/text-link/00-text-link-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/text-link/05-text-link.twig
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/text-link/10-text-link-with-icon.twig
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/text-link/15-text-link-reversed-underline.twig
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/text-link/20-text-link-button.twig
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/text-link/25-text-link-attributes.twig
  docs-site/src/pages/pattern-lab/_patterns/_20-elements/text-link/30-text-link-expand-click-target.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/core-v3.x/styles/01-settings/settings-global/_settings-global.scss
  packages/core-v3.x/styles/02-tools/tools-button-reset/_tools-button-reset.scss
  packages/core-v3.x/styles/02-tools/tools-inline-icon-wrapper/_tools-inline-icon-wrapper.scss
  packages/core-v3.x/styles/02-tools/tools-text-link/_tools-text-link.scss
  packages/core-v3.x/styles/main.scss
  packages/elements/bolt-link/CHANGELOG.md
  packages/elements/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/elements/bolt-link/index.js
  packages/elements/bolt-link/index.scss
  packages/elements/bolt-link/link.schema.js
  packages/elements/bolt-link/src/_link-macros.twig
  packages/elements/bolt-link/src/link.js
  packages/elements/bolt-link/src/link.scss
  packages/elements/bolt-link/src/link.twig
  packages/elements/bolt-text-link/CHANGELOG.md
  packages/elements/bolt-text-link/__tests__/__snapshots__/text-link.js.snap
  packages/elements/bolt-text-link/__tests__/text-link.js
  packages/elements/bolt-text-link/index.scss
  packages/elements/bolt-text-link/package.json
  packages/elements/bolt-text-link/src/text-link.scss
  packages/elements/bolt-text-link/src/text-link.twig
  packages/elements/bolt-text-link/text-link.schema.js
  packages/global/styles/00-vars/_vars-interactive-states.scss
  packages/global/styles/00-vars/_vars-transition.scss
  packages/global/styles/04-elements/_elements-anchor-and-button.scss
  packages/global/styles/04-elements/_elements-links.scss
  packages/global/styles/index.scss
Labels: type: feature

#2009 DS-250 remove text underline and fix subpixel border issue
  docs-site/src/components/pattern-lab-utils/docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/15-action-blocks-borderless-variations.twig
  packages/components/bolt-action-blocks/src/_action-blocks-settings-and-tools.scss
  packages/components/bolt-action-blocks/src/action-block.scss
  packages/components/bolt-action-blocks/src/action-blocks.scss
Labels: type: feature

#2010 DS-251 fix banner link color
  docs-site/src/pages/pattern-lab/_patterns/40-components/banner/20-banner-use-case-links.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/banner/20-banner-use-case-status-report.twig
  packages/components/bolt-banner/src/banner.scss
Labels: type: bugfix

#2012 ACD-365: Update Academy dashboard
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/cards/_vertical-card.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
Labels: type: feature

#2013 DS-253 Fix invisible Accordion content
  packages/components/bolt-accordion/src/accordion.js
  packages/components/bolt-band/src/band.js
Labels: type: bugfix

#2014 DS-255: Hero band should support vertical/horizontal alignment for the background
  docs-site/.incache
  docs-site/src/pages/pattern-lab/_patterns/40-components/hero/60-hero--bg-valign.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/hero/60-hero--bg-valign.twig
  packages/components/bolt-hero/hero.schema.js
  packages/components/bolt-hero/hero.twig
Labels: type: feature

#2016 DS-258 fix typos and bad code in Stack component
  packages/components/bolt-stack/src/stack.scss
  packages/components/bolt-stack/src/stack.twig
  packages/components/bolt-stack/stack.schema.js
Labels: type: bugfix

#2017 WWW-384 Play icon on video players floating separately from buttons on Edge v42 (Pega Edge)
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/core-v3.x/styles/02-tools/tools-ms-edge/_tools-ms-edge.scss
  packages/core-v3.x/styles/main.scss
Labels: type: feature

#2011 WWW-105 PatternLab video clean up
  docs-site/.incache
  docs-site/__tests__/__snapshots__/vrt-urls.js.snap
  docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card-replacement/35-card-replacement-with-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card-replacement/999-card-replacement-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/25-carousel-basic-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/device-viewer/25-device-viewer-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/figure/10-figure-media-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/30-tabs-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-05-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-10-video-hide-meta-title-and-duration.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-15-video-hide-meta-title-only.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-20-video-hide-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-25-video-with-external-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-35-video-with-inline-script-and-external-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-50-video-with-email-share.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-55-video-with-custom-share-text.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-60-video-with-cue-points.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-65-video-with-external-title.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-70-video-with-default-error-message.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-71-video-with-custom-error-message.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/00-video-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/00-video-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/_video-with-inline-script-and-external-controls-as-background.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/autoplay/-autoplay-and-loop-hide-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/autoplay/-autoplay-and-loop.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/autoplay/-autoplay.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/plugins/default-plugins.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/plugins/disabled-plugins.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/plugins/enabled-plugins.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/plugins/external-plugins-script.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/tests/-test-brightcove-video-player.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/tests/-test-two-cue-point-instances.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video/tests/-test-video-injection.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t4.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/50-d8-careers/00-careers-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
  packages/build-tools/create-webpack-config.js
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
  packages/components/bolt-tabs/__tests__/tabs.e2e.js
  packages/components/bolt-video/__tests__/__snapshots__/video.js.snap
  packages/components/bolt-video/__tests__/bolt-video.e2e.js
  packages/components/bolt-video/__tests__/video.js
  packages/components/bolt-video/brightcove.scss
  packages/components/bolt-video/brightcove/_video.scss
  packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
Labels: type: feature

#2015 DS-157 add button element
  docs-site/__tests__/__snapshots__/vrt-urls.js.snap
  docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/00-button-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/05-button.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/10-button-link.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/15-button-attributes.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/20-button-with-icon.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/25-button-with-icon-only.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/30-button-hierarchy.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/35-button-size.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/40-button-border-radius.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/45-button-display.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/50-button-upload.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/00-text-link-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/05-text-link.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/10-text-link-button.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/15-text-link-attributes.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/20-text-link-with-icon.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/25-text-link-reversed-underline.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/30-text-link-expand-click-target.twig
  packages/base-starter-kit/.boltrc.js
  packages/core-v3.x/styles/02-tools/tools-text-link/_tools-text-link.scss
  packages/elements/bolt-button/CHANGELOG.md
  packages/elements/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/elements/bolt-button/__tests__/button.js
  packages/elements/bolt-button/button.schema.js
  packages/elements/bolt-button/index.scss
  packages/elements/bolt-button/package.json
  packages/elements/bolt-button/src/button.scss
  packages/elements/bolt-button/src/button.twig
  packages/elements/bolt-text-link/src/text-link.scss
  packages/elements/bolt-text-link/src/text-link.twig
  packages/elements/bolt-text-link/text-link.schema.js
  packages/global/styles/00-vars/_vars-interactive-states.scss
  packages/global/styles/00-vars/_vars-mode.scss
  packages/global/styles/04-elements/_elements-anchor-and-button.scss
  packages/global/styles/index.scss
Labels: type: feature

#2019 DS-264: Add srcset support for hero component
  packages/components/bolt-hero/hero.schema.js
  packages/components/bolt-hero/hero.twig
Labels: type: feature

#2022 WWW-384: Fix responsiveness on Edge 42/44
  packages/components/bolt-video/src/_videojs-enhancements.scss
Labels: type: bugfix

#2021 DS-265 Bolt-card action buttons fix
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-icon/src/icon.scss
  packages/components/bolt-icons/__tests__/__image_snapshots__/icons-js-bolt-icon-component-additional-bolt-icon-with-shadow-dom-renders-2-snap.png
  packages/components/bolt-icons/__tests__/__image_snapshots__/icons-js-bolt-icon-component-default-bolt-icon-with-shadow-dom-renders-2-snap.png
  packages/components/bolt-logo/__tests__/__image_snapshots__/logo-js-logo-default-bolt-logo-renders-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-a-linked-title-2-snap.png
  packages/components/bolt-ratio/__tests__/__image_snapshots__/ratio-js-bolt-ratio-component-bolt-ratio-with-html-5-video-renders-2-snap.png
  packages/components/bolt-table/__tests__/__image_snapshots__/table-js-bolt-table-component-web-component-rendered-table-with-html-comments-1-snap.png
Labels: type: bugfix

#2024 Hotfix/2.29.1
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-icon/src/icon.scss
  packages/components/bolt-icons/__tests__/__image_snapshots__/icons-js-bolt-icon-component-additional-bolt-icon-with-shadow-dom-renders-2-snap.png
  packages/components/bolt-icons/__tests__/__image_snapshots__/icons-js-bolt-icon-component-default-bolt-icon-with-shadow-dom-renders-2-snap.png
  packages/components/bolt-logo/__tests__/__image_snapshots__/logo-js-logo-default-bolt-logo-renders-2-snap.png
  packages/components/bolt-navbar/__tests__/__image_snapshots__/navbar-js-bolt-navbar-component-bolt-navbar-with-a-linked-title-2-snap.png
  packages/components/bolt-ratio/__tests__/__image_snapshots__/ratio-js-bolt-ratio-component-bolt-ratio-with-html-5-video-renders-2-snap.png
  packages/components/bolt-table/__tests__/__image_snapshots__/table-js-bolt-table-component-web-component-rendered-table-with-html-comments-1-snap.png
  packages/components/bolt-video/src/_videojs-enhancements.scss
Labels: version: patch

#2026 Fix play icon
  packages/components/bolt-video/src/_videojs-enhancements.scss
Labels: type: bugfix, version: patch

#2023 DS-211: Disable canary releases when merging to master
  .travis.yml
  auto-release.js
Labels: type: feature

#2025 DS-245: Links to external sites in Teaser headlines not opening in new tab
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/10-teaser-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/15-teaser-with headline-link.twig
  packages/components/bolt-headline/headline.schema.js
  packages/components/bolt-headline/src/_typography.twig
Labels: type: feature
