Repository boltdesignsystem/bolt, pull requests merged in 2021-11, with the labels that each got.

#2371 Fix missing icons
  packages/components/bolt-code-snippet/src/code-snippet.js
  packages/components/bolt-typeahead/typeahead.js
Labels: type: bugfix

#2372 Fixed a markup error on the teaser component
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
Labels: type: feature

#2374 Hotfix v4.6.2
  docs-site/src/pages/pattern-lab/_patterns/999-tests/code-snippet/15-code-snippet-table.twig
  packages/components/bolt-code-snippet/index.js
  packages/components/bolt-code-snippet/src/code-snippet.js
  packages/components/bolt-table/package.json
  packages/components/bolt-table/src/table.js
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
Labels: version: patch

#2301 DS-565 My Quick Links 2.0: Manage My Quick Links page (UX Mockup)
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/quick-links-styles.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/quick-links.twig
  packages/elements/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/elements/bolt-icon/icon.schema.json
  packages/elements/bolt-icon/src/icons/minus-circle.twig
  packages/elements/bolt-icon/src/icons/minus-solid.twig
  packages/elements/bolt-icon/src/icons/minus.twig
  packages/elements/bolt-icon/src/svgs/minus-circle.svg
  packages/elements/bolt-icon/src/svgs/minus-solid.svg
  packages/elements/bolt-icon/src/svgs/minus.svg
Labels: type: feature

#2376 DS-344: [Remove] Bolt Video Component
  .travis.yml
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/35-card-replacement-with-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/card-replacement-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-05-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-10-video-hide-meta-title-and-duration.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-15-video-hide-meta-title-only.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-20-video-hide-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-25-video-with-external-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-35-video-with-inline-script-and-external-controls.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-50-video-with-email-share.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-55-video-with-custom-share-text.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-60-video-with-cue-points.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-65-video-with-external-title.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-70-video-with-default-error-message.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/-71-video-with-custom-error-message.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-deprecated/00-video-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/_product-t3-extra-videos.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/_product-t3.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-card-replacement/card-replacement.schema.js
  packages/components/bolt-card-replacement/package.json
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
  packages/components/bolt-video/CHANGELOG.md
  packages/components/bolt-video/README.md
  packages/components/bolt-video/TESTING.md
  packages/components/bolt-video/brightcove.scss
  packages/components/bolt-video/index.js
  packages/components/bolt-video/index.scss
  packages/components/bolt-video/main.js
  packages/components/bolt-video/package.json
  packages/components/bolt-video/plugins/cue-points.js
  packages/components/bolt-video/plugins/email-plugin.js
  packages/components/bolt-video/plugins/index.js
  packages/components/bolt-video/plugins/playback-plugin.js
  packages/components/bolt-video/plugins/social-plugin.js
  packages/components/bolt-video/src/_video-inline-script.twig
  packages/components/bolt-video/src/_video-tag.twig
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/components/bolt-video/src/video-meta.js
  packages/components/bolt-video/src/video-meta.scss
  packages/components/bolt-video/src/video.js
  packages/components/bolt-video/src/video.scss
  packages/components/bolt-video/src/video.standalone.js
  packages/components/bolt-video/src/video.twig
  packages/components/bolt-video/utils/dataset-to-object.js
  packages/components/bolt-video/utils/format-video-duration.js
  packages/components/bolt-video/utils/get-sub-array.js
  packages/components/bolt-video/utils/index.js
  packages/components/bolt-video/video.schema.js
  packages/twig-integration/twig-extensions-shared/src/TwigFunctions.php
  yarn.lock
Labels: type: feature

#2364 DS-395 [Remove] "bolt-theme()" Deprecated
  docs-site/src/components/radio-switch/package.json
  docs-site/src/components/radio-switch/radio-switch.js
  docs-site/src/components/radio-switch/radio-switch.scss
  docs-site/src/components/shadow-toggle/package.json
  docs-site/src/components/shadow-toggle/shadow-toggle.js
  docs-site/src/components/shadow-toggle/shadow-toggle.scss
  docs-site/src/components/site-layout/site-layout.scss
  docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/35-accordion-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button-deprecated/-20-button-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button-deprecated/-60-button-with-3rd-party-js.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/20-card-replacement-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/icon-deprecated/-10-icon-theme-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/menu/35-menu-use-case-theming.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/progress-bar/25-progress-bar-theming.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/share/30-share-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/table/30-table-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/25-tabs-theme.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/styles/_global-search.scss
  docs-site/src/pages/pattern-lab/_patterns/999-tests/academy/02-molecules/training/_completed-training-item.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/academy/02-molecules/training/_training-meta-items.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/academy/03-organisms/landing-page/_landing-page-inner-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/academy/05-pages/completed-training/acd-completed-training.twig
  packages/components/bolt-banner/src/banner.scss
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
  packages/components/bolt-icon/src/icon.scss
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-navbar/src/navbar-menu.scss
  packages/components/bolt-navbar/src/navbar.scss
  packages/components/bolt-ratio/src/ratio.scss
  packages/components/bolt-video/src/video.scss
  packages/core-v3.x/styles/01-settings/settings-themes/_constants.scss
  packages/core-v3.x/styles/01-settings/settings-themes/_helpers.scss
  packages/core-v3.x/styles/01-settings/settings-themes/index.scss
  packages/core-v3.x/styles/02-tools/tools-css-vars/_tools-css-vars.scss
  packages/core-v3.x/styles/02-tools/tools-themes/_tools.themes.scss
  packages/core-v3.x/styles/main.scss
  packages/experimental/micro-journeys/src/interactive-pathways.js
  packages/global/package.json
  packages/global/styles/06-themes/_themes.all.scss
  packages/global/styles/06-themes/themes.schema.json
  packages/global/styles/index.scss
  packages/layouts/bolt-list/src/list.js
Labels: type: feature

#2381 Hotfix: Yarn error and misplaced icons
  package.json
  packages/elements/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/elements/bolt-icon/icon.schema.json
  packages/elements/bolt-icon/src/icons/js/minus-circle.js
  packages/elements/bolt-icon/src/icons/js/minus-solid.js
  packages/elements/bolt-icon/src/icons/js/minus.js
  packages/elements/bolt-icon/src/icons/minus-circle.twig
  packages/elements/bolt-icon/src/icons/minus-solid.twig
  packages/elements/bolt-icon/src/icons/minus.twig
  packages/elements/bolt-icon/src/icons/svgs/minus-circle.svg
  packages/elements/bolt-icon/src/icons/svgs/minus-solid.svg
  packages/elements/bolt-icon/src/icons/svgs/minus.svg
  packages/elements/bolt-icon/src/icons/twig/minus-circle.twig
  packages/elements/bolt-icon/src/icons/twig/minus-solid.twig
  packages/elements/bolt-icon/src/icons/twig/minus.twig
Labels: version: patch

#2382 DS-590 Switch button component
  docs-site/src/pages/pattern-lab/_patterns/40-components/switch-button/00-switch-button-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/switch-button/05-switch-button.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/switch-button/switch-button-id.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-switch-button/README.md
  packages/components/bolt-switch-button/__tests__/__snapshots__/switch-button.js.snap
  packages/components/bolt-switch-button/__tests__/switch-button.js
  packages/components/bolt-switch-button/index.scss
  packages/components/bolt-switch-button/package.json
  packages/components/bolt-switch-button/src/switch-button.scss
  packages/components/bolt-switch-button/src/switch-button.twig
  packages/components/bolt-switch-button/switch-button.schema.js
Labels: type: feature

#2384 Update chromedriver
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#2383 DS-679 Profile view
  docs-site/src/assets/images/placeholders/badge-mis20301.png
  docs-site/src/assets/images/placeholders/badge-mis29881.png
  docs-site/src/assets/images/placeholders/badge-pw2020.png
  docs-site/src/assets/images/placeholders/badge-pw2021.png
  docs-site/src/assets/images/placeholders/cert-pegaclsa62.png
  docs-site/src/assets/images/placeholders/cert-pegapcdc80.png
  docs-site/src/assets/images/placeholders/cert-pegapcds80.png
  docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/40-components/info-section/00-info-section-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/info-section/05-info-section.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/00-profile-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/05-profile.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/10-profile-full-bleed.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/-portal-quick-links.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/00-portal-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/portal.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-profile.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/00-user-docs.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-info-section/README.md
  packages/components/bolt-info-section/__tests__/__snapshots__/info-section.js.snap
  packages/components/bolt-info-section/__tests__/info-section.js
  packages/components/bolt-info-section/index.js
  packages/components/bolt-info-section/index.scss
  packages/components/bolt-info-section/info-section.schema.js
  packages/components/bolt-info-section/package.json
  packages/components/bolt-info-section/src/info-section.js
  packages/components/bolt-info-section/src/info-section.scss
  packages/components/bolt-info-section/src/info-section.twig
  packages/components/bolt-page-footer/src/page-footer.scss
  packages/components/bolt-profile/README.md
  packages/components/bolt-profile/__tests__/__snapshots__/profile.js.snap
  packages/components/bolt-profile/__tests__/profile.js
  packages/components/bolt-profile/index.scss
  packages/components/bolt-profile/package.json
  packages/components/bolt-profile/profile.schema.js
  packages/components/bolt-profile/src/_profile-default-avatar.twig
  packages/components/bolt-profile/src/_profile-default-cover.twig
  packages/components/bolt-profile/src/profile.scss
  packages/components/bolt-profile/src/profile.twig
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-tooltip/src/tooltip.twig
  packages/elements/bolt-image/src/image.scss
Labels: type: feature

#2385 Background Component Image Update
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/00-background-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/10-background-opacity-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/15-background-focal-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/25-background-fill-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/35-background-valign-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/35-band-with-background.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/40-band-nested.twig
  packages/components/bolt-background/src/background-item.twig
Labels: type: feature

#2386 Release v4.8.0: Profile view and background image update
  docs-site/src/assets/images/placeholders/badge-mis20301.png
  docs-site/src/assets/images/placeholders/badge-mis29881.png
  docs-site/src/assets/images/placeholders/badge-pw2020.png
  docs-site/src/assets/images/placeholders/badge-pw2021.png
  docs-site/src/assets/images/placeholders/cert-pegaclsa62.png
  docs-site/src/assets/images/placeholders/cert-pegapcdc80.png
  docs-site/src/assets/images/placeholders/cert-pegapcds80.png
  docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/00-background-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/10-background-opacity-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/15-background-focal-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/25-background-fill-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/35-background-valign-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/35-band-with-background.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/40-band-nested.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/info-section/00-info-section-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/info-section/05-info-section.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/00-profile-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/05-profile.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/10-profile-full-bleed.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/-portal-quick-links.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/00-portal-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/80-portal/portal.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-profile.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/00-user-docs.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-background/package.json
  packages/components/bolt-background/src/background-item.twig
  packages/components/bolt-info-section/README.md
  packages/components/bolt-info-section/__tests__/__snapshots__/info-section.js.snap
  packages/components/bolt-info-section/__tests__/info-section.js
  packages/components/bolt-info-section/index.js
  packages/components/bolt-info-section/index.scss
  packages/components/bolt-info-section/info-section.schema.js
  packages/components/bolt-info-section/package.json
  packages/components/bolt-info-section/src/info-section.js
  packages/components/bolt-info-section/src/info-section.scss
  packages/components/bolt-info-section/src/info-section.twig
  packages/components/bolt-page-footer/src/page-footer.scss
  packages/components/bolt-profile/README.md
  packages/components/bolt-profile/__tests__/__snapshots__/profile.js.snap
  packages/components/bolt-profile/__tests__/profile.js
  packages/components/bolt-profile/index.scss
  packages/components/bolt-profile/package.json
  packages/components/bolt-profile/profile.schema.js
  packages/components/bolt-profile/src/_profile-default-avatar.twig
  packages/components/bolt-profile/src/_profile-default-cover.twig
  packages/components/bolt-profile/src/profile.scss
  packages/components/bolt-profile/src/profile.twig
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-tooltip/src/tooltip.twig
  packages/elements/bolt-image/src/image.scss
  packages/testing/testing-nightwatch/package.json
  packages/testing/testing-utils/__tests__/test-utils.test.js
  scripts/package.json
  yarn.lock
Labels: version: minor

#2387 Background Component Updates
  packages/base-starter-kit/.boltrc.js
  packages/components/bolt-background/package.json
  packages/testing/testing-nightwatch/package.json
  packages/testing/testing-utils/__tests__/test-utils.test.js
  scripts/package.json
  yarn.lock
Labels: type: feature

#2388 DS-669 side nav and holy grail layout enhancements
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/holy-grail/10-holy-grail-use-case-navigation.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/70-community/-community-doc-layout.twig
  packages/components/bolt-side-nav/src/side-nav.scss
  packages/layouts/bolt-holy-grail/src/holy-grail.scss
Labels: type: feature

#2390 DS-304 add subheadline sizes to match Drupal admin ui
  docs-site/src/pages/pattern-lab/_patterns/40-components/headline/40-headline-numbered.twig
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-headline/src/eyebrow.twig
  packages/components/bolt-headline/src/headline.scss
  packages/components/bolt-headline/src/headline.twig
  packages/components/bolt-headline/src/lead.twig
  packages/components/bolt-headline/src/subheadline.twig
  packages/components/bolt-headline/src/text.twig
Labels: type: feature

#2391 DS-676 Upgrade to Stylelint 14
  package.json
  packages/configs/stylelint-config/ideal.js
  packages/configs/stylelint-config/index.js
  packages/configs/stylelint-config/package.json
  yarn.lock
Labels: type: feature
