Repository boltdesignsystem/bolt, pull requests merged in 2021-02, with the labels that each got.

#2090 DS-316: make alt prop persistent
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-device-viewer/__tests__/__snapshots__/device-viewer.js.snap
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-image/__tests__/__snapshots__/image.js.snap
  packages/components/bolt-image/__tests__/image.js
  packages/components/bolt-image/src/image.js
  packages/components/bolt-image/src/image.twig
  packages/components/bolt-logo/__tests__/__snapshots__/logo.js.snap
Labels: type: feature

#2087 DS-307 Add section for visual changes to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: feature

#2092 DS-321 Update Slotify to handle only whitespace as content
  packages/base-element/src/Slotify.js
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
Labels: type: feature

#2091 DS-320 H5P-related component updates
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/h5p-embed/_h5p-embed.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/challenge-details/acd-challenge-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/wip-pages/mission-exercise/_acd-mission-exercise-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
  packages/components/bolt-band/__tests__/__image_snapshots__/band-js-bolt-band-component-full-bleed-usage-1-snap.png
  packages/components/bolt-band/__tests__/__image_snapshots__/band-js-bolt-band-component-nested-bands-usage-1-snap.png
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-band/__tests__/band.js
  packages/components/bolt-band/index.js
  packages/components/bolt-band/package.json
  packages/components/bolt-band/src/band.js
  packages/components/bolt-band/src/band.scss
  packages/components/bolt-band/src/band.twig
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-stack/__tests__/__snapshots__/stack.js.snap
  packages/components/bolt-stack/index.js
  packages/components/bolt-stack/package.json
  packages/components/bolt-stack/src/stack.js
  packages/components/bolt-stack/src/stack.scss
  packages/components/bolt-stack/src/stack.twig
  packages/components/bolt-sticky/__tests__/__snapshots__/sticky.js.snap
Labels: type: feature

#2086 Hotfix/DS-238 Update v3 dependencies
  package.json
  packages/experimental/micro-journeys/package.json
  packages/website-ui/uikit-polyfills/CHANGELOG.md
  packages/website-ui/uikit-polyfills/index.js
  packages/website-ui/uikit-polyfills/package.json
  packages/website-ui/uikit-workshop/package.json
  packages/website-ui/uikit-workshop/src/scripts/patternlab-viewer.js
  yarn.lock
Labels: version: patch

#2094 Hotfix/Revert adding build-tools to missing pkgs whitelist
  packages/build-tools/utils/manifest.get-pkg-info.js
Labels: version: patch

#2097 Hotfix/DS-291 SASS loader min() error (v2.31.2)
  packages/base-element/src/lib/decorators/json-schema-props.js
  packages/components/bolt-button/src/button.js
  packages/components/bolt-popover/src/popover.scss
Labels: version: patch

#2096 Hotfix/WWW-546 Fix JS error in MJ editor (v2.30.3)
  packages/base-element/src/lib/decorators/json-schema-props.js
  packages/components/bolt-button/src/button.js
Labels: version: patch

#2089 DS-318 add disabled state to typeahead
  packages/components/bolt-typeahead/typeahead.autosuggest.js
  packages/components/bolt-typeahead/typeahead.js
  packages/components/bolt-typeahead/typeahead.schema.js
  packages/components/bolt-typeahead/typeahead.scoped.scss
  packages/components/bolt-typeahead/typeahead.twig
Labels: type: bugfix

#2098 DS-313: Fix button's use of the style prop
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/15-button-style-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/20-button-theme-variations.twig
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-button/README.md
  packages/components/bolt-button/__tests__/3rd-party-javascript-events-after-moving-and-update-outer-props.html
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button-wc.test.js
  packages/components/bolt-button/button.schema.js
  packages/components/bolt-button/src/button.js
  packages/components/bolt-button/src/button.twig
  packages/components/bolt-card-deprecated/__tests__/__snapshots__/card.js.snap
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
  packages/twig-integration/twig-renderer-endpoint/__snapshots__/index.test.js.snap
Labels: type: feature

#2108 DS-323: deprecate auto slides per view. set max slides to 4.
  packages/components/bolt-carousel/carousel.schema.js
  packages/components/bolt-carousel/src/carousel.twig
Labels: type: feature

#2101 DS-328 fix starter kit CSS order and misc visual bugs
  docs-site/src/pages/pattern-lab/_patterns/40-components/buttons-group/20-button-group-contentItems.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-button-group/__tests__/button-group.js
  packages/components/bolt-button-group/button-group.schema.js
  packages/components/bolt-button-group/src/button-group.twig
  packages/components/bolt-form/src/form.scss
  packages/components/bolt-link/src/link.scss
  packages/elements/bolt-text-link/src/text-link.scss
  packages/layouts/bolt-list/__tests__/__snapshots__/list.js.snap
  packages/layouts/bolt-list/__tests__/list.js
Labels: type: bugfix

#2109 DS-303 Fix init() bugs
  packages/components/bolt-trigger/__tests__/__snapshots__/trigger.js.snap
  packages/components/bolt-trigger/__tests__/trigger.js
  packages/twig-integration/twig-extensions-shared/src/Utils.php
Labels: type: feature

#2085 [DO NOT MERGE] DS-312 best of content mockups
  docs-site/src/assets/images/backgrounds/navy-light-circles.jpg
  docs-site/src/assets/images/backgrounds/teal-stripes.png
  docs-site/src/assets/images/content/promos/promo-16x9-mask.jpg
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/00-homepage-phase0.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/00-homepage-phase0.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/03-gallery-phase0.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/03-gallery-phase0.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/13-gallery-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/13-gallery-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/16-listing-pegaworld-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/16-listing-pegaworld-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/20-homepage-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/20-homepage-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/23-gallery-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/23-gallery-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/26-listing-pegaworld-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/26-listing-pegaworld-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/29-listing-customers-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/29-listing-customers-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_00-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_00-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_00-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_00-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/_default-page-template.twig
Labels: type: feature

#2107 Add link trigger to modal docs
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
Labels: type: docs

#2111 Upgrade @babel/core, @babel/preset-env
  packages/build-tools/package.json
  packages/configs/babel-preset-bolt/index.js
  packages/configs/babel-preset-bolt/package.json
  packages/testing/testing-jest/package.json
  packages/website-ui/uikit-prerender-spa-plugin/package.json
  packages/website-ui/uikit-prerenderer/package.json
  packages/website-ui/uikit-workshop/package.json
  yarn.lock
Labels: type: feature

#2103 DS-303 Button Twig update
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/15-button-hierarchy-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/999-button-with-web-component.twig
  packages/components/bolt-button-group/__tests__/__snapshots__/button-group.js.snap
  packages/components/bolt-button/TESTING.md
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/button.schema.js
  packages/components/bolt-button/src/_button-macros.twig
  packages/components/bolt-button/src/button.scss
  packages/components/bolt-button/src/button.twig
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
  packages/components/bolt-typeahead/typeahead.twig
  packages/twig-integration/twig-renderer-endpoint/__snapshots__/index.test.js.snap
Labels: type: feature

#2080 DS-214 Listing Teaser Component
  docs-site/__tests__/__snapshots__/vrt-urls.js.snap
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/00-listing-teaser-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/05-listing-teaser.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/10-listing-teaser-signifier.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/15-listing-teaser-headline.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/20-listing-teaser-status-and-action.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/25-listing-teaser-meta-data-and-more.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/30-listing-teaser-use-case-academy.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/35-listing-teaser-use-case-collaboration-center.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/40-listing-teaser-use-case-article-list.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-headline/headline.schema.js
  packages/components/bolt-listing-teaser/README.md
  packages/components/bolt-listing-teaser/__tests__/__snapshots__/listing-teaser.js.snap
  packages/components/bolt-listing-teaser/__tests__/listing-teaser.js
  packages/components/bolt-listing-teaser/index.scss
  packages/components/bolt-listing-teaser/listing-teaser.schema.js
  packages/components/bolt-listing-teaser/package.json
  packages/components/bolt-listing-teaser/src/listing-teaser.scss
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
  yarn.lock
Labels: type: feature
