Repository boltdesignsystem/bolt, pull requests merged in 2021-12, with the labels that each got.

#2396 WWW-1072 Fix chip component's gray color option
  docs-site/src/pages/pattern-lab/_patterns/40-components/chip/30-chip-color-variations.twig
  packages/components/bolt-chip/chip.schema.js
  packages/components/bolt-chip/src/chip.js
  packages/components/bolt-chip/src/chip.scss
  packages/components/bolt-chip/src/chip.twig
Labels: type: bugfix

#2394 Background Component LazyLoad Update
  packages/components/bolt-background/src/background-item.twig
Labels: type: bugfix

#2395 Release v4.8.1: Background Image and Chip Color Update
  docs-site/src/pages/pattern-lab/_patterns/40-components/chip/30-chip-color-variations.twig
  packages/components/bolt-background/src/background-item.twig
  packages/components/bolt-chip/chip.schema.js
  packages/components/bolt-chip/src/chip.js
  packages/components/bolt-chip/src/chip.scss
  packages/components/bolt-chip/src/chip.twig
Labels: version: patch

#2399 DS-682 profile enhancements
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-notification-settings.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-notification-tag-manager-1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-notification-tag-manager-2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-notification-tag-manager-3.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-notification-tag-manager-4.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-profile-empty-state.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-profile.twig
  packages/components/bolt-info-section/src/info-section.scss
  packages/components/bolt-profile/src/profile.scss
  packages/components/bolt-profile/src/profile.twig
Labels: type: feature

#2379 DS 656 Form Documentation Update
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/00-form-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/05-form-element-input-field.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element~disabled-search.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element~disabled.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element~email.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element~password.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element~search.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-element-demo-input-element~server-errors.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/10-form-label-display.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/15-form-fieldset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/15-form-label-positions.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/20-form-element-demo-radio.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/20-form-element-demo-radio.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/20-form-radios-and-checkboxes.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/25-form-element-demo-radio-fieldset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/25-form-select.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/26-form-element-auto-format.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/30-form-element-demo-checkbox.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/30-form-element-demo-checkbox.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/30-form-textarea.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/35-form-element-demo-checkbox-fieldset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/35-form-input-auto-format.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/40-form-element-demo-select.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/40-form-element-demo-select.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/40-form-use-case-campaign-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/45-form-use-case-inline-inputs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/50-form-element-demo-textarea.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/60-form-full-campaign-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/65-form-inline-inputs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/70-form-card-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/50-modal-usage-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/52-modal-usage-persistent.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/55-modal-usage-form.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/05-d8-browse-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/00-event-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/_event-register-form.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/45-d8-blog/00-blog-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/50-d8-careers/00-careers-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-results.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  packages/components/bolt-form/src/elements/form-fieldset.twig
  packages/components/bolt-form/src/elements/form-label.twig
  packages/components/bolt-form/src/form.scss
  packages/components/bolt-form/src/form.twig
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
Labels: type: docs

#2403 WWW-1121 adjust chip icon alignment
  docs-site/src/pages/pattern-lab/_patterns/999-tests/chip/00-chip-and-icon.twig
  packages/components/bolt-chip/src/chip.scss
Labels: type: bugfix

#2404 DS-683 Fix printable element's width in Safari print
  docs-site/.incache
  docs-site/src/pages/pattern-lab/_patterns/20-elements/printable/05-printable.twig
  packages/elements/bolt-printable/src/printable.scss
Labels: type: bugfix

#2402 DOCS-232 Fix holy grail layout content width
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/holy-grail/10-holy-grail-use-case-navigation.twig
  packages/layouts/bolt-holy-grail/src/holy-grail.scss
Labels: type: bugfix

#2405 Release v4.8.3
  docs-site/.incache
  docs-site/src/pages/pattern-lab/_patterns/20-elements/printable/05-printable.twig
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/holy-grail/10-holy-grail-use-case-navigation.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/chip/00-chip-and-icon.twig
  packages/components/bolt-chip/src/chip.scss
  packages/elements/bolt-printable/src/printable.scss
  packages/layouts/bolt-holy-grail/src/holy-grail.scss
Labels: version: patch

#2400 DS-660 Ratio Element
  docs-site/.incache
  docs-site/src/pages/pattern-lab/_patterns/20-elements/ratio/00-ratio-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/ratio/05-ratio.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/ratio/10-ratio-video.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/ratio/15-ratio-use-case-fit-and-position.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/elements/bolt-ratio/CHANGELOG.md
  packages/elements/bolt-ratio/README.md
  packages/elements/bolt-ratio/__tests__/__snapshots__/ratio.js.snap
  packages/elements/bolt-ratio/__tests__/ratio.js
  packages/elements/bolt-ratio/index.scss
  packages/elements/bolt-ratio/package.json
  packages/elements/bolt-ratio/ratio.schema.js
  packages/elements/bolt-ratio/src/ratio.scss
  packages/elements/bolt-ratio/src/ratio.twig
Labels: type: feature

#2408 JS refactoring
  docs-site/.incache
  package.json
  packages/build-tools/tasks/api-tasks/bolt-versions.js
Labels: type: feature

#2406 Version Selector Logic Update
  docs-site/.incache
  packages/build-tools/tasks/api-tasks/bolt-versions.js
Labels: type: feature

#2413 Hotfix: v5.1.1 fix build errors
  packages/build-tools/tasks/task-collections.js
  packages/configs/stylelint-config/package.json
  yarn.lock
Labels: version: patch
