Repository boltdesignsystem/bolt, pull requests merged in 2021-07, with the labels that each got.

#2245 DS-526: Replace Button in Carousel Component
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-carousel/__tests__/carousel.js
  packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
  packages/components/bolt-carousel/src/carousel.js
  packages/components/bolt-carousel/src/carousel.twig
Labels: type: feature

#2251 DS-381: Remove click-handler JS module
  packages/core-v3.x/index.js
  packages/core-v3.x/modules/index.js
  packages/core-v3.x/modules/modules.js
  packages/core-v3.x/modules/src/click-handler.js
Labels: type: feature

#2252 DS-545 add pin icon and fix name typo
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/svgs/pega/pega-connection-hierarchy.svg
  packages/components/bolt-icons/src/svgs/pega/pega-database.svg
  packages/components/bolt-icons/src/svgs/pega/pega-pin.svg
Labels: type: feature

#2253 DS-524: Fix smooth scroll bug on deep linked Tabs
  docs-site/src/pages/pattern-lab/_patterns/999-tests/tabs/10-tabs-deep-linking.twig
  packages/components/bolt-tabs/src/tabs.js
Labels: type: bugfix

#2250 DS-535: Replace Button in Typeahead Component
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
  packages/components/bolt-typeahead/typeahead.js
  packages/components/bolt-typeahead/typeahead.scoped.scss
  packages/components/bolt-typeahead/typeahead.twig
Labels: type: feature

#2249 DS-109: Convert components to use border radius function
  packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
  packages/components/bolt-blockquote/src/blockquote.scss
  packages/components/bolt-button/src/button.scss
  packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
  packages/components/bolt-carousel/src/_carousel.pagination.scss
  packages/components/bolt-carousel/src/_carousel.scrollbar.scss
  packages/components/bolt-icon/src/icon.scss
  packages/components/bolt-navbar/src/navbar-menu.scss
  packages/components/bolt-pagination/src/pagination.scss
  packages/components/bolt-progress-bar/src/progress-bar.scss
  packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
  packages/components/bolt-tabs/src/tabs.scss
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-video/src/_videojs-enhancements.scss
  packages/components/bolt-video/src/video-meta.scss
Labels: type: feature

#2260 DS-548 Listing teaser custom status numbers
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/05-listing-teaser.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/20-listing-teaser-status-and-action.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/25-listing-teaser-meta-data-and-more.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/55-listing-teaser-use-case-collaboration-center.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/65-listing-teaser-use-case-search-result-list.twig
  packages/components/bolt-listing-teaser/__tests__/__snapshots__/listing-teaser.js.snap
  packages/components/bolt-listing-teaser/listing-teaser-status-number.schema.js
  packages/components/bolt-listing-teaser/listing-teaser.schema.js
  packages/components/bolt-listing-teaser/package.json
  packages/components/bolt-listing-teaser/src/listing-teaser-status-number.twig
  packages/components/bolt-listing-teaser/src/listing-teaser.scss
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
Labels: type: feature

#2257 DS-204: Print Styles
  docs-site/src/components/pattern-lab-utils/docs.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/printable/00-printable-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/printable/05-printable.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/04-templates/_academy-detail-page-template.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/configs/stylelint-config/ideal.js
  packages/elements/bolt-printable/CHANGELOG.md
  packages/elements/bolt-printable/README.md
  packages/elements/bolt-printable/index.scss
  packages/elements/bolt-printable/package.json
  packages/elements/bolt-printable/src/printable.scss
Labels: type: feature

#2263 DS-530: Deprecate Button-Group
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/opacity.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button-group-deprecated.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/button-group-deprecated/-05-button-group.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button-group-deprecated/-10-button-group-icon-only.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button-group-deprecated/-15-button-group-quantity-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button-group-deprecated/00-deprecated-button-group-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/buttons-group/00-button-group-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/30-tabs-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/40-tabs-use-case-tabbed-band.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/05-d8-homepage-japanese.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t4.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/00-d8-news-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/05-d8-browse-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/30-d8-partners/00-d8-partners-search.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/05-event-detail.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/45-d8-blog/00-blog-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/dashboard/dashboard/acd-dashboard.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
  packages/components/bolt-search-filter/search-filter.twig
Labels: type: feature

#2259 DS-539 Fix toolbar buttons alignment
  packages/components/bolt-toolbar/toolbar.scss
  packages/components/bolt-toolbar/toolbar.twig
Labels: type: bugfix

#2264 Hotfix: Listing Teaser Update
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/05-listing-teaser.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/15-listing-teaser-headline.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/20-listing-teaser-status-and-action.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/25-listing-teaser-meta-data-and-more.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/55-listing-teaser-use-case-collaboration-center.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/65-listing-teaser-use-case-search-result-list.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/70-listing-teaser-use-case-contact-list.twig
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/svgs/pega/pega-connection-hierarchy.svg
  packages/components/bolt-icons/src/svgs/pega/pega-database.svg
  packages/components/bolt-icons/src/svgs/pega/pega-pin.svg
  packages/components/bolt-listing-teaser/listing-teaser-status-number.schema.js
  packages/components/bolt-listing-teaser/listing-teaser.schema.js
  packages/components/bolt-listing-teaser/package.json
  packages/components/bolt-listing-teaser/src/listing-teaser-status-number.twig
  packages/components/bolt-listing-teaser/src/listing-teaser.scss
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
Labels: version: patch

#2256 DS-534: Replace Button in Card Component
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/999-card-replacement-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/card/10-card-links-and-buttons.twig
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-card-replacement/package.json
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.scss
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
  packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
  packages/components/bolt-listing-teaser/__tests__/__snapshots__/listing-teaser.js.snap
Labels: type: feature

#2255 DS-537: Standarize schema and twig for bolt-banner
  packages/components/bolt-banner/banner.schema.js
  packages/components/bolt-banner/src/banner.twig
Labels: type: feature

#2261 DS-489 twig deprecations
  docs-site/src/components/pattern-lab-utils/_schema-docs-macros.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/15-action-blocks-borderless-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/05-text.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/10-text-typographic-recipes.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/15-text-tag-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/20-text-display-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/25-text-color-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/30-text-align-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/35-text-opacity-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/40-text-quoted.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/45-text-line-height-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/50-text-letter-spacing-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/55-text-transform-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/60-text-font-family-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/65-text-font-size-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/70-text-font-style-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/75-text-font-weight-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/04-templates/_academy-detail-page-template.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/04-templates/_academy-landing-page-template.twig
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig
  packages/components/bolt-accordion/src/accordion.twig
  packages/components/bolt-action-blocks/src/action-blocks.twig
  packages/components/bolt-band/src/band.twig
  packages/components/bolt-banner/src/banner.twig
  packages/components/bolt-blockquote/src/blockquote.twig
  packages/components/bolt-button/src/button.twig
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
  packages/components/bolt-chip/src/chip.twig
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-image/src/image.twig
  packages/components/bolt-link/src/link.twig
  packages/components/bolt-list/src/list.twig
  packages/components/bolt-menu/src/menu.twig
  packages/components/bolt-modal/src/modal.twig
  packages/components/bolt-navbar/src/navbar-li.twig
  packages/components/bolt-navbar/src/navbar.twig
  packages/components/bolt-page-header/src/page-header.twig
  packages/components/bolt-popover/src/popover.twig
  packages/components/bolt-stack/src/stack.twig
  packages/components/bolt-table/src/table.twig
  packages/components/bolt-tabs/src/TabPanel/tab-panel.twig
  packages/components/bolt-tabs/src/tabs.twig
  packages/components/bolt-toc/src/_toc-item.twig
  packages/components/bolt-toc/src/toc.twig
  packages/components/bolt-toolbar/toolbar.twig
  packages/components/bolt-tooltip/src/tooltip.twig
  packages/components/bolt-trigger/src/trigger.twig
  packages/layouts/bolt-list/src/list.twig
  packages/twig-integration/twig-extensions-shared/src/Layout/GridCellNode.php
  packages/twig-integration/twig-extensions-shared/src/Layout/GridTagNode.php
  packages/twig-integration/twig-extensions-shared/src/SSR/SSRTagNode.php
  packages/twig-integration/twig-extensions-shared/src/TwigExtensions/BoltCore.php
Labels: type: feature

#2270 DS-563: Fix boolean attribute syntax
  docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/05-navbar-with-active-link.twig
  packages/components/bolt-navbar/src/navbar-li.twig
Labels: version: patch

#2269 DS-554: Remove Text Align Left Update
  packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
  packages/components/bolt-banner/src/banner.scss
  packages/components/bolt-button/src/button.scss
  packages/components/bolt-list/src/list.scss
  packages/components/bolt-video/brightcove/_video.scss
  packages/components/bolt-video/src/_videojs-enhancements.scss
Labels: type: feature

#2271 DS-562 Remove unexpected margin bottom on Navbar title
  docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/22-navbar-title-tags.twig
  packages/components/bolt-navbar/src/navbar.scss
Labels: type: bugfix

#2272 Hotfix v4.0.2
  docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/05-navbar-with-active-link.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/22-navbar-title-tags.twig
  packages/components/bolt-band/band.schema.js
  packages/components/bolt-navbar/src/navbar-li.twig
  packages/components/bolt-navbar/src/navbar.scss
  packages/twig-integration/twig-extensions-shared/src/Utils.php
Labels: version: patch

#2265 DS-138 Replace Button/Link in PL and Jest tests
  docs-site/src/components/pattern-lab-utils/sassdocs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/block-list/00-block-list-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/block-list/05-block-list.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/block-list/10-block-list-theme-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/10-popover-boundary.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/tooltip/10-tooltip-boundary.twig
  docs-site/src/templates/default.twig
  packages/base-starter-kit/demo.html
  packages/build-tools/tasks/api-tasks/bolt-status-board.js
  packages/components/bolt-breadcrumb/__tests__/__snapshots__/breadcrumb.js.snap
  packages/components/bolt-breadcrumb/__tests__/breadcrumb.js
  packages/components/bolt-popover/__tests__/__snapshots__/popover.js.snap
  packages/components/bolt-popover/__tests__/popover.js
  packages/components/bolt-tabs/__tests__/tabs.e2e.js
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/__tests__/tooltip.js
Labels: type: feature

#2262 DS-538: Update test banner
  packages/components/bolt-banner/__tests__/__snapshots__/banner.js.snap
  packages/components/bolt-banner/__tests__/banner.js
Labels: type: feature

#2277 COM-780 keyboard input styles
  packages/global/styles/04-elements/_elements-code.scss
  packages/global/styles/04-elements/_elements-misc.scss
Labels: type: bugfix

#2282 DS-574: Disable cssnano `calc` optimizations
  packages/build-tools/create-webpack-config.js
Labels: version: patch

#2280 DS-555 Remove Bolt No Select Mixin
  docs-site/src/components/radio-switch/radio-switch.scss
  docs-site/src/components/shadow-toggle/shadow-toggle.scss
  packages/components/bolt-button/src/_button-settings-and-tools.scss
  packages/core-v3.x/styles/02-tools/tools-no-select/README.md
  packages/core-v3.x/styles/02-tools/tools-no-select/_tools-no-select.scss
  packages/core-v3.x/styles/main.scss
Labels: type: feature

#2105 DS-296 Image Element
  docs-site/src/pages/pattern-lab/_patterns/20-elements/image/00-image-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/image/05-image.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/image/10-image-srcset-and-sizes.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/image/15-image-fill.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/image/20-image-background.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/image/25-image-use-case-background-fit-and-position.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/image/30-image-use-case-art-direction.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/00-d8-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/05-d8-homepage-japanese.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/15-d8-resource-details-pages/00-resource-details-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/00-event-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/05-event-detail.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-blockquote/src/blockquote.twig
  packages/components/bolt-device-viewer/src/device-viewer.twig
  packages/components/bolt-device-viewer/src/devices/_ipad.twig
  packages/components/bolt-device-viewer/src/parts/_screen.twig
  packages/elements/bolt-image/CHANGELOG.md
  packages/elements/bolt-image/image.schema.js
  packages/elements/bolt-image/index.scss
  packages/elements/bolt-image/package.json
  packages/elements/bolt-image/src/image.scss
  packages/elements/bolt-image/src/image.twig
  yarn.lock
Labels: type: feature

#2281 DS-504: Add option to show and hide Test folder in Pattern Lab
  packages/website-ui/uikit-workshop/src/icons/test.svg
  packages/website-ui/uikit-workshop/src/scripts/actions/app.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-list.scss
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-toggle-test/pl-toggle-test.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-toggle-test/pl-toggle-test.scss
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-tools-menu/pl-tools-menu.js
  packages/website-ui/uikit-workshop/src/scripts/localstorage.js
  packages/website-ui/uikit-workshop/src/scripts/patternlab-components.js
  packages/website-ui/uikit-workshop/src/scripts/reducers/app.js
Labels: type: feature

#2283 Hotfix v4.0.3
  packages/build-tools/create-webpack-config.js
Labels: version: patch
