Repository boltdesignsystem/bolt, pull requests merged in 2021-03, with the labels that each got.

#2112 DS-388 Allow `download` attribute to be added to inner `<a>`
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-button/src/button.twig
Labels: type: feature

#2110 Feature/ds 360 card action icon override
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/10-card-button-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/999-card-replacement-with-web-component.twig
  packages/components/bolt-card-replacement/card-replacement.schema.js
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
  packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
Labels: type: feature

#2116 DS-399 Replace theme-tools, upgrade notifier
  packages/build-tools/plugins/sass-export-data/index.js
  packages/build-tools/plugins/sass-export-data/package.json
  packages/build-tools/utils/package.json
Labels: type: feature

#2117 DS-399 Upgrade lerna, remove unused deps
  lerna.json
  package.json
  packages/servers/default-server/package.json
  yarn.lock
Labels: type: feature

#2119 WWW-467 Create PegaWorld navigation with Page Header component
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/-example-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/05-page-header.twig
  packages/components/bolt-page-header/page-header.schema.js
  packages/components/bolt-page-header/src/_page-header-desktop.scss
  packages/components/bolt-page-header/src/_page-header-mobile.scss
  packages/components/bolt-page-header/src/_page-header-settings-and-tools.scss
  packages/components/bolt-page-header/src/page-header.scss
  packages/components/bolt-page-header/src/page-header.twig
Labels: type: feature

#2120 DS-399 Dependency cleanup
  packages/build-tools/package.json
  packages/configs/stylelint-config/ideal.js
  packages/configs/stylelint-config/index.js
  packages/configs/stylelint-config/package.json
  packages/core-v3.x/package.json
  yarn.lock
Labels: type: feature

#2121 DS-405: Upgrade babel to latest minor release to fix Edge 18 JS error
  packages/build-tools/package.json
  packages/configs/babel-preset-bolt/package.json
  packages/testing/testing-jest/package.json
  yarn.lock
Labels: type: feature

#2118 DS-324 Quick filters
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_00-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_00-quick-filters.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/index.scss
  packages/components/bolt-modal/src/modal.js
Labels: type: feature

#2124 Make button and text-link public
  packages/elements/bolt-button/package.json
  packages/elements/bolt-text-link/package.json
Labels: type: feature

#2125 Release 3.2.0
  packages/elements/bolt-button/package.json
  packages/elements/bolt-text-link/package.json
Labels: version: minor

#2126 DS-410 Babel node fixes
  package.json
  packages/build-tools/package.json
  packages/testing/testing-helpers/package.json
  packages/twig-integration/twig-renderer/package.json
  packages/website-ui/uikit-workshop/package.json
  yarn.lock
Labels: type: feature

#2127 Fix: quick filters overflow style
  docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
  docs-site/src/index.js
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-05-boc-homepage-phase0.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-10-boc-gallery-phase0.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-15-boc-homepage-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-20-boc-gallery-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-25-boc-listing-pegaworld-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-30-boc-homepage-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-35-boc-gallery-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-40-boc-listing-pegaworld-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-45-boc-listing-customers-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/00-boc-quick-filters-docs.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/00-boc-quick-filters-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/05-boc-homepage-phase0.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/10-boc-gallery-phase0.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/15-boc-homepage-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/20-boc-gallery-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/25-boc-listing-pegaworld-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/30-boc-homepage-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/35-boc-gallery-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/40-boc-listing-pegaworld-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/45-boc-listing-customers-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-quick-filters.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/index.scss
Labels: type: bugfix

#2131 DS-383: Carousel slides_per_group=1 changes click behavior
  packages/components/bolt-carousel/src/carousel.js
Labels: type: bugfix

#2135 DS-421: passing custom attributes to the band
  packages/components/bolt-hero/hero.schema.js
  packages/components/bolt-hero/hero.twig
Labels: type: feature

#2137 Brightcove Adjustments (WWW-465)
  docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/35-card-replacement-with-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/999-card-replacement-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/25-carousel-basic-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/device-viewer/25-device-viewer-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/figure/10-figure-media-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/30-tabs-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/25-teaser-type-and-time.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t4.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/50-d8-careers/00-careers-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
  packages/components/bolt-video/brightcove/_video.scss
  packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
Labels: type: feature

#2134 DS-419: Fix support for Edge 18/44
  packages/build-tools/get-babel-config.js
  packages/configs/browserslist-config/index.js
  packages/website-ui/uikit-workshop/webpack.config.js
Labels: version: patch

#2139 Remove dependency warning
  packages/build-tools/utils/manifest.js
Labels: type: feature

#2138 Upgrade stylelint to fix autofix bug
  package.json
Labels: type: feature

#2140 Fix issues with checkboxes on Safari browser
  packages/core-v3.x/styles/02-tools/tools-visuallyhidden/_tools-visuallyhidden.scss
Labels: type: bugfix

#2142 Updating the z-index
  packages/core-v3.x/styles/02-tools/tools-visuallyhidden/_tools-visuallyhidden.scss
Labels: type: bugfix

#2136 DS-371: Standardize Twig and Schema (Button)
  packages/components/bolt-button/src/button.twig
Labels: type: feature

#2130 Fix Twig conditions in Page Header and Listing Teaser
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
  packages/components/bolt-page-header/src/page-header.twig
Labels: type: bugfix

#2141 DS-384: Brightcove Language Order
  packages/components/bolt-video/brightcove/_video.scss
Labels: type: feature

#2143 DS-425 Fix Tabs "ready" event
  packages/components/bolt-tabs/src/tabs.js
Labels: type: feature

#2144 DS-239 Popover rework
  docs-site/src/pages/pattern-lab/_patterns/40-components/popover/35-popover-trigger-event-variations.twig
  packages/build-tools/create-webpack-config.js
  packages/components/bolt-modal/focus-trap/focusable.js
  packages/components/bolt-modal/focus-trap/index.js
  packages/components/bolt-modal/package.json
  packages/components/bolt-modal/src/modal.js
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-popover/__tests__/__snapshots__/popover.js.snap
  packages/components/bolt-popover/__tests__/popover.e2e.js
  packages/components/bolt-popover/package.json
  packages/components/bolt-popover/popover.schema.js
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-popover/src/popover.twig
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/package.json
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-tooltip/src/tooltip.twig
  packages/core-v3.x/elements/focus-trap/index.js
  packages/core-v3.x/package.json
  packages/core-v3.x/utils/index.js
  packages/core-v3.x/utils/query-shadow-root.js
  packages/core-v3.x/utils/tippy/index.js
  packages/global/styles/08-vendor/_vendor-tippy.scss
  packages/global/styles/index.scss
  yarn.lock
Labels: type: feature

#2146 Release 3.4.0
  docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/35-card-replacement-with-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/999-card-replacement-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/25-carousel-basic-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/device-viewer/25-device-viewer-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/figure/10-figure-media-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/popover/35-popover-trigger-event-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/30-tabs-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/25-teaser-type-and-time.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t4.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/50-d8-careers/00-careers-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
  package.json
  packages/build-tools/create-webpack-config.js
  packages/build-tools/utils/manifest.js
  packages/components/bolt-button/src/button.twig
  packages/components/bolt-carousel/src/carousel.js
  packages/components/bolt-hero/hero.schema.js
  packages/components/bolt-hero/hero.twig
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
  packages/components/bolt-modal/focus-trap/focusable.js
  packages/components/bolt-modal/focus-trap/index.js
  packages/components/bolt-modal/package.json
  packages/components/bolt-modal/src/modal.js
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-page-header/src/page-header.twig
  packages/components/bolt-popover/__tests__/__snapshots__/popover.js.snap
  packages/components/bolt-popover/__tests__/popover.e2e.js
  packages/components/bolt-popover/package.json
  packages/components/bolt-popover/popover.schema.js
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-popover/src/popover.twig
  packages/components/bolt-tabs/src/tabs.js
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
  packages/components/bolt-tooltip/package.json
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
  packages/components/bolt-tooltip/src/tooltip.twig
  packages/components/bolt-video/brightcove/_video.scss
  packages/core-v3.x/elements/focus-trap/index.js
  packages/core-v3.x/package.json
  packages/core-v3.x/styles/02-tools/tools-visuallyhidden/_tools-visuallyhidden.scss
  packages/core-v3.x/utils/index.js
  packages/core-v3.x/utils/query-shadow-root.js
  packages/core-v3.x/utils/tippy/index.js
  packages/global/styles/08-vendor/_vendor-tippy.scss
  packages/global/styles/index.scss
  packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
  yarn.lock
Labels: version: minor

#2149 WWW-467: Remove separate hard-coded classes on desktop heading links
  packages/components/bolt-page-header/src/page-header-nav-li.twig
Labels: type: bugfix

#2150 DS-439 Add `inverted` option to Tooltip
  docs-site/src/pages/pattern-lab/_patterns/40-components/tooltip/15-tooltip-inverted.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tooltip/20-tooltip-use-case-button-and-link.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tooltip/25-tooltip-use-case-icon.twig
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/tooltip.schema.js
  packages/global/styles/08-vendor/_vendor-tippy.scss
Labels: type: feature

#2151 Hotfix: Page Header and Tooltip updates
  docs-site/src/pages/pattern-lab/_patterns/40-components/tooltip/15-tooltip-inverted.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tooltip/20-tooltip-use-case-button-and-link.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/tooltip/25-tooltip-use-case-icon.twig
  packages/components/bolt-page-header/src/page-header-nav-li.twig
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/tooltip.schema.js
  packages/global/styles/08-vendor/_vendor-tippy.scss
Labels: version: patch
