Repository boltdesignsystem/bolt, pull requests merged in 2021-05, with the labels that each got.

#2194 DS-426 Fix Tabs overflow menu bug
  packages/components/bolt-tabs/src/tabs.js
Labels: type: bugfix

#2189 DS-401: Standardize Twig and Schema (Background)
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/00-background-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/10-background-opacity-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/15-background-focal-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/20-background-shapes-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/25-background-fill-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/30-background-without-overlay.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/35-background-valign-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/35-band-with-background.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/40-band-nested.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/breadcrumb/15-breadcrumb-use-case-band.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/20-card-replacement-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/30-carousel-advanced-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/sticky/-15-sticky-with-content-example.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/00-d8-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/05-d8-homepage-japanese.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/_product-t3-extra-videos.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/_product-t3.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t4.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/00-d8-news-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/05-d8-browse-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/30-d8-partners/00-d8-partners-search.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/00-event-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/40-d8-content-hub/00-sticky-navbar.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/band/_band--instructor-led-training.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/heros/dashboard-page-hero/_dashboard-page-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/heros/homepage-heros/_hero--hp-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/heros/search/_search-results-hero.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/landing-page/_landing-page-inner-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/modals/_test-completed-modal--after-submit.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/dashboard/dashboard--my-missions/acd-dashboard--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/certification-exam/acd-certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/combos/-95-in-page-example.twig
  packages/components/bolt-background/background.schema.js
  packages/components/bolt-background/src/background-item.twig
  packages/components/bolt-background/src/background-overlay.twig
  packages/components/bolt-background/src/background-shapes-wrapper.twig
  packages/components/bolt-background/src/background.twig
Labels: type: feature

#2193 DS-407: Update modal demos to use [data-bolt-modal-target] convention
  docs-site/src/pages/pattern-lab/_patterns/40-components/device-viewer/30-device-viewer-content-magnifier-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/05-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/10-modal-width-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/15-modal-spacing-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/20-modal-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/25-modal-scroll-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/35-modal-usage-javascript.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/40-modal-usage-image-and-caption.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/50-modal-usage-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/52-modal-usage-persistent.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/55-modal-usage-form.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/999-modal-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/trigger/35-trigger-advanced-usage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-results.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/certification-exam/acd-certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-quick-filters.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
  packages/components/bolt-listing-teaser/package.json
  packages/components/bolt-trigger/__tests__/trigger.e2e.js
  yarn.lock
Labels: type: feature

#2197 DS-464 add bell and flag icons
  packages/components/bolt-icon/icon.schema.json
  packages/components/bolt-icons/src/svgs/utility/bell-solid.svg
  packages/components/bolt-icons/src/svgs/utility/flag-solid.svg
Labels: type: feature

#2192 CC-472 Add reply prop and rename more_info prop to description in Listing Teaser
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/05-listing-teaser.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/10-listing-teaser-signifier.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/15-listing-teaser-headline.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/20-listing-teaser-status-and-action.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/25-listing-teaser-meta-data-and-more.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/30-listing-teaser-reply.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/35-listing-teaser-use-case-academy.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/40-listing-teaser-use-case-collaboration-center.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-use-case-article-list.twig
  packages/components/bolt-listing-teaser/__tests__/__snapshots__/listing-teaser.js.snap
  packages/components/bolt-listing-teaser/__tests__/listing-teaser.js
  packages/components/bolt-listing-teaser/listing-teaser.schema.js
  packages/components/bolt-listing-teaser/src/listing-teaser.scss
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
  yarn.lock
Labels: type: bugfix

#2200 Add wiki images
  docs-site/src/assets/images/wiki/poc-banner/banner-anatomy.png
  docs-site/src/assets/images/wiki/poc-banner/banner-dark-mode.jpg
  docs-site/src/assets/images/wiki/poc-banner/banner-inline.gif
  docs-site/src/assets/images/wiki/poc-banner/banner-inline.jpg
  docs-site/src/assets/images/wiki/poc-banner/banner-toast.gif
  docs-site/src/assets/images/wiki/poc-banner/banner-toast.jpg
  docs-site/src/assets/images/wiki/poc-banner/banner-validation.jpg
  docs-site/src/assets/images/wiki/poc-navbar/navbar-desktop.png
  docs-site/src/assets/images/wiki/poc-navbar/navbar.gif
  docs-site/src/assets/images/wiki/poc-table/table-checkbox.gif
  docs-site/src/assets/images/wiki/poc-table/table-filters.gif
  docs-site/src/assets/images/wiki/poc-table/table-row-expand.gif
  docs-site/src/assets/images/wiki/poc-table/table-sort.gif
  docs-site/src/assets/images/wiki/poc-tabs/tabs-desktop.png
  docs-site/src/assets/images/wiki/poc-tabs/tabs-dropdown.gif
  docs-site/src/assets/images/wiki/poc-tabs/tabs-scroll.gif
  yarn.lock
Labels: type: docs

#2199 Update repo README
  README.md
Labels: type: docs

#2195 WWW-739: Video Load Update
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/25-teaser-type-and-time.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
  packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
Labels: type: feature

#2202 Release 3.6.0
  auto-release.js
Labels: type: feature, version: minor

#2205 Release 3.6.0
  auto-release.js
Labels: type: feature, version: minor

#2204 WWW-476: Share URL Update
  docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/30-band-with-pinned-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/20-listing-teaser-status-and-action.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/60-listing-teaser-use-case-article-list.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/65-listing-teaser-use-case-search-result-list.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/share/00-share-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/share/05-share.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/share/_share-variables.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/00-d8-news-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/05-d8-browse-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/20-d8-details-page-press.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/40-d8-content-hub/00-sticky-navbar.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/45-d8-blog/05-blog-post.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/_wip-doc-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/accordion/00-accordion-no-shadow.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/share/05-share.twig
  packages/components/bolt-menu/menu.schema.js
  packages/components/bolt-share/__tests__/__snapshots__/share.js.snap
  packages/components/bolt-share/__tests__/share.js
  packages/components/bolt-share/share.schema.js
  packages/components/bolt-share/src/share.twig
  packages/components/bolt-teaser/__tests__/teaser.js
Labels: type: feature

#2209 Hotfix v3.6.1
  docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/30-band-with-pinned-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/20-listing-teaser-status-and-action.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/60-listing-teaser-use-case-article-list.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/65-listing-teaser-use-case-search-result-list.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/share/00-share-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/share/05-share.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/share/_share-variables.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/00-d8-news-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/05-d8-browse-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/20-d8-details-page-press.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/40-d8-content-hub/00-sticky-navbar.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/45-d8-blog/05-blog-post.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/_wip-doc-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/accordion/00-accordion-no-shadow.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/share/05-share.twig
  packages/components/bolt-menu/menu.schema.js
  packages/components/bolt-share/__tests__/__snapshots__/share.js.snap
  packages/components/bolt-share/__tests__/share.js
  packages/components/bolt-share/share.schema.js
  packages/components/bolt-share/src/share.twig
  packages/components/bolt-teaser/__tests__/teaser.js
Labels: version: patch

#2214 WWW-745: Allow attributes to be passed from share to copy to clipboard
  packages/components/bolt-share/src/share.twig
Labels: version: patch

#2215 WWW-745 share copy attributes
  packages/components/bolt-share/src/share.twig
Labels: version: patch
