Repository boltdesignsystem/bolt, pull requests merged in 2021-06, with the labels that each got.

#2216 DS-481: Fix popover/tooltip when shadow dom disabled
  docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/05-popover-no-shadow.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/tooltip/00-tooltip-no-shadow.twig
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
Labels: type: bugfix

#2206 DS-435 Standardize Twig and Schema (Card)
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/_info-density.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/50-card-replacement-border-radius.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/modals/_test-completed-modal--after-submit.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/modals/_test-completed-modal--before-submit.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/certification-exam/acd-certification-exam-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/module-landing/acd-module-landing-page.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/card/05-card.twig
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-card-replacement/__tests__/card-replacement.js
  packages/components/bolt-card-replacement/card-replacement.schema.js
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action-item.twig
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
  packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-actions.twig
  packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
Labels: type: feature

#2222 upgrade chromedriver, lock file
  yarn.lock
Labels: type: bugfix

#2225 Remove failing SSR nightwatch test and related SSR button code
  docs-site/__tests__/server-side-rendering.e2e.js
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/999-button-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/ssr-examples/-test-button-ssr--twig-plus-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/ssr-examples/-test-button-ssr--twig.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/ssr-examples/-test-button-ssr--web-component-wo-shadow-dom.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/button/ssr-examples/-test-button-ssr--web-component.twig
  packages/components/bolt-button/__tests__/button-wc.test.js
Labels: type: bugfix

#2224 Hotfix: paragraph spacing
  docs-site/__tests__/server-side-rendering.e2e.js
  packages/global/styles/03-generic/_generic-reset.scss
  packages/global/styles/03-generic/_generic-shared.scss
  packages/global/styles/04-elements/_elements-misc.scss
  packages/global/styles/index.scss
  yarn.lock
Labels: version: patch

#2210 DS-435: Card Test Update
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-card-replacement/__tests__/card-replacement.js
Labels: type: feature

#2217 DS-339 Replace old Card in PL
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/55-band-collection.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/25-carousel-basic-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/30-carousel-advanced-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/70-form-card-theme-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/05-d8-browse-page.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/30-d8-partners/00-d8-partners-search.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/00-event-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/05-event-detail.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/10-event-form-example.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/40-d8-content-hub/00-sticky-navbar.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/45-d8-blog/00-blog-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/50-d8-careers/00-careers-homepage.twig
Labels: type: feature

#2219 DS-490: jest test image update
  packages/components/bolt-image/__tests__/__snapshots__/image.js.snap
  packages/components/bolt-image/__tests__/image.js
  packages/components/bolt-image/__tests__/image.test.js
  packages/components/bolt-image/src/lazysizes.js
Labels: type: feature

#2185 DS-411: Component Test Refactor
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-blockquote/__tests__/blockquote.js
  packages/components/bolt-breadcrumb/__tests__/__snapshots__/breadcrumb.js.snap
  packages/components/bolt-breadcrumb/__tests__/breadcrumb.js
  packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
  packages/components/bolt-tabs/__tests__/tabs.js
  packages/testing/testing-helpers/index.js
  packages/twig-integration/twig-renderer-endpoint/index.test.js
Labels: type: feature

#2229 DS-467 remove card deprecations
  packages/components/bolt-card-replacement/card-replacement.schema.js
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
Labels: type: feature

#2231 Revert "DS-432: Remove deprecated props from link component"
  packages/components/bolt-link/link.schema.js
  packages/components/bolt-link/src/link.twig
Labels: type: feature

#2232 DS-335 Set up site layout
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/site/00-site-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/site/05-site.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/layouts/bolt-site/CHANGELOG.md
  packages/layouts/bolt-site/README.md
  packages/layouts/bolt-site/index.scss
  packages/layouts/bolt-site/package.json
  packages/layouts/bolt-site/site.schema.js
  packages/layouts/bolt-site/src/site.scss
  packages/layouts/bolt-site/src/site.twig
Labels: type: feature

#2233 DS-499 Update Navbar offset props
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/-navbar-use-case-multiple.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/-navbar-use-case-scroll-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/-navbar-use-case-sticky-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/35-navbar-scroll-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/40-navbar-sticky-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/45-navbar-multiple.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/50-navbar-custom-content.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/30-navbar-with-offsets.twig
  packages/components/bolt-navbar/navbar.schema.js
  packages/components/bolt-navbar/src/navbar.js
  packages/components/bolt-navbar/src/navbar.scss
  packages/components/bolt-navbar/src/navbar.twig
Labels: type: feature

#2236 DS-248 Add navbar 'static' doc
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/25-navbar-static.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/30-navbar-theme.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/35-navbar-hide-title-text.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/40-navbar-scroll-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/45-navbar-sticky-offset.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/50-navbar-multiple.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/navbar/55-navbar-custom-content.twig
Labels: type: feature

#2237 DS-248 Update sticky classes
  packages/components/bolt-navbar/__tests__/__snapshots__/navbar.js.snap
  packages/components/bolt-navbar/src/navbar.js
  packages/components/bolt-navbar/src/navbar.twig
  packages/components/bolt-page-header/src/page-header.twig
  packages/components/bolt-sticky/index.js
  packages/components/bolt-sticky/package.json
  packages/components/bolt-sticky/src/sticky.js
  yarn.lock
Labels: type: feature

#1252 Modal carousel doc page
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/_wip-modal-usage-carousel.twig
Labels: type: docs

#2238 Release v4.0.0
  .travis.yml
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/_wip-modal-usage-carousel.twig
Labels: breaking change, version: major

#2239 Release 4.0.0
  auto-release.js
Labels: breaking change, version: major

#2240 Release v4.0.0
  auto-release.js
Labels: breaking change, version: major

#2242 DS-528 Fix PL homepage navbar
  docs-site/src/templates/homepage.twig
  packages/components/bolt-navbar/src/navbar.scss
Labels: type: bugfix

#2243 Hotfix v4.0.1
  docs-site/src/templates/homepage.twig
  packages/components/bolt-navbar/src/navbar.scss
Labels: version: patch

#2244 Hotfix v4.0.1
  package.json
Labels: version: patch

#2247 Add icon-only class to element button docs.
  docs-site/src/pages/pattern-lab/_patterns/20-elements/button/25-button-with-icon-only.twig
Labels: type: docs

#2241 DS-486: Jest Test Button/Link Update
  packages/elements/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/elements/bolt-button/__tests__/button.js
  packages/elements/bolt-text-link/__tests__/__snapshots__/text-link.js.snap
  packages/elements/bolt-text-link/__tests__/text-link.js
Labels: type: feature

#2211 Update the z-index for tooltip and popover
  docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/10-popover-boundary.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/tooltip/10-tooltip-boundary.twig
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-popover/src/popover.scss
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/src/tooltip.scss
Labels: type: bugfix
