Repository boltdesignsystem/bolt, pull requests merged in 2021-01, with the labels that each got.

#2051 Fixed a Brightcove CSS error for the new player
  packages/components/bolt-video/brightcove/_video.scss
Labels: type: feature

#2050 DS-284: Update device-viewer renderer
  packages/components/bolt-device-viewer/src/device-viewer.standalone.js
Labels: type: feature

#2052 DS-285: Update dropdown to the latest renderer
  packages/components/bolt-dropdown/dropdown.js
  packages/components/bolt-dropdown/dropdown.scss
  packages/components/bolt-dropdown/index.js
Labels: type: feature

#2048 DS-181: Remove enums from booleans in schema files
  docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/15-action-blocks-borderless-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/25-band-full-bleed-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/list/30-list-inset-variations.twig
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-accordion/accordion-item.schema.js
  packages/components/bolt-accordion/accordion.schema.js
  packages/components/bolt-action-blocks/__tests__/action-blocks.js
  packages/components/bolt-action-blocks/action-blocks.schema.js
  packages/components/bolt-band/band.schema.js
  packages/components/bolt-carousel/carousel.schema.js
  packages/components/bolt-image/image.schema.js
  packages/components/bolt-list/__tests__/list.js
  packages/components/bolt-list/list.schema.js
  packages/components/bolt-navbar/navbar.schema.js
  packages/components/bolt-table/__tests__/table.js
  packages/components/bolt-table/table.schema.js
  packages/components/bolt-text/text.schema.js
Labels: type: feature

#2053 Brightcove CSS Update
  packages/components/bolt-video/brightcove/_video.scss
Labels: type: feature

#2056 DS-290: Update Constructor on image and link
  packages/components/bolt-image/src/image.js
  packages/components/bolt-link/src/link.js
Labels: type: feature

#2055 DS-280: Update Chip and Trigger to the Newest Renderer
  packages/components/bolt-chip/chip.schema.js
  packages/components/bolt-chip/src/chip.js
  packages/components/bolt-menu/__tests__/__snapshots__/menu.js.snap
  packages/components/bolt-trigger/__tests__/__snapshots__/trigger.js.snap
  packages/components/bolt-trigger/src/trigger.js
  packages/components/bolt-trigger/trigger.schema.js
  packages/components/bolt-video/src/video.standalone.js
  packages/core-v2.x/elements/bolt-action/README.md
  packages/core-v2.x/elements/bolt-action/index.js
  packages/core-v2.x/package.json
  packages/core-v2.x/utils/index.js
  packages/core-v3.x/elements/bolt-action/README.md
  packages/core-v3.x/elements/bolt-action/index.js
  packages/core-v3.x/elements/index.js
  packages/core-v3.x/package.json
  packages/core-v3.x/utils/index.js
  yarn.lock
Labels: type: feature

#2059 Fix: tabs show more button active color
  packages/components/bolt-tabs/src/tabs.scss
  packages/core-v3.x/styles/01-settings/settings-global/_settings-global.scss
Labels: type: bugfix

#2057 DS-292 Fix `:host` and `[attribute]` css
  packages/components/bolt-banner/src/banner.scss
  packages/components/bolt-button/src/button.scss
  packages/components/bolt-menu/src/_menu-item.scss
  packages/components/bolt-menu/src/menu.scss
  packages/components/bolt-stack/src/stack.scss
Labels: type: bugfix

#2060 DS-238: Add support for 3.x releases
  .autorc
  .travis.yml
  auto-release.js
Labels: type: feature

#2062 DS-238: Comment-out failing Nightwatch test
  packages/components/bolt-typeahead/__tests__/typeahead.e2e.js
Labels: type: bugfix

#2058 Docs: fix pattern lab theming and color docs
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/10-theming-system.twig
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/_color-swatch.scss
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/05-spacing/_spacing.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/_wip-global-search.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/styles/_global-search.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/styles/index.scss
Labels: type: docs

#2066 DS-295 remove xsmall icon size
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/search/_search-results--results-list.twig
  packages/components/bolt-icon/icon.schema.json
Labels: type: bugfix

#2067 Fix: academy colors and xxdark theme
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
  packages/global/styles/00-vars/_vars-mode.scss
Labels: type: bugfix

#2071 Fix: secondary color variable
  packages/global/styles/00-vars/_vars-mode.scss
Labels: type: bugfix

#2070 DS-300 Fix Slotify empty component bug
  packages/base-element/src/Slotify.js
Labels: type: bugfix

#2068 Whitelist "build-tools" to prevent warning on `yarn start`
  packages/build-tools/utils/manifest.get-pkg-info.js
Labels: type: bugfix

#2074 Fix: remove bolt-button[type] browser defaults
  packages/components/bolt-button/src/button.scss
Labels: type: bugfix

#2076 DS-306 fix desktop primary nav full width item
  packages/components/bolt-page-header/src/_page-header-desktop.scss
Labels: type: bugfix

#2081 Hotfix: Filter out `style` prop from button WC
  packages/components/bolt-button/src/button.js
Labels: version: patch

#2082 Hotfix/DS-238 Build updates
  packages/base-element/index.js
  packages/base-lazy-queue/index.mjs
  packages/base-lazy-queue/package.json
  packages/build-tools/cli.js
  packages/build-tools/create-webpack-config.js
Labels: version: patch

#2083 Hotfix/DS-238 yarn lock
  yarn.lock
Labels: version: patch

#2063 DS-294: update action-block twig conventions
  packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
  packages/components/bolt-action-blocks/action-blocks.schema.js
  packages/components/bolt-action-blocks/src/action-blocks.twig
Labels: type: feature

#2084 DS-315 Fix icon schema formatting
  packages/build-tools/tasks/icon-tasks.js
  packages/components/bolt-icon/icon.schema.json
Labels: type: bugfix

#2077 DS-302: Band twig update
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/35-background-valign-variations.twig
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-band/band.schema.js
  packages/components/bolt-band/src/band.twig
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/components/bolt-sticky/__tests__/__snapshots__/sticky.js.snap
Labels: type: feature

#2088 DS-297 Update background twig to latest conventions
  packages/components/bolt-background/src/background-item.twig
  packages/components/bolt-background/src/background-overlay.twig
  packages/components/bolt-background/src/background-shapes-wrapper.twig
  packages/components/bolt-background/src/background.scss
  packages/components/bolt-background/src/background.twig
Labels: type: feature
