Repository boltdesignsystem/bolt, pull requests merged in 2021-09, with the labels that each got.

#2309 Upgrade chromedriver
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#2298 Fix read-only repo publishing
  scripts/release/update-read-only-git-repos.sh
Labels: type: bugfix

#2278 DS-520 Refactor Page Footer component
  docs-site/.boltrc.js
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-footer/00-page-footer-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-footer/05-page-footer.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-footer/_page-footer.twig
  packages/base-starter-kit/.boltrc.js
  packages/components/bolt-page-footer/_page-footer.twig
  packages/components/bolt-page-footer/index.js
  packages/components/bolt-page-footer/index.scss
  packages/components/bolt-page-footer/package.json
  packages/components/bolt-page-footer/page-footer-nav-li.schema.js
  packages/components/bolt-page-footer/page-footer-nav-ul.schema.js
  packages/components/bolt-page-footer/page-footer.schema.js
  packages/components/bolt-page-footer/page-footer.scss
  packages/components/bolt-page-footer/page-footer.twig
  packages/components/bolt-page-footer/src/page-footer-nav-li.twig
  packages/components/bolt-page-footer/src/page-footer-nav-ul.twig
  packages/components/bolt-page-footer/src/page-footer.js
  packages/components/bolt-page-footer/src/page-footer.scss
  packages/components/bolt-page-footer/src/page-footer.twig
  packages/testing/testing-utils/__tests__/test-utils.test.js
Labels: type: feature

#2313 WWW-920: add title and chip to video-thumbnail
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/05-video-thumbnail.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/10-video-thumbnail-aspect-ratio.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/15-video-thumbnail-border-radius.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/20-video-thumbnail-title-and-chips.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/25-video-thumbnail-use-case-modal.twig
  packages/components/bolt-video-thumbnail/src/video-thumbnail.scss
  packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
  packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
Labels: type: feature

#2314 WWW-960: mobile nav top link color
  packages/components/bolt-page-header/src/_page-header-settings-and-tools.scss
Labels: type: feature

#2310 DS-599: Optimized Campaign Landing Page
  docs-site/src/assets/images/backgrounds/ocpl-bg-1.svg
  docs-site/src/assets/images/backgrounds/ocpl-bg-2.svg
  docs-site/src/assets/images/backgrounds/ocpl-bg-3.svg
  docs-site/src/assets/images/backgrounds/ocpl-bg-4.svg
  docs-site/src/assets/images/backgrounds/ocpl-bg-5.svg
  docs-site/src/assets/images/backgrounds/ocpl-bg-6.svg
  docs-site/src/assets/images/backgrounds/ocpl-contact-bg-1.svg
  docs-site/src/assets/images/backgrounds/ocpl-contact-bg-2.svg
  docs-site/src/assets/images/backgrounds/ocpl-contact-bg-3.jpg
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-05-oclp-gated-pdf.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-10-oclp-gated-external-link.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-15-oclp-gated-video.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-20-oclp-ungated-others.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-25-oclp-ungated-video.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/00-oclp-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/05-oclp-gated-pdf.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/10-oclp-gated-external-link.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/15-oclp-gated-video.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/20-oclp-ungated-others.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/25-oclp-ungated-video.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/oclp.scss
  docs-site/src/pages/pattern-lab/_patterns/999-tests/optimized-campaign-landing/00-oclp-page-theme-1.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/optimized-campaign-landing/05-oclp-page-theme-2.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/optimized-campaign-landing/10-oclp-page-theme-3.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/optimized-campaign-landing/15-oclp-page-theme-4.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/optimized-campaign-landing/20-oclp-page-theme-5.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/optimized-campaign-landing/25-oclp-page-theme-6.twig
  packages/elements/bolt-button/src/button.scss
  packages/elements/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/elements/bolt-icon/icon.schema.json
  packages/elements/bolt-icon/src/icons/pega-download-pdf.twig
  packages/elements/bolt-icon/src/svgs/pega-download-pdf.svg
  packages/elements/bolt-text-link/src/text-link.scss
  packages/layouts/bolt-layout/layout.schema.js
  packages/layouts/bolt-layout/src/layout-item.twig
  packages/layouts/bolt-layout/src/layout.scss
Labels: type: feature

#2303 DS-603 and DS-611 docs layout enhancements
  docs-site/src/pages/pattern-lab/_patterns/40-components/side-nav/00-side-nav-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/side-nav/05-side-nav.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/70-community/-community-doc-layout.twig
  packages/components/bolt-side-nav/side-nav-li.schema.js
  packages/components/bolt-side-nav/src/side-nav-li.twig
  packages/components/bolt-side-nav/src/side-nav.scss
  packages/layouts/bolt-holy-grail/src/holy-grail.scss
Labels: type: feature

#2312 DS-529: Pega.com: Add 'Download slides' CTA to PW Replays "Best Of" cards
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-05-boc-homepage-phase0.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-10-boc-gallery-phase0.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-15-boc-homepage-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-20-boc-gallery-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-25-boc-listing-pegaworld-phase1.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-30-boc-homepage-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-35-boc-gallery-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-40-boc-listing-pegaworld-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-45-boc-listing-customers-phase2.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/05-boc-homepage-phase0.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/10-boc-gallery-phase0.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/15-boc-homepage-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/20-boc-gallery-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/25-boc-listing-pegaworld-phase1.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/30-boc-homepage-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/35-boc-gallery-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/40-boc-listing-pegaworld-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/45-boc-listing-customers-phase2.md
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
  packages/components/bolt-teaser/teaser.schema.js
  packages/core-v3.x/styles/02-tools/tools-inline-icon-wrapper/_tools-inline-icon-wrapper.scss
Labels: type: feature

#2316 DS-582 Add information about twig file name on schema section
  docs-site/src/components/pattern-lab-utils/schema-docs.twig
  packages/components/bolt-navbar/navbar-li.schema.js
  packages/components/bolt-navbar/navbar-ul.schema.js
  packages/layouts/bolt-layout/layout-item.schema.js
Labels: type: feature

#2319 DS-600 Replace Link in Headline Component
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-headline/package.json
  packages/components/bolt-headline/src/_typography.twig
Labels: type: feature

#2322 DS-391 Image documentation
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated/-05-image.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated/-10-image-size-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated/-15-image-source-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated/-20-image-lazyload-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated/-25-image-custom-width-height-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated/-35-image-with-web-components.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/image-deprecated/00-deprecated-image-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/image/00-image-docs.twig
Labels: type: feature

#2324 Fix: layout demo typos
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-10-layout-template.twig
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-15-layout-sub-template.twig
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-35-layout-horizontal-alignment.twig
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-40-layout-vertical-alignment.twig
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-45-layout-item-vertical-alignment.twig
  docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-50-layout-item-order.twig
Labels: type: docs

#2328 Update chromedriver
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#2320 DS-594 Replace component-icons in Elements and Components
  packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
  packages/components/bolt-action-blocks/__tests__/action-blocks.js
  packages/components/bolt-action-blocks/package.json
  packages/components/bolt-action-blocks/src/action-block.twig
  packages/components/bolt-content-pagination/package.json
  packages/components/bolt-copy-to-clipboard/__tests__/__snapshots__/copy-to-clipboard.js.snap
  packages/components/bolt-copy-to-clipboard/__tests__/copy-to-clipboard.js
  packages/components/bolt-copy-to-clipboard/package.json
  packages/components/bolt-listing-teaser/package.json
  packages/components/bolt-listing-teaser/src/listing-teaser.scss
  packages/components/bolt-menu/src/_menu-item.scss
  packages/components/bolt-page-footer/package.json
  packages/components/bolt-page-footer/src/page-footer-nav-ul.twig
  packages/components/bolt-pagination/__tests__/__snapshots__/pagination.js.snap
  packages/components/bolt-pagination/src/pagination.twig
  packages/components/bolt-share/package.json
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-teaser/__tests__/teaser.js
  packages/components/bolt-teaser/src/teaser.twig
  packages/components/bolt-teaser/teaser.schema.js
  packages/elements/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/elements/bolt-button/__tests__/button.js
  packages/elements/bolt-button/button.schema.js
  packages/elements/bolt-button/package.json
  packages/elements/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/elements/bolt-icon/src/icon.scss
  packages/elements/bolt-icon/src/icons/chevron-down.twig
  packages/elements/bolt-icon/src/icons/chevron-left.twig
  packages/elements/bolt-icon/src/icons/chevron-right.twig
  packages/elements/bolt-icon/src/icons/chevron-up.twig
  packages/elements/bolt-icon/src/svgs/chevron-down.svg
  packages/elements/bolt-icon/src/svgs/chevron-left.svg
  packages/elements/bolt-icon/src/svgs/chevron-right.svg
  packages/elements/bolt-icon/src/svgs/chevron-up.svg
  packages/elements/bolt-text-link/__tests__/__snapshots__/text-link.js.snap
  packages/elements/bolt-text-link/__tests__/text-link.js
  packages/elements/bolt-text-link/package.json
  packages/elements/bolt-text-link/text-link.schema.js
Labels: type: feature

#2325 DS-609 Custom icon workflow
  docs-site/src/pages/pattern-lab/_patterns/20-elements/icon/20-icon-use-case-custom-svg.twig
  packages/elements/bolt-icon/icon.schema.json
  packages/elements/bolt-icon/src/icon.twig
Labels: type: feature

#2327 WWW-920 Add preview image chip and re-order preview and checklist in mobile view
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-05-oclp-gated-pdf.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-10-oclp-gated-external-link.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-15-oclp-gated-video.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/oclp.scss
Labels: type: feature

#2258 Twig 2 upgrade (Drupal 9 compatibility)
  docs-site/.patches/addTwigGlobals.patch
  docs-site/composer.json
  docs-site/composer.lock
  packages/testing/testing-helpers/package.json
  packages/twig-integration/drupal-module/bolt_connect.info.yml
  packages/twig-integration/drupal-module/bolt_connect.services.yml
  packages/twig-integration/drupal-module/composer.json
  packages/twig-integration/drupal-module/src/BoltConnectTwigNamespaces.php
  packages/twig-integration/twig-extensions-shared/composer.json
  packages/twig-integration/twig-extensions-shared/composer.lock
  packages/twig-integration/twig-renderer/composer.json
  packages/twig-integration/twig-renderer/composer.lock
  packages/twig-integration/twig-renderer/package.json
  yarn.lock
Labels: type: feature

#2332 Nuke obsolete docs
  docs-site/__tests__/docs-site-nav.e2e.js
  docs-site/__tests__/homepage.e2e.js
  docs-site/src/pages/docs/00-getting-started/00-index.md
  docs-site/src/pages/docs/00-index.md
  docs-site/src/pages/docs/25-design-principles/00-index.md
  docs-site/src/pages/docs/25-design-principles/05-accessibility.md
  docs-site/src/pages/docs/25-design-principles/10-interface-copy.md
  docs-site/src/pages/docs/45-development/00-index.md
  docs-site/src/pages/docs/45-development/00-standards-and-best-practices/00-index.md
  docs-site/src/pages/docs/45-development/00-standards-and-best-practices/10-architecture-principles.md
  docs-site/src/pages/docs/45-development/00-standards-and-best-practices/10-javascript.md
  docs-site/src/pages/docs/45-development/01-local-dev-environment-setup.md
  docs-site/src/pages/docs/45-development/10-server-side-rendering.md
  docs-site/src/pages/docs/45-development/20-sassdocs.md
  docs-site/src/pages/docs/45-development/25-patching=npm-package.md
  docs-site/src/pages/docs/45-development/30-build-tools/00-index.md
  docs-site/src/pages/docs/45-development/30-build-tools/01-boltrc-config.md
  docs-site/src/pages/docs/45-development/30-build-tools/10-basic-config.md
  docs-site/src/pages/docs/45-development/30-build-tools/20-components.md
  docs-site/src/pages/docs/45-development/30-build-tools/30-envs.md
  docs-site/src/pages/docs/45-development/30-build-tools/40-internationalization.md
  docs-site/src/pages/docs/45-development/30-build-tools/_40-extras.md
  docs-site/src/pages/docs/45-development/50-developer-tools/00-index.md
  docs-site/src/pages/docs/45-development/50-developer-tools/10-using-xdebug-for-PHP.md
  docs-site/src/pages/docs/45-development/70-testing-standards/00-index.md
  docs-site/src/pages/docs/45-development/70-testing-standards/10-js-testing-standards.md
  docs-site/src/pages/docs/45-development/70-testing-standards/20-manual-testing-standards.md
  docs-site/src/pages/docs/45-workflow-and-process/00-index.md
  docs-site/src/pages/docs/45-workflow-and-process/10-release-types.md
  docs-site/src/pages/docs/45-workflow-and-process/20-cutting-a-release.md
  docs-site/src/pages/docs/50-guides/00-index.md
  docs-site/src/pages/docs/50-guides/10-browser-support.md
  docs-site/src/pages/docs/50-guides/10-install-component.md
  docs-site/src/pages/docs/50-guides/15-building-a-new-component.md
  docs-site/src/pages/docs/50-guides/20-troubleshooting.md
  docs-site/src/pages/docs/50-guides/30-adding-custom-icons.md
  docs-site/src/pages/docs/50-guides/40-road-runner-rules.md
  docs-site/src/pages/docs/50-guides/50-tips-on-building-web-components.md
  docs-site/src/pages/docs/50-guides/60-migrating-to-3.x.md
  docs-site/src/pages/docs/_00-faq.md
  docs-site/src/pages/docs/_00-resources.md
  docs-site/src/pages/docs/_15-whats-new-in-bolt-v1.md
  docs-site/src/pages/docs/_20-releases.md
  docs-site/src/pages/docs/_30-ui-patterns/00-index.md
  docs-site/src/pages/docs/_30-ui-patterns/bands.md
  docs-site/src/pages/docs/_30-ui-patterns/blockquotes.md
  docs-site/src/pages/docs/_30-ui-patterns/buttons.md
  docs-site/src/pages/docs/_30-ui-patterns/cards.md
  docs-site/src/pages/docs/_30-ui-patterns/forms.md
  docs-site/src/pages/docs/_40-visual-language/00-index.md
  docs-site/src/pages/docs/_40-visual-language/10-colors.md
  docs-site/src/pages/docs/_40-visual-language/20-typography.md
  docs-site/src/pages/docs/_40-visual-language/30-iconography.md
  docs-site/src/pages/docs/_40-visual-language/40-spacing.md
  docs-site/src/templates/_navbar-with-version-selector.twig
  docs-site/src/templates/_page-header.twig
  docs-site/src/templates/default-redesign.twig
  docs-site/src/templates/default.twig
  docs-site/src/templates/homepage.twig
  docs-site/src/templates/sassdoc.twig
Labels: type: docs

#2317 DS-483 Code Snippet rebuild
  docs-site/src/components/pattern-lab-utils/docs.twig
  docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/article/05-article.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/00-code-snippet-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/05-code-snippet.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/10-code-snippet-display-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/10-code-snippet-language.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/15-code-snippet-language-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/15-code-snippet-mode.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/20-code-snippet-custom-language-label.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/20-code-snippet-syntax-variation.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/25-code-snippet-header-display.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/999-code-snippet-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/code-snippet/00-code-snippet-languages.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/code-snippet/05-code-snippet-lang-none.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/code-snippet/10-code-snippet-escape-html.twig
  packages/components/bolt-code-snippet/__tests__/__snapshots__/code-snippet.js.snap
  packages/components/bolt-code-snippet/__tests__/code-snippet.js
  packages/components/bolt-code-snippet/code-snippet.schema.js
  packages/components/bolt-code-snippet/index.js
  packages/components/bolt-code-snippet/index.scss
  packages/components/bolt-code-snippet/package.json
  packages/components/bolt-code-snippet/src/_code-snippet-base.scss
  packages/components/bolt-code-snippet/src/_code-snippet-languages.js
  packages/components/bolt-code-snippet/src/_code-snippet-syntax-dark.scss
  packages/components/bolt-code-snippet/src/_code-snippet-syntax-light.scss
  packages/components/bolt-code-snippet/src/code-snippet.js
  packages/components/bolt-code-snippet/src/code-snippet.standalone.js
  packages/components/bolt-code-snippet/src/code-snippet.twig
  packages/core-v3.x/styles/02-tools/tools-text-link/_tools-text-link.scss
  packages/elements/bolt-text-link/src/text-link.scss
  yarn.lock
Labels: type: feature

#2337 Hotfix: DS-649 Navbar schema key name
  packages/components/bolt-navbar/src/navbar-li.twig
  packages/components/bolt-navbar/src/navbar-ul.twig
Labels: version: patch

#2338 Hotfix: DS-649 Navbar schema key name (take 2)
  packages/components/bolt-navbar/src/navbar-li.twig
  packages/components/bolt-navbar/src/navbar-ul.twig
Labels: version: patch
