Repository boltdesignsystem/bolt, pull requests merged in 2021-04, with the labels that each got.

#2154 WWW-606: Hover Description Text Update
  packages/components/bolt-teaser/src/teaser.scss
Labels: type: bugfix, version: patch

#2132 DS-333: replace onClick and onClickTarget with snake case
  jest.config.js
  packages/base-element/src/BoltActionElement.js
  packages/base-element/src/BoltActionElement.schema.js
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-button/src/button.twig
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-link/src/link.twig
  packages/components/bolt-trigger/__tests__/__snapshots__/trigger.js.snap
  packages/components/bolt-trigger/__tests__/trigger.js
  packages/components/bolt-trigger/src/trigger.twig
  packages/components/bolt-trigger/trigger.schema.js
Labels: type: feature

#2156 DS-447 Fix broken `renderWC` promise
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/testing/testing-helpers/index.js
Labels: type: feature

#2152 DS-427 Enhance Teaser description ellipsis display
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/35-teaser-text-options.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/40-teaser-description-on-hover.twig
  packages/components/bolt-tabs/index.js
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
Labels: type: feature

#2158 DS-418: 2.30 regression: Image modal scroll dragging overlay up
  packages/components/bolt-modal/src/modal.scss
Labels: type: bugfix

#2145 DS-372: Standardize Twig and Schema (Link)
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/_archive/examples/_text-carousel.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/typeahead/00-typeahead-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/heros/homepage-heros/_hero--hp-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/modals/_test-completed-modal--return-to-mission.twig
  packages/components/bolt-breadcrumb/__tests__/__snapshots__/breadcrumb.js.snap
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/link.schema.js
  packages/components/bolt-link/src/link.twig
Labels: type: feature

#2160 Fixed a active state color bug on the quick tabs
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/index.scss
Labels: type: bugfix

#2159 DS-488: PW Replay facets :On IOS mobile upon trying to apply the filter the save option is not in the viewport. Upon scrolling able to see the same
  packages/components/bolt-modal/src/modal.scss
Labels: type: bugfix

#2161 DS-449: Fix stacking order in FF
  packages/components/bolt-teaser/src/teaser.scss
Labels: type: feature

#2162 Release 3.5.0
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/_archive/examples/_text-carousel.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/35-teaser-text-options.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/40-teaser-description-on-hover.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/typeahead/00-typeahead-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/heros/homepage-heros/_hero--hp-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/modals/_test-completed-modal--return-to-mission.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/index.scss
  jest.config.js
  packages/base-element/src/BoltActionElement.js
  packages/base-element/src/BoltActionElement.schema.js
  packages/components/bolt-breadcrumb/__tests__/__snapshots__/breadcrumb.js.snap
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-button/src/button.twig
  packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
  packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
  packages/components/bolt-headline/src/_typography.twig
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-link/link.schema.js
  packages/components/bolt-link/src/link.twig
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-tabs/index.js
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
  packages/components/bolt-trigger/__tests__/__snapshots__/trigger.js.snap
  packages/components/bolt-trigger/__tests__/trigger.js
  packages/components/bolt-trigger/src/trigger.twig
  packages/components/bolt-trigger/trigger.schema.js
  packages/testing/testing-helpers/index.js
Labels: version: minor

#2157 WWW-467 Header tweaks
  packages/components/bolt-page-header/page-header.schema.js
  packages/components/bolt-page-header/src/page-header.twig
Labels: type: bugfix

#2163 DS-450 Fix stacking order of Teaser view count in FF
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
Labels: type: bugfix

#2164 Hotfix: DS-450 limit z-index to like and share buttons
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
Labels: version: patch

#2165 DS-141: Remove Unused Dependencies
  package.json
  yarn.lock
Labels: type: feature

#2166 DS-28: Intermittent build failures on Travis
  packages/components/bolt-accordion/__tests__/accordion.js
  packages/components/bolt-action-blocks/__tests__/action-blocks.js
  packages/components/bolt-background-shapes/__tests__/background-shapes.js
  packages/components/bolt-band/__tests__/band.js
  packages/components/bolt-banner/__tests__/banner.js
  packages/components/bolt-blockquote/__tests__/blockquote.js
  packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
  packages/components/bolt-button/__tests__/button.js
  packages/components/bolt-card-replacement/__tests__/card-replacement.js
  packages/components/bolt-carousel/__tests__/carousel.js
  packages/components/bolt-chip-list/__tests__/chip-list.js
  packages/components/bolt-chip/__tests__/chip.js
  packages/components/bolt-device-viewer/__tests__/device-viewer.js
  packages/components/bolt-figure/__tests__/figure.js
  packages/components/bolt-headline/__tests__/headline.js
  packages/components/bolt-icon/__tests__/icon.js
  packages/components/bolt-icons/__tests__/__snapshots__/icons.js.snap
  packages/components/bolt-icons/__tests__/icons.js
  packages/components/bolt-image/__tests__/image.js
  packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
  packages/components/bolt-link/__tests__/link.js
  packages/components/bolt-list/__tests__/list.js
  packages/components/bolt-listing-teaser/__tests__/listing-teaser.js
  packages/components/bolt-logo/__tests__/__snapshots__/logo.js.snap
  packages/components/bolt-logo/__tests__/logo.js
  packages/components/bolt-menu/__tests__/menu.js
  packages/components/bolt-modal/__tests__/modal.js
  packages/components/bolt-navbar/__tests__/navbar.js
  packages/components/bolt-pagination/__tests__/pagination.js
  packages/components/bolt-popover/__tests__/popover.js
  packages/components/bolt-progress-bar/__tests__/progress-bar.js
  packages/components/bolt-ratio/__tests__/__snapshots__/ratio.js.snap
  packages/components/bolt-ratio/__tests__/ratio.js
  packages/components/bolt-share/__tests__/share.js
  packages/components/bolt-stack/__tests__/stack.js
  packages/components/bolt-sticky/__tests__/sticky.js
  packages/components/bolt-table/__tests__/table.js
  packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
  packages/components/bolt-tabs/__tests__/tabs.js
  packages/components/bolt-teaser/__tests__/teaser.js
  packages/components/bolt-text/__tests__/text.js
  packages/components/bolt-toc/__tests__/toc.js
  packages/components/bolt-tooltip/__tests__/tooltip.js
  packages/components/bolt-typeahead/__tests__/typeahead.js
  packages/components/bolt-ul/__tests__/ul.js
  packages/testing/testing-helpers/index.js
Labels: type: feature

#2169 DS-28 Remove VRT tools
  jest.config.js
  packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js.snap
  packages/generators/yeoman-create-component/generators/component/templates/component.test.js
  packages/testing/testing-jest/jest-reporter-vrt.js
  packages/testing/testing-jest/jest-setup-files-after-env.js
  packages/testing/testing-jest/package.json
  patches/jest-image-snapshot+2.12.0.patch
  yarn.lock
Labels: type: feature

#2170 Fix `min-indent` error
  package.json
  packages/configs/stylelint-config/package.json
  yarn.lock
Labels: type: feature

#2171 DS-89 Remove font-loading code
  packages/core-v3.x/styles/01-settings/settings-font-family/_settings-font-family.scss
  packages/core-v3.x/styles/01-settings/settings-global/_settings-global.scss
  packages/servers/testing-server/index.js
Labels: type: feature

#2172 Upgrade chromedriver to 89 to fix Travis builds
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#2173 WWW-696 Fix Drupal escaping markup when using 'set foo = bar'.
  packages/components/bolt-share/src/share.twig
Labels: type: feature

#2176 Hotfix: WWW-696 Fix Drupal escaping markup when using 'set' in Share component
  packages/components/bolt-share/src/share.twig
Labels: version: patch

#2179 WWW-694: PW Replay facets :On IOS mobile upon trying to apply the filter the save option is not in the viewport. Upon scrolling able to see the same
  packages/components/bolt-modal/src/modal.js
Labels: version: patch

#2175 Fix lock-solid.svg to work with dark theme
  packages/components/bolt-icons/src/svgs/utility/lock-solid.svg
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
Labels: type: bugfix

#2181 Hotfix 3.4.4
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/35-teaser-text-options.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/40-teaser-description-on-hover.twig
  packages/components/bolt-share/src/share.twig
  packages/components/bolt-tabs/index.js
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
  packages/components/bolt-teaser/src/teaser.scss
  packages/components/bolt-teaser/src/teaser.twig
Labels: version: patch

#2177 DS-452: Rename Waypoint "target"
  packages/components/bolt-toc/src/_toc-item.js
  packages/components/bolt-toc/src/toc.js
  packages/core-v3.x/utils/waypoint/index.js
Labels: type: feature

#2046 DS-271: Support multiple schemas, nested `items` display
  docs-site/src/components/pattern-lab-utils/_schema-docs-macros.twig
  docs-site/src/components/pattern-lab-utils/docs.twig
  docs-site/src/components/pattern-lab-utils/schema-docs.twig
  packages/build-tools/utils/manifest.get-pkg-info.js
  packages/components/bolt-accordion/src/accordion.js
  packages/components/bolt-blockquote/src/blockquote.js
  packages/components/bolt-page-header/package.json
  packages/components/bolt-page-header/page-header-primary-nav.schema.js
  packages/components/bolt-page-header/page-header-search-panel.schema.js
  packages/components/bolt-page-header/src/page-header.twig
Labels: type: feature

#2186 Bugfix/ds 458 listing component fix auto escaping issues
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
Labels: type: bugfix

#2187 Hotfix v3.5.4
  packages/base-element/src/lib/decorators/json-schema-props.js
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
Labels: version: patch

#2180 Removed IE 11 specific code from the modal.js
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/custom-events/_modal-usage-custom-events.twig
  packages/components/bolt-modal/src/modal.js
  packages/core-v3.x/utils/scrollbar.js
Labels: type: feature

#2182 DS-389 Standardize Twig and Schema (Image)
  packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
  packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
  packages/components/bolt-device-viewer/__tests__/__snapshots__/device-viewer.js.snap
  packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
  packages/components/bolt-image/__tests__/__snapshots__/image.js.snap
  packages/components/bolt-image/src/image.twig
  packages/components/bolt-logo/__tests__/__snapshots__/logo.js.snap
  packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
Labels: type: feature
