Repository boltdesignsystem/bolt, pull requests merged in 2022-09, with the labels that each got.

#2536 DS-850: Fix edit button z-index bug
  docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
  packages/components/bolt-profile/src/profile.scss
Labels: type: feature

#2538 DS-839: Fix broken schema to fix full_bleed prop
  docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
  packages/components/bolt-profile/src/profile.twig
Labels: type: bugfix

#2539 Hotfix v5.7.3
  docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
  packages/components/bolt-profile/src/profile.scss
  packages/components/bolt-profile/src/profile.twig
Labels: version: patch

#2537 DS-579 Header Height HTML Attribute
  packages/components/bolt-page-header/src/page-header.js
Labels: type: feature

#2540 Enhance Teaser Functionality
  docs-site/src/pages/pattern-lab/_patterns/999-tests/teaser/05-teaser-video.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/teaser/10-teaser-video-card.twig
Labels: type: feature

#2546 CC-959: Hide instead of destroy Tippy instance on disconnect
  docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/15-popover-disconnected-callback.twig
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-tooltip/src/tooltip.js
Labels: type: feature

#2547 Hotfix v5.7.4
  docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/15-popover-disconnected-callback.twig
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-tooltip/src/tooltip.js
Labels: version: patch

#2549 Update twig version requirement to not be hard-coded.
  docs-site/composer.json
  docs-site/composer.lock
  packages/twig-integration/twig-extensions-shared/composer.json
Labels: version: patch
