Repository boltdesignsystem/bolt, pull requests merged in 2022-12, with the labels that each got.

#2577 DS-774: Close Popover when inner action is clicked
  docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/20-popover-close-on-action.twig
  packages/components/bolt-popover/src/popover.js
Labels: type: feature

#2579 DS 889: Drupal Admin UI Paternlab Section
  docs-site/src/index.scss
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/00-text-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/05-advanced-text-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/10-icon-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/15-image-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/20-button-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/25-blockquote-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/30-list-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/35-action-blocks-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/40-tabs-and-accordion-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/_drupal-admin-ui-template.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/_main-content.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/styles/index.scss
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-action-advanced-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-action.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-animation.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-avatar.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-icon-after-advanced-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-icon-after.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-icon-before-advanced-paragraph.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-icon-before.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-icon-only.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-item-alignment.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-item-options-accordion.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-item-options-action-blocks.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-item-options-tabs.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-logo.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-overrides.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-shape.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-spacing.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-visual-accordion.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-visual-blockquote.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tab-visual-tabs.twig
  docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/tabs/_tabs-set.twig
  packages/website-ui/uikit-workshop/src/scripts/actions/app.js
  packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav.js
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-toggle-hidden-folders/pl-toggle-hidden-folders.js
  packages/website-ui/uikit-workshop/src/scripts/localstorage.js
  packages/website-ui/uikit-workshop/src/scripts/reducers/app.js
Labels: type: feature

#2580 DS-868: Add description_clamp prop to Listing Teaser
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-line-clamp.twig
  packages/components/bolt-listing-teaser/listing-teaser.schema.js
  packages/components/bolt-listing-teaser/src/listing-teaser.scss
  packages/components/bolt-listing-teaser/src/listing-teaser.twig
Labels: type: feature

#2582 DS-893: Long strings in notifications causes some minor layout issues
  docs-site/src/pages/pattern-lab/_patterns/999-tests/notifications/00-notifications-long-strings.twig
  packages/components/bolt-notifications/src/notifications.scss
Labels: type: bugfix

#2578 [6.x] DS-855 Prep Bolt in Drupal
  docs-site/src/templates/_site-head.twig
  packages/base-element/package.json
  packages/build-tools/cli.js
  packages/build-tools/create-webpack-config.js
  packages/build-tools/package.json
  packages/build-tools/tasks/task-collections.js
  packages/build-tools/tasks/webpack-tasks.js
  packages/build-tools/utils/config.schema.yml
  packages/components/bolt-typeahead/package.json
  packages/components/bolt-typeahead/typeahead.autosuggest.js
  packages/configs/stylelint-config/ideal.js
  packages/configs/stylelint-config/package.json
  packages/experimental/editor/editor-in-pl.twig
  packages/servers/testing-server/index.js
  packages/website-ui/uikit-workshop/package.json
  packages/website-ui/uikit-workshop/src/scripts/components/pl-search/pl-search.js
  yarn.lock
Labels: type: feature

#2585 Update card media deprecation to check both src and attributes.src
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
Labels: version: patch

#2586 DS-902: Icon in the menu comp doesn't display in proper place
  docs-site/src/pages/pattern-lab/_patterns/40-components/menu/25-menu-use-case-icons.twig
  packages/components/bolt-menu/src/_menu-item.scss
  packages/components/bolt-menu/src/_menu-item.twig
Labels: type: bugfix

#2541 [6.x] DS-244 cleanup and refactor background component
  docs-site/src/pages/pattern-lab/_patterns/40-components/background/20-background-shapes.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/03-organisms/landing-page/_landing-page-inner-layout.twig
  packages/components/bolt-background/background.schema.js
Labels: type: feature
