Repository boltdesignsystem/bolt, pull requests merged in 2022-08, with the labels that each got.

#2521 DS-821 WWW: Button Icon Size Bug
  packages/elements/bolt-button/src/button.scss
Labels: type: bugfix

#2522 DS-811 Wrapper Element
  docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/00-wrapper-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/05-wrapper.twig
  docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/10-wrapper-use-case-custom-max-width.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
  packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
  packages/elements/bolt-wrapper/CHANGELOG.md
  packages/elements/bolt-wrapper/README.md
  packages/elements/bolt-wrapper/__tests__/__snapshots__/wrapper.js.snap
  packages/elements/bolt-wrapper/__tests__/wrapper.js
  packages/elements/bolt-wrapper/index.scss
  packages/elements/bolt-wrapper/package.json
  packages/elements/bolt-wrapper/src/wrapper.scss
  packages/elements/bolt-wrapper/src/wrapper.twig
  packages/elements/bolt-wrapper/wrapper.schema.js
Labels: type: feature

#2527 DS-834: Remove the medium animation duration
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/icon-test-fade-ins.twig
  packages/global/styles/06-animations/_animations.scss
Labels: type: feature

#2524 DS-694 Twig XSS Vulnerabilities
  docs-site/src/pages/pattern-lab/_patterns/20-elements/type/25-type-with-icon.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-sign-up.twig
  packages/components/bolt-teaser/src/teaser.twig
  packages/elements/bolt-button/src/button.twig
  packages/elements/bolt-text-link/src/text-link.twig
  packages/elements/bolt-type/src/type.twig
  packages/generators/bolt-generator/templates/element/element.twig
Labels: type: feature

#2480 Card/Video Thumbnail Update
  docs-site/src/custom-brightcove.js
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/35-card-replacement-with-video.twig
  packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
  packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
  packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
Labels: type: feature

#2529 DS-733: make tabs show-more button invisble by default
  packages/components/bolt-tabs/src/tabs.js
Labels: type: feature

#2520 DS-767 Remove usage of image component from card
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/_info-density.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/band/55-band-collection.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/00-card-replacement-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/05-card.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/06-card-horizontal.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/10-card-button-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/15-card-replacement-with-two-buttons.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/25-card-replacement-height-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/30-card-replacement-link-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/40-card-replacement-with-freeform-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/45-card-replacement-with-text-group.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/50-card-replacement-border-radius.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/55-card-replacement-spacing.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/card/999-card-replacement-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/25-carousel-basic-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/_archive/example-content/_carousel-slide-content.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/modal/_wip-modal-content-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/-page-header-example-main-site-anonymous.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/-page-header-example-main-site-with-subnav.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/_demo-main-site-page-header.twig
  docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/combos/-95-in-page-example.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/blog/blog-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/careers/careers-homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/content-hub/sticky-navbar.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/events/event-detail.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/homepage/homepage-japanese.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/homepage/homepage.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/partners/partners-search.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/press-and-media/news-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/_product-t3-extra-videos.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/_product-t3.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/product-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/product-t2.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/product-t4.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/card/05-card.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/card/10-card-links-and-buttons.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/dialog/30-dialog-from-card.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/trigger/00-trigger-card-modal.twig
  packages/components/bolt-card-replacement/card-replacement.schema.js
  packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
Labels: type: feature

#2531 DS-839: Add Edit Button to Profile Avatar
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-avatar-edit-button.twig
  packages/components/bolt-profile/package.json
  packages/components/bolt-profile/profile-avatar-edit-button.schema.js
  packages/components/bolt-profile/profile.schema.js
  packages/components/bolt-profile/src/profile-avatar-edit-button.twig
  packages/components/bolt-profile/src/profile.scss
  packages/components/bolt-profile/src/profile.twig
Labels: type: feature

#2532 Hotfix v5.7.1
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-avatar-edit-button.twig
  packages/components/bolt-profile/package.json
  packages/components/bolt-profile/profile-avatar-edit-button.schema.js
  packages/components/bolt-profile/profile.schema.js
  packages/components/bolt-profile/src/profile-avatar-edit-button.twig
  packages/components/bolt-profile/src/profile.scss
  packages/components/bolt-profile/src/profile.twig
  packages/components/bolt-tabs/src/tabs.js
Labels: version: patch

#2534 DS-839: Fix avatar edit button template
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-avatar-edit-button.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
  packages/components/bolt-profile/src/profile-avatar-edit-button.twig
Labels: type: feature

#2535 Hotfix v5.7.2
  docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-avatar-edit-button.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
  packages/components/bolt-profile/src/profile-avatar-edit-button.twig
Labels: version: patch

#2533 Patternlab Browser Support Link
  packages/website-ui/uikit-workshop/src/icons/browser-support.svg
  packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-tools-menu/pl-tools-menu.js
Labels: type: feature
