Repository boltdesignsystem/bolt, pull requests merged in 2022-04, with the labels that each got.

#2467 Fix: add proper navigation labels
  packages/components/bolt-page-footer/src/page-footer.twig
  packages/components/bolt-page-header/src/page-header-primary-nav.twig
Labels: type: feature

#2470 CC-843 remove fibers dependency
  packages/build-tools/package.json
  packages/website-ui/uikit-workshop/package.json
  yarn.lock
Labels: version: patch

#2466 DS-442: Holy Grail Layout Cookie
  packages/layouts/bolt-holy-grail/package.json
  packages/layouts/bolt-holy-grail/src/holy-grail.js
  yarn.lock
Labels: type: feature

#2449 DS-498 Close Nav on Anchor Click
  packages/components/bolt-page-header/src/page-header-nav.js
Labels: type: feature

#2465 DS-752 Remove unused docs-site components (Part 2)
  .eslintignore
  .stylelintrc
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/components/docs-search/CHANGELOG.md
  docs-site/src/components/docs-search/docs-search.js
  docs-site/src/components/docs-search/docs-search.scss
  docs-site/src/components/docs-search/index.js
  docs-site/src/components/docs-search/package.json
  docs-site/src/components/schema-form/CHANGELOG.md
  docs-site/src/components/schema-form/component-explorer.js
  docs-site/src/components/schema-form/component-explorer.scss
  docs-site/src/components/schema-form/grid-layout.js
  docs-site/src/components/schema-form/index.js
  docs-site/src/components/schema-form/package.json
  docs-site/src/components/schema-form/schema-form.js
  docs-site/src/components/schema-form/utils.js
  docs-site/src/components/shadow-toggle/CHANGELOG.md
  docs-site/src/components/shadow-toggle/index.js
  docs-site/src/components/shadow-toggle/package.json
  docs-site/src/components/shadow-toggle/shadow-toggle.js
  docs-site/src/components/shadow-toggle/shadow-toggle.twig
  package.json
  yarn.lock
Labels: type: feature

#2474 DS-756 Fix css animation selector
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/banner-test-fade-ins.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/gallery-test-fade-ins.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/icon-test-fade-ins.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/video-test-bounce-ins.twig
  packages/global/styles/06-animations/_999-animations-on-load-test.js
  packages/global/styles/06-animations/_animations.scss
Labels: type: bugfix

#2473 DS-732 Mobile | IOS Search icon is not visible in the search bar
  packages/components/bolt-form/src/form.scss
Labels: type: bugfix

#2476 DS-744 enhance table colors in additional color themes
  docs-site/.incache
  docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/10-theming-system.twig
  packages/components/bolt-table/src/table.scss
  packages/global/styles/00-vars/_vars-mode.scss
Labels: type: feature

#2477 DS-760 fix switch button label text
  docs-site/src/pages/pattern-lab/_patterns/40-components/switch-button/05-switch-button.twig
  packages/components/bolt-switch-button/__tests__/__snapshots__/switch-button.js.snap
  packages/components/bolt-switch-button/src/switch-button.twig
Labels: type: bugfix

#2423 DS-541 Floating Action Buttons
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-05a-floating-action-buttons-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-10a-floating-action-buttons-demo-show-on-scroll-selector.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-15a-floating-action-buttons-demo-toggle-button.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-999a-floating-action-buttons-demo-use-case-offsets.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/00-floating-action-buttons-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/05-floating-action-buttons.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/05-floating-action-buttons.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/05a-floating-action-buttons-demo.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/10-floating-action-buttons-show-on-scroll-selector.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/10-floating-action-buttons-show-on-scroll-selector.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/10a-floating-action-buttons-demo-show-on-scroll-selector.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/15-floating-action-buttons-toggle-button.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/15-floating-action-buttons-toggle-button.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/15a-floating-action-buttons-demo-toggle-button.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/999-floating-action-buttons-use-case-offsets.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/999-floating-action-buttons-use-case-offsets.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/999a-floating-action-buttons-demo-use-case-offsets.md
  docs-site/src/templates/_site-head.twig
  packages/base-starter-kit/.boltrc.js
  packages/base-starter-kit/package.json
  packages/components/bolt-floating-action-buttons/README.md
  packages/components/bolt-floating-action-buttons/__tests__/__snapshots__/floating-action-buttons.js.snap
  packages/components/bolt-floating-action-buttons/__tests__/floating-action-buttons.js
  packages/components/bolt-floating-action-buttons/floating-action-buttons-li.schema.js
  packages/components/bolt-floating-action-buttons/floating-action-buttons-toggle-button.schema.js
  packages/components/bolt-floating-action-buttons/floating-action-buttons-ul.schema.js
  packages/components/bolt-floating-action-buttons/floating-action-buttons.schema.js
  packages/components/bolt-floating-action-buttons/index.js
  packages/components/bolt-floating-action-buttons/index.scss
  packages/components/bolt-floating-action-buttons/package.json
  packages/components/bolt-floating-action-buttons/src/floating-action-buttons-li.twig
  packages/components/bolt-floating-action-buttons/src/floating-action-buttons-toggle-button.twig
  packages/components/bolt-floating-action-buttons/src/floating-action-buttons-ul.twig
  packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
  packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
  packages/components/bolt-floating-action-buttons/src/floating-action-buttons.twig
  packages/core-v3.x/styles/01-settings/settings-z-index/_settings-z-index.scss
  packages/elements/bolt-button/src/button.scss
Labels: type: feature

#2481 DS-540: scroll to top demo warning
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-05a-floating-action-buttons-demo.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-10a-floating-action-buttons-demo-show-on-scroll-selector.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-15a-floating-action-buttons-demo-toggle-button.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-999a-floating-action-buttons-demo-use-case-offsets.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/05-floating-action-buttons.twig
Labels: type: feature
