Repository boltdesignsystem/bolt, pull requests merged in 2022-02, with the labels that each got.

#2432 Hotfix v5.2.1
  docs-site/src/pages/pattern-lab/_patterns/999-tests/tooltip/15-tooltip-link-whitespace.twig
  packages/components/bolt-popover/src/popover.js
  packages/components/bolt-tooltip/src/tooltip.js
  scripts/deploy-tagged-release.js
  scripts/package.json
Labels: version: patch

#2433 Fix: namespace Page Footer component code
  packages/components/bolt-page-footer/src/page-footer-nav-li.twig
  packages/components/bolt-page-footer/src/page-footer-nav-ul.twig
  packages/components/bolt-page-footer/src/page-footer.scss
  packages/components/bolt-page-footer/src/page-footer.twig
Labels: type: bugfix

#2434 Fix: add max width to regular modal
  packages/components/bolt-modal/src/modal.scss
Labels: type: bugfix

#2435 Hotfix v5.2.2
  packages/components/bolt-modal/src/modal.scss
  packages/components/bolt-page-footer/src/page-footer-nav-li.twig
  packages/components/bolt-page-footer/src/page-footer-nav-ul.twig
  packages/components/bolt-page-footer/src/page-footer.scss
  packages/components/bolt-page-footer/src/page-footer.twig
Labels: version: patch

#2439 update chromedriver to 98.0.0
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#2441 WWW-1289 fix page footer button's chevron placement in iOS 14
  packages/components/bolt-page-footer/src/page-footer.scss
Labels: type: bugfix

#2442 WWW-1284: Remove reference to undefined `themes` variable
  packages/experimental/micro-journeys/src/interactive-pathways.js
Labels: type: bugfix

#2428 DS-692 Animation Tool Set (edits)
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/banner-test-fade-ins.twig
  packages/global/styles/06-animations/_999-animations-on-load-test.js
  packages/global/styles/06-animations/_animations.scss
Labels: type: feature

#2443 DS-734: Tooltip aria_type Prop
  packages/components/bolt-tooltip/src/tooltip.js
  packages/components/bolt-tooltip/tooltip.schema.js
Labels: type: feature

#2444 Hotfix: footer and micro journeys
  packages/components/bolt-page-footer/src/page-footer.scss
  packages/experimental/micro-journeys/src/interactive-pathways.js
Labels: version: patch

#2419 DS-692 Animation Tool Set
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/banner-test-fade-ins.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/gallery-test-fade-ins.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/icon-test-fade-ins.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/video-test-bounce-ins.twig
  packages/global/styles/00-vars/_vars-animation.scss
  packages/global/styles/06-animations/_999-animations-on-load-test.js
  packages/global/styles/06-animations/_animations-bounce-in.scss
  packages/global/styles/06-animations/_animations-bounce-out.scss
  packages/global/styles/06-animations/_animations-fade-in.scss
  packages/global/styles/06-animations/_animations-fade-out.scss
  packages/global/styles/06-animations/_animations-zoom-in.scss
  packages/global/styles/06-animations/_animations-zoom-out.scss
  packages/global/styles/06-animations/_animations.scss
  packages/global/styles/index.js
  packages/global/styles/index.scss
Labels: type: feature
