Repository boltdesignsystem/bolt, pull requests merged in 2022-03, with the labels that each got.

#2417 WWW-1112 mock up user sign up page
  docs-site/src/assets/images/heros/hero-foreground-pega-registration.png
  docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-sign-up.twig
Labels: type: feature

#2445 Brightcove Playback Rates update
  packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
Labels: type: feature

#2448 Fix: page header pulse icon link for Saleshub
  docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/-page-header-example-saleshub.twig
  packages/components/bolt-page-header/src/_page-header-desktop.scss
  packages/components/bolt-page-header/src/page-header-nav-li.twig
Labels: version: patch

#2446 WWW-850 add subtitle icon
  packages/elements/bolt-icon/__tests__/__snapshots__/icon.js.snap
  packages/elements/bolt-icon/icon.schema.json
  packages/elements/bolt-icon/src/icons/js/pega-subtitle.js
  packages/elements/bolt-icon/src/icons/svgs/pega-subtitle.svg
  packages/elements/bolt-icon/src/icons/twig/pega-subtitle.twig
Labels: type: feature

#2440 Ds 729 Scope button state styles to a and button elements
  docs-site/src/pages/pattern-lab/_patterns/999-tests/button/00-button-without-states.twig
  packages/elements/bolt-button/src/button.scss
Labels: type: feature

#2429 DS-690: Remove Nightwatch
  .travis.yml
  jest.config.js
  package.json
  packages/build-tools/package.json
  packages/build-tools/tasks/api-tasks/bolt-status-board.js
  packages/components/bolt-accordion/__tests__/accordion.e2e.js
  packages/components/bolt-blockquote/__tests__/bolt-blockquote.e2e.js
  packages/components/bolt-carousel/__tests__/bolt-carousel.e2e.js
  packages/components/bolt-copy-to-clipboard/__tests__/copy-to-clipboard.no2e.js
  packages/components/bolt-image/__tests__/bolt-image.e2e.js
  packages/components/bolt-modal/__tests__/modal.e2e.js
  packages/components/bolt-sticky/__tests__/sticky.no2e.js
  packages/components/bolt-tabs/__tests__/tabs.e2e.js
  packages/components/bolt-trigger/__tests__/trigger.e2e.js
  packages/components/bolt-typeahead/__tests__/typeahead.e2e.js
  packages/testing/testing-helpers/package.json
  packages/testing/testing-nightwatch/CHANGELOG.md
  packages/testing/testing-nightwatch/nightwatch-report-results.js
  packages/testing/testing-nightwatch/nightwatch.handle-results.js
  packages/testing/testing-nightwatch/nightwatch.js
  packages/testing/testing-nightwatch/nightwatch.local.js
  packages/testing/testing-nightwatch/package.json
  scripts/package.json
  yarn.lock
Labels: type: feature

#2452 DS-630: Screenreader Keypress Navigation in Page Header
  packages/components/bolt-page-header/src/page-header-nav.js
  packages/components/bolt-page-header/src/page-header.js
Labels: type: feature

#2454 DS-745 Support PHP 8
  docs-site/composer.json
  docs-site/composer.lock
  docs-site/config/config.yml
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/_archive/_20-loop.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/_archive/_21-loop--without-enough-slides.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/03-organisms/collections/dashboard/_dashboard-band--in-progress.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/03-organisms/collections/dashboard/_dashboard-band--my-favorite-training.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/03-organisms/collections/dashboard/_dashboard-band--new-training.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/03-organisms/collections/dashboard/_dashboard-band--recommended.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/03-organisms/collections/search/_search-results--results-list.twig
  docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/05-pages/t1-landing-pages/mission-landing/acd-mission-landing.twig
  packages/twig-integration/drupal-module/composer.json
  packages/twig-integration/twig-extensions-shared/composer.json
  packages/twig-integration/twig-extensions-shared/composer.lock
  packages/twig-integration/twig-extensions-shared/src/Images.php
  packages/twig-integration/twig-extensions-shared/src/TwigExtensions/BoltCore.php
  packages/twig-integration/twig-extensions-shared/src/TwigExtensions/Faker.php
  packages/twig-integration/twig-extensions-shared/src/TwigFunctions.php
  packages/twig-integration/twig-extensions-shared/tests/ImagesTest.php
  packages/twig-integration/twig-renderer/SetupTwigRenderer.php
  packages/twig-integration/twig-renderer/composer.lock
Labels: type: feature

#2455 Fix: typeahead search button misalignment
  packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
  packages/components/bolt-typeahead/typeahead.js
  packages/components/bolt-typeahead/typeahead.scoped.scss
  packages/components/bolt-typeahead/typeahead.twig
Labels: type: bugfix

#2451 DC-337: Video Thumbnail Inline Play Functionality
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/65-listing-teaser-use-case-search-result-list.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/00-video-thumbnail-docs.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/05-video-thumbnail.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/10-video-thumbnail-aspect-ratio.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/15-video-thumbnail-border-radius.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/20-video-thumbnail-title-chips-and-subtitles.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/25-video-thumbnail-use-case-modal.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/30-video-thumbnail-use-case-inline.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/video-thumbnail/35-video-thumbnail-external-link.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/70-community/-community-search-layout.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-15-oclp-gated-video.twig
  docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-25-oclp-ungated-video.twig
  packages/components/bolt-video-thumbnail/__tests__/__snapshots__/video-thumbnail.js.snap
  packages/components/bolt-video-thumbnail/__tests__/video-thumbnail.js
  packages/components/bolt-video-thumbnail/index.js
  packages/components/bolt-video-thumbnail/package.json
  packages/components/bolt-video-thumbnail/src/video-thumbnail.js
  packages/components/bolt-video-thumbnail/src/video-thumbnail.scss
  packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
  packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
  packages/twig-integration/twig-extensions-shared/src/TwigFilters.php
Labels: type: feature

#2457 PP-563 add search button label for search input
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/40-form-search.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/45-form-use-case-campaign-landing.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/50-form-use-case-inline-inputs.twig
  docs-site/src/pages/pattern-lab/_patterns/999-tests/form/00-form-search-fields.twig
  packages/components/bolt-form/__tests__/__snapshots__/form.js.snap
  packages/components/bolt-form/src/form-icons.twig
  packages/components/bolt-form/src/inputs/form-input.twig
Labels: type: feature

#2453 DS-737 multi-column form layout and grid spacing fix
  docs-site/.incache
  docs-site/src/assets/images/backgrounds/contact.jpg
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/-55a-form-demo-multiple-columns.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/55-form-use-case-multiple-columns.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/form/55a-form-demo-multiple-columns.md
  docs-site/src/pages/pattern-lab/_patterns/40-components/grid/15-grid-gutter-variations.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/grid/20-grid-row-gutter-variations.twig
  packages/components/bolt-grid/grid-item.schema.js
  packages/components/bolt-grid/grid.schema.js
  packages/components/bolt-grid/package.json
  packages/components/bolt-grid/src/_grid-item.scss
  packages/components/bolt-grid/src/_grid-item.twig
  packages/components/bolt-grid/src/grid.scss
  packages/components/bolt-grid/src/grid.twig
Labels: type: feature

#2462 DS 748 update ordered list formats in article element
  docs-site/src/pages/pattern-lab/_patterns/20-elements/article/05-article.twig
  packages/elements/bolt-article/src/article.scss
Labels: type: feature

#2464 DS-752 Remove ssr-server and all related code (Part 1)
  docs-site/.boltrc.js
  docs-site/package.json
  docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/999-carousel-with-web-component.twig
  docs-site/src/pages/pattern-lab/_patterns/40-components/text/999-text-ssr-with-twig-filter.twig
  packages/build-tools/cli.js
  packages/build-tools/utils/config-store.js
  packages/build-tools/utils/config.schema.yml
  packages/components/bolt-image/src/image.js
  packages/servers/ssr-server/.patches/document-register-element+1.13.1.patch
  packages/servers/ssr-server/CHANGELOG.md
  packages/servers/ssr-server/index.js
  packages/servers/ssr-server/libs/render/RenderBackend.js
  packages/servers/ssr-server/libs/render/Renderer.js
  packages/servers/ssr-server/libs/render/backend/jsdom/FilesystemResourceLoader.js
  packages/servers/ssr-server/libs/render/backend/jsdom/JsDomRenderBackend.js
  packages/servers/ssr-server/libs/render/backend/jsdom/index.js
  packages/servers/ssr-server/libs/render/backend/jsdom/template.js
  packages/servers/ssr-server/libs/render/backend/pupeteer/PupeteerRenderBackend.js
  packages/servers/ssr-server/libs/render/backend/pupeteer/index.js
  packages/servers/ssr-server/libs/render/index.js
  packages/servers/ssr-server/libs/render/renderer/WebComponentRenderer.js
  packages/servers/ssr-server/package.json
  packages/twig-integration/twig-extensions-shared/src/SSR/SSRTagNode.php
  packages/twig-integration/twig-extensions-shared/src/SSR/SSRTagTokenParser.php
  packages/twig-integration/twig-extensions-shared/src/TwigExtensions/BoltCoreCompat.php
  packages/twig-integration/twig-extensions-shared/src/TwigExtensions/BoltExtras.php
  packages/twig-integration/twig-extensions-shared/src/TwigFilters.php
  packages/twig-integration/twig-extensions-shared/src/TwigFunctions.php
  packages/twig-integration/twig-extensions-shared/src/TwigRenderer.php
  packages/twig-integration/twig-extensions-shared/src/TwigRendererSSR.php
  packages/twig-integration/twig-extensions-shared/src/TwigTags.php
  yarn.lock
Labels: type: feature
